(mes
 (meta (engine 'ADV) (charset "pc98"))
 (seg*
  ((cmd 206) 1 3)
  (sound '|| 0)
  (exec-mem 10496 2 32 5 127 66 61 29 61 29 0 50)
  ((cmd 197) 0 0)
  ((cmd 197) 1 0)
  (image-file "A:¥GRAPH¥BL105.GPC") (image-mem 1 1)
  (image-file "A:¥GRAPH¥BL105A.GPC") (image-mem 1 1)
  ((cmd 193) 0 "A:¥ANIME¥BL106.GPA")
  ((cmd 194) 0 "ｱ. ｱ..ｴ..ｵ..ｶ...ｵ.ｲ.ｳ..ｲｱ..ｶ.ｱ. .ｴ...ｶｱ .")
  ((cmd 193) 1 "A:¥ANIME¥BL105.GPA")
  ((cmd 196) 1 11)
  (exec-mem 10496 1 61 29 61 29 32 5 127 66 8 50)
  (text-frame 17 284 76 340)
  (text-reset 14)
  (proc 4) (str "Sheila: ") (proc 2)
     (str "What is this place?")
  (proc 3)
  (proc 4) (str "Cole: ") (proc 0)
   (str "There's large machinery everywhere. Just what goes on" 'br)
   (str "in here?")
  (proc 3)
  (text-frame 17 284 76 340)
  (text-reset 14)
  ((cmd 182) "A:¥CLM¥BL105.CLM")
  (exec-mem 16384 0 0 1 1)
  (exec-mem 256 2)
  (nop@)
  (set-reg 0 #t)
  (loop
   ((cmd 182) P 0)
   (if (</>
        (//
         (? (= Q 1))
         (nop@)
         (exec-mem 16384 0 0 1 1)
         (exec-mem 256 2)
         (set-reg 0 #t))))
   (seg-call)
   ((cmd 197) 0 0)
   ((cmd 197) 1 0)))
 (seg (? (= Q 9) (= 0 #t) (= 10 #f))
   (proc 4) (str "Cole: ") (proc 0)
    (str "There are many large machines.")
   (proc 3)
   (proc 4) (str "Sheila: ") (proc 2)
      (str "What's this room for?")
   (set-reg 10 #t)
   (proc 3))
 (seg (? (= Q 9) (= 0 #t))
   (proc 4) (str "Cole: ") (proc 0)
    (str "A large machine. I have no idea what it does.")
   (proc 3))
 (seg (? (= Q 10) (= 0 #t) (= 10 #t) (= 12 #t) (= 16 #t))
   (proc 4) (str "Cole: ") (proc 0)
    (str "The hell? Someone's trapped in that capsule!")
   (proc 3)
   (proc 4) (str "Sheila: ") (proc 2)
      (str "Ah!")
   (proc 3)
   (image-file "A:¥GRAPH¥BL106.GPC") (image-mem 1 1)
   (sound '|| 0)
   (sound '|se | 22)
   (proc 4) (str "Cole: ") (proc 0)
    (str "Cain?!")
   (proc 3)
   ((cmd 197) 0 15)
   (proc 4) (str "Cain: ") (proc 1)
    (str "Cole! What're you doing here?!")
   (proc 3)
   ((cmd 197) 0 0)
   (proc 4) (str "Sheila: ") (proc 2)
      (str "Cain!!!")
   (proc 3)
   (proc 4) (str "Cole: ") (proc 0)
    (str "What are you doing in that thing?")
   (proc 3)
   ((cmd 197) 0 15)
   (proc 4) (str "Cain: ") (proc 1)
    (str "It's him... it's Ghoul!")
   (proc 3)
   ((cmd 197) 0 0)
   (proc 4) (str "Cole: ") (proc 0)
    (str "Hang on, Cain, I'll open it!")
   (proc 3)
   ((cmd 196) 1 12)
   (delay 4)
   ((cmd 196) 1 11)
   (delay 4)
   ((cmd 196) 1 10)
   (delay 4)
   ((cmd 196) 1 9)
   (delay 4)
   ((cmd 196) 1 8)
   (delay 4)
   ((cmd 196) 1 7)
   (delay 4)
   ((cmd 196) 1 6)
   (delay 4)
   ((cmd 196) 1 5)
   (delay 4)
   ((cmd 196) 1 4)
   (delay 4)
   ((cmd 196) 1 3)
   (delay 4)
   ((cmd 196) 1 2)
   (delay 4)
   ((cmd 196) 1 1)
   (delay 4)
   ((cmd 196) 1 0)
   (text-color 15)
   (str "Man's Voice: Cole, the capsule can only be opened from" 'br)
   (str "here")
   (str ".")
   (exec-mem 16384 0 0 2 1)
   (proc 3)
   (proc 4) (str "Sheila: ") (proc 2)
      (str "Cole, look!")
   (proc 3)
   (proc 4) (str "Cole: ") (proc 0)
    (str "Ghoul!")
   (proc 3)
   (proc 4) (str "Ghoul: ") (proc 1)
     (str "Looks like a pair of rodents have made their way" 'br)
   (str "into our sanctum.")
   (proc 3)
   (proc 4) (str "Cole: ") (proc 0)
    (str "Ghoul! You motherfucker!")
   (proc 3)
   (proc 4) (str "Ghoul: ") (proc 1)
     (str "I betrayed that fool Killer, but it seems you" 'br)
   (str "somehow survived. I'll never forget your dumb faces when I" 'br)
   (str "was shooting at you from the chopper.")
   (proc 3)
   (proc 4) (str "Cole: ") (proc 0)
    (str "What's your intent?! Why are you doing these things?!" 'br)
   (str "Slaughtering the innocent is fun, huh?!")
   (proc 3)
   (proc 4) (str "Ghoul: ") (proc 1)
     (str "My goal? What goal? I think it's fun to play with" 'br)
   (str "humans.")
   (proc 3)
   (proc 4) (str "Ghoul: ") (proc 1)
     (str "I've seen hundreds die. There's nothing more fun" 'br)
   (str "than seeing humans struggle so much to live.")
   (proc 3)
   (proc 4) (str "Cole: ") (proc 0)
    (str "You killed all those people at the hotel for such a" 'br)
   (str "trivial goal! They were all good people!")
   (proc 3)
   (proc 4) (str "Ghoul: ") (proc 1)
     (str "Trivial? What goals do people usually die for?" 'br)
   (str "Money? Honor? Idiotic goals if I've ever heard them!")
   (proc 3)
   (proc 4) (str "Ghoul: ") (proc 1)
     (str "It's so entertaining to watch people die by my own" 'br)
   (str "hand! Is there anyone these days who can say they've lived" 'br)
   (str "truly for themselves to such a degree?")
   (proc 3)
   (proc 4) (str "Cole: ") (proc 0)
    (str "This isn't a game! Losing loved ones is a part of" 'br)
   (str "life!")
   (proc 3)
   (proc 4) (str "Ghoul: ") (proc 1)
     (str "Hahaha...")
   (proc 3)
   (proc 4) (str "Cole: ") (proc 0)
    (str "What's wrong?")
   (proc 3)
   (proc 4) (str "Ghoul: ") (proc 1)
     (str "Will you flee and leave your love to die here?")
   (proc 3)
   (proc 4) (str "Cole: ") (proc 0)
    (str "Huh?!")
   (proc 3)
   (proc 4) (str "Ghoul: ") (proc 1)
     (str "Didn't you shoot Cooger? Wasn't he your best friend?")
   (proc 3)
   (proc 4) (str "Cole: ") (proc 0)
    (str "Doc knew he was gonna be a zombie. If I were him, I'd" 'br)
   (str "do the same!")
   (proc 3)
   (proc 4) (str "Ghoul: ") (proc 1)
     (str "You shot your best friend. I think I see promise in" 'br)
   (str "you.")
   (proc 3)
   (proc 4) (str "Ghoul: ") (proc 1)
     (str "Don't be like Killer. Join me and we can have fun" 'br)
   (str "killing these fools together!")
   (proc 3)
   (proc 4) (str "Cole: ") (proc 0)
    (str "Don't act like that! You're mad! You've killed all" 'br)
   (str "those people!")
   (proc 3)
   (sound '|se | 9)
   (delay 8)
   (sound '|se | 8)
   (delay 8)
   (sound '|se | 9)
   (proc 4) (str "Cole: ") (proc 0)
    (str "What? Bulletproof?!")
   (proc 3)
   (proc 4) (str "Ghoul: ") (proc 1)
     (str "It's idiotic to refuse such an invitation. Don't" 'br)
   (str "worry though, I have a trump card that'll make you bend to" 'br)
   (str "my will!")
   (proc 3)
   (proc 4) (str "Ghoul: ") (proc 1)
     (str "It'll be fun. I have something here that combines" 'br)
   (str "Cooger's resurrection drug with every chemical in this" 'br)
   (str "facility!")
   (proc 3)
   (proc 4) (str "Ghoul: ") (proc 1)
     (str "It's in liquid form, but if I put it in here, it" 'br)
   (str "vaporizes into a gas.")
   (proc 3)
   (proc 4) (str "Ghoul: ") (proc 1)
     (str "What happens when you use it on a human? Hell if I" 'br)
   (str "know! Let's find out!")
   (proc 3)
   (proc 4) (str "Sheila: ") (proc 2)
      (str "Please! Cole, do something!")
   (proc 3)
   (proc 4) (str "Cole: ") (proc 0)
    (str "Ghoul... I'll do whatever you please. Just let Cain" 'br)
   (str "out!")
   (proc 3)
   (proc 4) (str "Ghoul: ") (proc 1)
     (str "You should've said that from the beginning...")
   (proc 3)
   (proc 4) (str "Ghoul: ") (proc 1)
     (str "Oh well! I didn't wait for your response! The drug" 'br)
   (str "is already a gas! Ha!")
   (proc 3)
   (proc 4) (str "Cole: ") (proc 0)
    (str "Cain!!!")
   (proc 3)
   ((cmd 197) 0 15)
   (proc 4) (str "Cain: ") (proc 1)
    (str "Cole. If I die here, please avenge me! Stop this" 'br)
   (str "lunatic! Avenge my family!")
   (proc 3)
   ((cmd 197) 0 0)
   (proc 4) (str "Sheila: ") (proc 2)
      (str "No!! Please! Help!")
   (proc 3)
   (proc 4) (str "Cole: ") (proc 0)
    (str "Cain!!!")
   (proc 3)
   ((cmd 197) 0 15)
   (proc 4) (str "Cain: ") (proc 1)
    (str "Sheila, don't worry...")
   (proc 3)
   ((cmd 193) 0 "A:¥ANIME¥BL106A.GPA")
   (proc 4) (str "Cain: ") (proc 1)
    (str "Aghhh!")
   ((cmd 196) 0 0)
   (delay 3)
   ((cmd 196) 0 1)
   (delay 3)
   ((cmd 196) 0 2)
   (delay 3)
   ((cmd 196) 0 3)
   (delay 3)
   ((cmd 196) 0 4)
   (proc 3)
   ((cmd 198) 32 5 127 66 0)
   ((cmd 197) 0 0)
   ((cmd 197) 1 0)
   (image-file "A:¥GRAPH¥BL105.GPC") (image-mem 1 1)
   (image-file "A:¥GRAPH¥BL105A.GPC") (image-mem 1 1)
   ((cmd 198) 32 5 127 66 15)
   (text-reset 14)
   (proc 4) (str "Ghoul: ") (proc 1)
     (str "Now it's your turn! Here's 400ml of the gaseous" 'br)
   (str "concoction! It'll fill the lab in 20 seconds! Such a shame I" 'br)
   (str "can't see the effects from behind this wall!")
   (proc 3)
   (proc 4) (str "Cole: ") (proc 0)
    (str "Sheila, we have to get out of here!")
   (proc 3)
   (proc 4) (str "Sheila: ") (proc 2)
      (str "Ahhh!")
   (proc 3)
   (proc 4) (str "Cole: ") (proc 0)
    (str "Shit! He's dropped a shutter! We're trapped!")
   (proc 3)
   (proc 4) (str "Ghoul: ") (proc 1)
     (str "Sorry, Cole! Ha!")
   ((cmd 193) 1 "A:¥ANIME¥BL105.GPA")
   (proc 3)
   ((cmd 196) 1 0)
   ((cmd 196) 1 1)
   (delay 4)
   ((cmd 196) 1 2)
   (delay 4)
   ((cmd 196) 1 3)
   (delay 4)
   ((cmd 196) 1 4)
   (delay 4)
   ((cmd 196) 1 5)
   (delay 4)
   ((cmd 196) 1 6)
   (delay 4)
   ((cmd 196) 1 7)
   (delay 4)
   ((cmd 196) 1 8)
   (delay 4)
   ((cmd 196) 1 9)
   (delay 4)
   ((cmd 196) 1 10)
   (delay 4)
   ((cmd 196) 1 11)
   (delay 4)
   ((cmd 196) 1 12)
   (sound '|| 0)
   (mes-jump "A:¥MES¥000063.MES"))
 (seg (? (= Q 10) (= 0 #t) (= 11 #f))
   (proc 4) (str "Cole: ") (proc 0)
    (str "There's something in the middle of the room. Is this a capsule?")
   (set-reg 11 #t)
   (proc 3))
 (seg (? (= Q 10) (= 0 #t))
   (proc 4) (str "Cole: ") (proc 0)
    (str "What are these big capsules for?")
   (proc 3))
 (seg (? (= Q 11) (= 0 #t) (= 12 #f))
   (proc 4) (str "Sheila: ") (proc 2)
      (str "There's a big window up there.")
   (proc 3)
   (proc 4) (str "Cole: ") (proc 0)
    (str "I see a console. Can't do anything with it from here.")
   (set-reg 12 #t)
   (proc 3))
 (seg (? (= Q 11) (= 0 #t))
   (proc 4) (str "Cole: ") (proc 0)
    (str "It's a glass shield? I can't see it there from here.")
   (proc 3))
 (seg (? (= Q 12) (= 0 #t) (= 13 #f))
   (proc 4) (str "Cole: ") (proc 0)
    (str "This cable is connected to the capsule. It's thick," 'br)
   (str "so it's probably for something besides power.")
   (set-reg 13 #t)
   (proc 3))
 (seg (? (= Q 12) (= 0 #t))
   (proc 4) (str "Cole: ") (proc 0)
    (str "The cable goes from the wall to the capsule.")
   (proc 3))
 (seg (? (= Q 13) (= 0 #t) (= 14 #f))
   (proc 4) (str "Cole: ") (proc 0)
    (str "This floor here is shiny. Very different from that" 'br)
   (str "tunnel.")
   (set-reg 14 #t)
   (proc 3))
 (seg (? (= Q 13) (= 0 #t))
   (proc 4) (str "Cole: ") (proc 0)
    (str "Our footprints are the only dirty thing on the clean" 'br)
   (str "floor. No trash or anything.")
   (proc 3))
 (seg (? (= Q 14) (= 0 #t) (= 15 #f))
   (proc 4) (str "Cole: ") (proc 0)
    (str "The walls are pretty clean.")
   (set-reg 15 #t)
   (proc 3))
 (seg (? (= Q 14) (= 0 #t))
   (proc 4) (str "Sheila: ") (proc 2)
      (str "It's quite a big room.")
   (proc 3)
   (proc 4) (str "Cole: ") (proc 0)
    (str "You'd expect a huge room like this in such a big" 'br)
   (str "laboratory.")
   (set-reg 16 #t)
   (proc 3))
 (seg (? (= Q 8))
   (exec-mem 16384 0 0 1 8)
   (exec-mem 256 7)
   (str "Select Save Number.")
   (menu1
    20
    305
    34
    305
    48
    305
    62
    305
    20
    325
    34
    325
    48
    325
    62
    325
    68
    285
    (</>
     (/ (str " SAVE No.1 "))
     (/ (str " SAVE No.2 "))
     (/ (str " SAVE No.3 "))
     (/ (str " SAVE No.4 "))
     (/ (str " SAVE No.5 "))
     (/ (str " SAVE No.6 "))
     (/ (str " SAVE No.7 "))
     (/ (str " SAVE No.8 "))
     (/ (str "[CANCEL]"))))
   (text-reset 14)
   (text-frame 41 305)
   (set-reg 48 #t)
   (text-color 15)
   (str "WAIT....")
   (branch-var
    S
    (</>
     (/ (flag-save 1))
     (/ (flag-save 2))
     (/ (flag-save 3))
     (/ (flag-save 4))
     (/ (flag-save 5))
     (/ (flag-save 6))
     (/ (flag-save 7))
     (/ (flag-save 8))
     (/ (nop@))))
   (text-frame 17 284 76 340)
   (text-reset 14)
   (exec-mem 16384 0 0 1 1)
   (exec-mem 256 2)
   (nop@)
   (set-reg 0 #t))
 (seg (? (= Q 7))
   (exec-mem 16384 0 0 1 7)
   (exec-mem 256 6)
   (str "Select Load Number.")
   (menu1
    20
    305
    34
    305
    48
    305
    62
    305
    20
    325
    34
    325
    48
    325
    62
    325
    68
    285
    (</>
     (/ (str " LOAD No.1 "))
     (/ (str " LOAD No.2 "))
     (/ (str " LOAD No.3 "))
     (/ (str " LOAD No.4 "))
     (/ (str " LOAD No.5 "))
     (/ (str " LOAD No.6 "))
     (/ (str " LOAD No.7 "))
     (/ (str " LOAD No.8 "))
     (/ (str "[CANCEL]"))))
   (text-reset 14)
   (branch-var
    S
    (</>
     (/
      (exec-mem 10496 2 32 5 127 66 32 36 127 36 0 50)
      (exec-mem 10496 0 32 5 127 66 0)
      (flag-load 1))
     (/
      (exec-mem 10496 2 32 5 127 66 32 36 127 36 0 50)
      (exec-mem 10496 0 32 5 127 66 0)
      (flag-load 2))
     (/
      (exec-mem 10496 2 32 5 127 66 32 36 127 36 0 50)
      (exec-mem 10496 0 32 5 127 66 0)
      (flag-load 3))
     (/
      (exec-mem 10496 2 32 5 127 66 32 36 127 36 0 50)
      (exec-mem 10496 0 32 5 127 66 0)
      (flag-load 4))
     (/
      (exec-mem 10496 2 32 5 127 66 32 36 127 36 0 50)
      (exec-mem 10496 0 32 5 127 66 0)
      (flag-load 5))
     (/
      (exec-mem 10496 2 32 5 127 66 32 36 127 36 0 50)
      (exec-mem 10496 0 32 5 127 66 0)
      (flag-load 6))
     (/
      (exec-mem 10496 2 32 5 127 66 32 36 127 36 0 50)
      (exec-mem 10496 0 32 5 127 66 0)
      (flag-load 7))
     (/
      (exec-mem 10496 2 32 5 127 66 32 36 127 36 0 50)
      (exec-mem 10496 0 32 5 127 66 0)
      (flag-load 8))
     (/ (nop@))))
   (exec-mem 16384 0 0 1 1)
   (exec-mem 256 2)
   (nop@)
   (set-reg 0 #t))
 (seg*))