(mes
 (meta (engine 'ADV) (charset "pc98"))
 (seg*
  ((cmd 206) 1 2)
  ((cmd 197) 0 0)
  ((cmd 197) 1 0)
  (image-file "A:¥GRAPH¥BL032.GPC") (image-mem 1 1)
  (sound '|| 0)
  (sound '|se | 10)
  (exec-mem 10496 1 32 36 127 36 32 5 127 66 8 50)
  (text-frame 17 284 76 340)
  (text-reset 14)
  (proc 4) (str "Cole: ") (proc 0)
   (str "Killer must've been in the meeting room a bit ago.")
  (proc 3)
  (exec-mem 16384 0 0 1 6)
  (exec-mem 256 4)
  (loop
   (menu1 18 300 38 300 (</> (/ (text "ＭＥＥＴＩＮＧ")) (/ (text "　　２２０　　"))))
   (text-reset 14)
   (seg-call)
   (if (</>
        (//
         (? (= 10 #t) (= 11 #t))
         (image-file "A:¥GRAPH¥BL036.GPC")
         ((cmd 198) 32 5 127 66 0)
         (image-mem 1 1)
         (exec-mem 16384 0 0 2 6)
         ((cmd 193) 0 "A:¥ANIME¥BL036.GPA")
         ((cmd 194) 0 "ｱｴ. ..ｶ....ｵ...ｴ..ｲｳ.ｵｲｱ..ｴ ....ｶ...ｴ....ｶ...ｴｱ")
         ((cmd 198) 32 5 127 66 15)
         (proc 4) (str "Cole: ") (proc 0)
          (str "Ghoul!")
         (proc 3)
         ((cmd 197) 0 15)
         (proc 4) (str "Ghoul: ") (proc 1)
           (str "Cole, what're you doing here? We already got the" 'br)
   (str "dispatch to move to the backup HQ.")
         (proc 3)
         ((cmd 197) 0 0)
         (proc 4) (str "Cole: ") (proc 0)
          (str "Huh? We're abandoning the hotel?")
         (proc 3)
         ((cmd 197) 0 15)
         (proc 4) (str "Ghoul: ") (proc 1)
           (str "Yeah, we're off to the Needle River Hospital. I was" 'br)
   (str "just about to leave.")
         (proc 3)
         (proc 4) (str "Ghoul: ") (proc 1)
           (str "Hold on. Who's this guy?")
         (proc 3)
         ((cmd 197) 0 0)
         (proc 4) (str "Cain: ") (proc 1)
          (str "I'm Cain. Nice to meet you.")
         (proc 3)
         ((cmd 197) 0 15)
         (proc 4) (str "Ghoul: ") (proc 1)
           (str "Ah, another survivor?")
         (proc 3)
         ((cmd 197) 0 0)
         (proc 4) (str "Cole: ") (proc 0)
          (str "Actually, I have a little story to tell you about" 'br)
   (str "Killer...")
         (proc 3)
         ((cmd 197) 0 15)
         (proc 4) (str "Ghoul: ") (proc 1)
           (str "First things first, can you get to the hospital to" 'br)
   (str "help out? Everyone's already there, so if you're quick, you" 'br)
   (str "won't be too late. We'll take a break once we arrive.")
         (proc 3)
         ((cmd 197) 0 0)
         (proc 4) (str "Cole: ") (proc 0)
          (str "Understood.")
         (proc 3)
         (proc 4) (str "Cole: ") (proc 0)
          (str "Huh?")
         (proc 3)
         ((cmd 197) 0 15)
         (proc 4) (str "Ghoul: ") (proc 1)
           (str "Also, it looks like we've got a swarm of zombies. We" 'br)
   (str "locked up well, so how the hell did they enter?")
         (proc 3)
         (proc 4) (str "Ghoul: ") (proc 1)
           (str "Cole and... Cain, right? You need to exterminate the" 'br)
   (str "zombies on the first floor. I'm going to the hospital now" 'br)
   (str "from the back door.")
         (proc 3)
         ((cmd 197) 0 0)
         (proc 4) (str "Cole: ") (proc 0)
          (str "Understood.")
         (proc 3)
         ((cmd 197) 0 15)
         (proc 4) (str "Ghoul: ") (proc 1)
           (str "I'm counting on the both of you.")
         (proc 3)
         ((cmd 197) 0 0)
         (image-file "A:¥GRAPH¥BL032.GPC")
         ((cmd 198) 32 5 127 66 0)
         (image-mem 1 1)
         ((cmd 198) 32 5 127 66 15)
         (proc 4) (str "Cain: ") (proc 1)
          (str "Is he a cop? Big badge on his shirt and all.")
         (proc 3)
         (proc 4) (str "Cole: ") (proc 0)
          (str "He's the Chief of the 16th Precinct and the leader of" 'br)
   (str "his zombie-killing team.")
         (proc 3)
         (proc 4) (str "Cain: ") (proc 1)
          (str "That was the chief? Seems like a tough guy.")
         (proc 3)
         (proc 4) (str "Cole: ") (proc 0)
          (str "We've got to get to the first floor, quickly!")
         (proc 3)
         (proc 4) (str "Cain: ") (proc 1)
          (str "Alright, let's do this!")
         (proc 3)
         (exec-mem 10496 2 32 5 127 66 32 36 127 36 0 50)
         (exec-mem 10496 0 32 5 127 66 0)
         (sound '|| 0)
         (mes-jump "A:¥MES¥000054.MES"))))))
 (seg (? (= T 0) (= 11 #t) (= 10 #f))
   ((cmd 198) 32 5 127 66 0)
   (image-file "A:¥GRAPH¥BL034.GPC") (image-mem 1 1)
   ((cmd 198) 32 5 127 66 15)
   (proc 4) (str "Cole: ") (proc 0)
    (str "Huh? Did everyone go to their rooms?")
   (proc 3)
   (proc 4) (str "Cain: ") (proc 1)
    (str "Where's this Killer guy?")
   (proc 3)
   (proc 4) (str "Cole: ") (proc 0)
    (str "I don't know. Wait, where's Sheila?")
   (set-reg 10 #t)
   (proc 3)
   (image-file "A:¥GRAPH¥BL032.GPC")
   ((cmd 198) 32 5 127 66 0)
   (image-mem 1 1)
   ((cmd 198) 32 5 127 66 15))
 (seg (? (= T 0) (= 10 #f) (= 11 #f))
   (proc 4) (str "Cain: ") (proc 1)
    (str "Cole, watch your back.")
   (proc 19)
   (proc 4) (str "Cole: ") (proc 0)
    (str "Yeah, got it.")
   (proc 3)
   ((cmd 198) 32 5 127 66 0)
   (image-file "A:¥GRAPH¥BL034.GPC") (image-mem 1 1)
   ((cmd 198) 32 5 127 66 15)
   (proc 4) (str "Cole: ") (proc 0)
    (str "Huh? Did everyone go to their rooms?")
   (proc 3)
   (proc 4) (str "Cain: ") (proc 1)
    (str "Where's this Killer guy?")
   (proc 3)
   (proc 4) (str "Cole: ") (proc 0)
    (str "I don't know. Wait, where's Sheila?")
   (set-reg 10 #t)
   (proc 3)
   (image-file "A:¥GRAPH¥BL032.GPC")
   ((cmd 198) 32 5 127 66 0)
   (image-mem 1 1)
   ((cmd 198) 32 5 127 66 15))
 (seg (? (= T 0))
   (proc 4) (str "Cain: ") (proc 1)
    (str "Cole, you didn't see anyone when you came in earlier," 'br)
   (str "right?")
   (proc 3)
   (proc 4) (str "Cole: ") (proc 0)
    (str "That's right...")
   (proc 3))
 (seg (? (= T 1) (= 11 #f) (= 10 #f))
   (proc 4) (str "Cole: ") (proc 0)
    (str "Let's go to my room for now.")
   (proc 3)
   (image-file "A:¥GRAPH¥BL042.GPC")
   ((cmd 198) 32 5 127 66 0)
   (image-mem 1 1)
   ((cmd 198) 32 5 127 66 15)
   (proc 4) (str "Cole: ") (proc 0)
    (str "Huh? Where's Sheila? I told her to wait here.")
   (proc 3)
   (proc 4) (str "Cole: ") (proc 0)
    (str "Maybe she's in the meeting room with everyone else.")
   (proc 3)
   (proc 4) (str "Cain: ") (proc 1)
    (str "We've gotta find Killer he gets to Sheila.")
   (set-reg 11 #t)
   (proc 3)
   (image-file "A:¥GRAPH¥BL032.GPC")
   ((cmd 198) 32 5 127 66 0)
   (image-mem 1 1)
   ((cmd 198) 32 5 127 66 15))
 (seg (? (= T 1) (= 10 #t) (= 11 #f))
   (proc 4) (str "Cain: ") (proc 1)
    (str "Does Sheila know which room Killer's staying in?")
   (proc 3)
   (proc 4) (str "Cole: ") (proc 0)
    (str "Maybe...")
   (proc 3)
   (image-file "A:¥GRAPH¥BL042.GPC")
   ((cmd 198) 32 5 127 66 0)
   (image-mem 1 1)
   ((cmd 198) 32 5 127 66 15)
   (proc 4) (str "Cole: ") (proc 0)
    (str "Where'd Sheila go?")
   (proc 3)
   (proc 4) (str "Cain: ") (proc 1)
    (str "Cole, if it comes to it, it's best to search every" 'br)
   (str "room in the hotel.")
   (proc 3)
   (proc 4) (str "Cole: ") (proc 0)
    (str "You can't get into the rooms without an ID card...")
   (proc 3)
   (proc 4) (str "Cain: ") (proc 1)
    (str "Don't worry, I'll open it for ya.")
   (set-reg 11 #t)
   (proc 3)
   (image-file "A:¥GRAPH¥BL032.GPC")
   ((cmd 198) 32 5 127 66 0)
   (image-mem 1 1)
   ((cmd 198) 32 5 127 66 15))
 (seg (? (= T 1))
   (proc 4) (str "Cain: ") (proc 1)
    (str "Cole, was no one here when you came?")
   (proc 19)
   (proc 4) (str "Cole: ") (proc 0)
    (str "That's right.")
   (proc 3))
 (seg*))