(mes
 (meta (engine 'ADV) (charset "pc98"))
 (seg*
  ((cmd 206) 1 2)
  ((cmd 197) 0 0)
  ((cmd 197) 1 0)
  (image-file "A:¥GRAPH¥BL034.GPC") (image-mem 1 1)
  (image-file "A:¥GRAPH¥BL035G.GPC") (image-mem 1 1)
  (image-file "A:¥GRAPH¥BL035S.GPC") (image-mem 1 1)
  (image-file "A:¥GRAPH¥BL035N.GPC") (image-mem 1 1)
  (image-file "A:¥GRAPH¥BL035R.GPC") (image-mem 1 1)
  (image-file "A:¥GRAPH¥BL033.GPC") (image-mem 1 1)
  ((cmd 193) 0 "A:¥ANIME¥BL033.GPA")
  ((cmd 194) 0 "ｱｴ. ..ｶ....ｵ...ｴ..ｲｳ.ｵｲｱ..ｴ. ...ｶ...ｴ....ｶ...ｴｱ .")
  (sound '|| 0)
  (sound '|| "A:¥MUSIC¥B0N_07.USO")
  (sound '|| 1)
  ((cmd 198) 32 5 127 66 15)
  (text-frame 17 284 76 340)
  (text-reset 14)
  (if (</>
       (//
        (? (= 43 #f))
        ((cmd 197) 0 15)
        (proc 4) (str "Killer: ") (proc 1)
           (str "Cole, I just checked downstairs. You did a good" 'br)
   (str "job.")
        (proc 3)
        ((cmd 197) 0 0)
        (proc 4) (str "Cole: ") (proc 0)
         (str "Ah. Thank you.")
        (proc 3)
        ((cmd 197) 0 15)
        (proc 4) (str "Killer: ") (proc 1)
           (str "That man you were here with. I saw his corpse as" 'br)
   (str "well...")
        (proc 3)
        ((cmd 197) 0 0)
        (proc 4) (str "Cole: ") (proc 0)
         (str "Yeah, sadly, when I realized he was already bit..." 'br)
   (str "well...")
        (proc 3)
        ((cmd 197) 0 15)
        (proc 4) (str "Killer: ") (proc 1)
           (str "Ugh. That's awful. I'm sorry to hear it.")
        (proc 3)
        ((cmd 197) 0 0)
        (proc 4) (str "Cole: ") (proc 0)
         (str "Yeah...")
        (set-reg 43 #t)
        (proc 3)
        ((cmd 197) 0 15)
        (proc 4) (str "Killer: ") (proc 1)
           (str "Cole, what're you up to now?")
        (proc 3))))
  ((cmd 197) 0 0)
  ((cmd 182) "A:¥CLM¥BL033.CLM")
  (exec-mem 16384 0 0 1 1)
  (exec-mem 256 2)
  (nop@)
  (set-reg 0 #f)
  (set-reg 1 #t)
  (loop
   ((cmd 182) P 0)
   (if (</>
        (//
         (? (= Q 1))
         (nop@)
         (exec-mem 16384 0 0 1 1)
         (exec-mem 256 2)
         (set-reg 0 #f)
         (set-reg 1 #t))
        (//
         (? (= Q 2))
         (nop@)
         (exec-mem 16384 0 0 1 2)
         (exec-mem 256 1)
         (set-reg 0 #t)
         (set-reg 1 #t))
        (//
         (? (= Q 4))
         (nop@)
         (exec-mem 16384 0 0 1 4)
         (exec-mem 256 3)
         (set-reg 0 #f)
         (set-reg 1 #f))))
   (seg-call)
   ((cmd 197) 0 0)))
 (seg (? (= Q 9) (= 0 #f) (= 1 #t) (= 44 #f))
   (proc 4) (str "Cole: ") (proc 0)
    (str "I've been thinking of this man since yesterday." 'br)
   (str "Killer has an old Chinese face, like a TV character's.")
   (set-reg 44 #t)
   (proc 3))
 (seg (? (= Q 9) (= 0 #f) (= 1 #t) (= 45 #f))
   (proc 4) (str "Cole: ") (proc 0)
    (str "It's a sharp face. I wonder if it makes him look" 'br)
   (str "scary when interrogating people.")
   (set-reg 45 #t)
   (proc 3))
 (seg (? (= Q 9) (= 0 #f) (= 1 #t))
   (proc 4) (str "Cole: ") (proc 0)
    (str "His face is fine but quite scary.")
   (proc 3))
 (seg (? (= Q 10) (= 0 #f) (= 1 #t) (= 46 #f))
   (proc 4) (str "Cole: ") (proc 0)
    (str "Not bad. His shoulders are broader than mine. Maybe I" 'br)
   (str "can beat him in a fight.")
   (set-reg 46 #t)
   (proc 3))
 (seg (? (= Q 10) (= 0 #f) (= 1 #t) (= 47 #f))
   (proc 4) (str "Cole: ") (proc 0)
    (str "He's quite fashionable for a cop.")
   (set-reg 47 #t)
   (proc 3))
 (seg (? (= Q 10) (= 0 #f) (= 1 #t))
   (proc 4) (str "Cole: ") (proc 0)
    (str "Looks like he has a good gun on that shoulder" 'br)
   (str "harness.")
   (proc 3))
 (seg (? (= Q 11) (= 0 #f) (= 1 #t) (= 49 #f))
   (proc 4) (str "Cole: ") (proc 0)
    (str "I need a harness like that. I had my gun in my pocket" 'br)
   (str "yesterday.")
   (set-reg 49 #t)
   (proc 3))
 (seg (? (= Q 11) (= 0 #f) (= 1 #t))
   (proc 4) (str "Cole: ") (proc 0)
    (str "I was almost shot dead with that gun yesterday.")
   (proc 3))
 (seg (? (= Q 9) (= 0 #t) (= 1 #t) (= 50 #f))
   (proc 4) (str "Cole: ") (proc 0)
    (str "On the second floor, if it wasn't for Doc, I would've" 'br)
   (str "been dead.")
   (proc 3)
   ((cmd 197) 0 15)
   (proc 4) (str "Killer: ") (proc 1)
      (str "There was a bullet hole in his head, point blank.")
   (proc 3)
   ((cmd 197) 0 0)
   (proc 4) (str "Cole: ") (proc 0)
    (str "He was bitten by a zombie... so I had to.")
   (proc 3)
   ((cmd 197) 0 15)
   (proc 4) (str "Killer: ") (proc 1)
      (str "I see. I've had to do stuff like that. I" 'br)
   (str "understand, Cole.")
   (set-reg 50 #t)
   (proc 3))
 (seg (? (= Q 9) (= 0 #t) (= 1 #t) (= 51 #f))
   ((cmd 197) 0 15)
   (proc 4) (str "Killer: ") (proc 1)
      (str "What sort of Doctor was Cooger?")
   (proc 3)
   ((cmd 197) 0 0)
   (proc 4) (str "Cole: ") (proc 0)
    (str "I've heard he mainly researches cancer cells. Why?")
   (proc 3)
   ((cmd 197) 0 15)
   (proc 4) (str "Killer: ") (proc 1)
      (str "Well, that lab coat he's wearing has a ton of" 'br)
   (str "stains. It's so odd.")
   (set-reg 51 #t)
   (proc 3))
 (seg (? (= Q 9) (= 0 #t) (= 1 #t) (= 52 #f))
   ((cmd 197) 0 15)
   (proc 4) (str "Killer: ") (proc 1)
      (str "Sheila, was that her name? Where is she?")
   (proc 3)
   ((cmd 197) 0 0)
   (proc 4) (str "Cole: ") (proc 0)
    (str "She went to the market to get food. I thought she" 'br)
   (str "would be back by now.")
   (proc 3)
   ((cmd 197) 0 15)
   (proc 4) (str "Killer: ") (proc 1)
      (str "I also went out but I didn't see her. Not even a" 'br)
   (str "single zombie. All I saw were members of Bloody Fox.")
   (proc 3)
   (proc 4) (str "Killer: ") (proc 1)
      (str "I should've talked to Ray about it.")
   (proc 3)
   ((cmd 197) 0 0)
   (proc 4) (str "Cole: ") (proc 0)
    (str "Bloody Fox is that marauding gang, right? Was Ray a" 'br)
   (str "member?")
   (proc 3)
   ((cmd 197) 0 15)
   (proc 4) (str "Killer: ") (proc 1)
      (str "You didn't know that? Well, Ray used to be part of" 'br)
   (str "their gang.")
   (proc 3)
   ((cmd 197) 0 0)
   (proc 4) (str "Cole: ") (proc 0)
    (str "Is that so? So, what about those gang members?")
   (proc 3)
   ((cmd 197) 0 15)
   (proc 4) (str "Killer: ") (proc 1)
      (str "When they saw me, they ran away. As for the" 'br)
   (str "zombies, I'm guessing they go hiding during the day.")
   (str ".")
   (proc 3)
   ((cmd 197) 0 0)
   (proc 4) (str "Cole: ") (proc 0)
    (str "Hiding?! Where though?")
   (proc 3)
   ((cmd 197) 0 15)
   (proc 4) (str "Killer: ") (proc 1)
      (str "Not sure. If they are all hiding, we won't be able" 'br)
   (str "to kill any until night.")
   (set-reg 52 #t)
   (proc 3))
 (seg (? (= Q 9) (= 0 #t) (= 1 #t) (= 53 #f))
   ((cmd 197) 0 15)
   (proc 4) (str "Killer: ") (proc 1)
      (str "Cole, did Cooger say anything about any of this" 'br)
   (str "before he died? About zombies or what caused this?")
   (proc 3)
   ((cmd 197) 0 0)
   (proc 4) (str "Cole: ") (proc 0)
    (str "No. Nothing really...")
   (proc 19)
   (str "[This isn't good. He's suspecting Doc.]")
   (proc 3)
   (proc 4) (str "Cole: ") (proc 0)
    (str "That's right. Doc said he thought he knew you from" 'br)
   (str "somewhere.")
   (proc 3)
   ((cmd 197) 0 15)
   (proc 4) (str "Killer: ") (proc 1)
      (str "Me? Well, I've been around the city a lot, so" 'br)
   (str "maybe, but I don't remember seeing him around, even though" 'br)
   (str "that lab coat sticks out.")
   (proc 3)
   ((cmd 197) 0 0)
   (proc 4) (str "Cole: ") (proc 0)
    (str "True.")
   (set-reg 53 #t)
   (proc 3))
 (seg (? (= Q 9) (= 0 #t) (= 1 #t) (= 54 #f))
   (proc 4) (str "Cole: ") (proc 0)
    (str "What do you think of the other people here?")
   (proc 3)
   ((cmd 197) 0 15)
   (proc 4) (str "Killer: ") (proc 1)
      (str "Boss has been with us for years. He takes care of" 'br)
   (str "his own people well.")
   (proc 3)
   (proc 4) (str "Killer: ") (proc 1)
      (str "Sally's pretty sharp. As a detective, I don't say" 'br)
   (str "that lightly. She can put together a real detailed plan on" 'br)
   (str "such short notice.")
   (proc 3)
   (proc 4) (str "Killer: ") (proc 1)
      (str "Nose used to be in the military, so it's good to" 'br)
   (str "have someone like him. He's probably a bit embarrassed by" 'br)
   (str "it, but I've had to save his hide a few times.")
   (proc 3)
   (proc 4) (str "Killer: ") (proc 1)
      (str "Ray does a lot, but he has a personality that" 'br)
   (str "doesn't fit well with the others. He needs to curb that if" 'br)
   (str "he wants to survive this with us.")
   (proc 3)
   (proc 4) (str "Killer: ") (proc 1)
      (str "As for Cathy, she has potential, but she tends to" 'br)
   (str "panic a lot and can't fire a gun when it matters.")
   (proc 3)
   (proc 4) (str "Killer: ") (proc 1)
      (str "There you go. Was that helpful?")
   (set-reg 54 #t)
   (proc 3))
 (seg (? (= Q 9) (= 0 #t) (= 1 #t))
   ((cmd 197) 0 15)
   (proc 4) (str "Killer: ") (proc 1)
      (str "Well, Cole, I think you'll get along with all of" 'br)
   (str "us.")
   (proc 3))
 (seg (? (= Q 9) (= 0 #f) (= 1 #f))
   ((cmd 197) 0 15)
   (proc 4) (str "Killer: ") (proc 1)
      (str "Feel free to ask me anything if you need to.")
   (proc 3)
   ((cmd 198) 32 5 127 66 0)
   ((cmd 197) 0 0)
   (mes-jump "A:¥MES¥000031.MES"))
 (seg (? (= Q 8))
   (exec-mem 16384 0 0 1 8)
   (exec-mem 256 7)
   (str "Select Save Number.")
   (menu1
    20
    305
    34
    305
    48
    305
    62
    305
    20
    325
    34
    325
    48
    325
    62
    325
    68
    285
    (</>
     (/ (str " SAVE No.1 "))
     (/ (str " SAVE No.2 "))
     (/ (str " SAVE No.3 "))
     (/ (str " SAVE No.4 "))
     (/ (str " SAVE No.5 "))
     (/ (str " SAVE No.6 "))
     (/ (str " SAVE No.7 "))
     (/ (str " SAVE No.8 "))
     (/ (str "[CANCEL]"))))
   (text-reset 14)
   (text-frame 41 305)
   (set-reg 48 #t)
   (text-color 15)
   (str "WAIT....")
   (branch-var
    S
    (</>
     (/ (flag-save 1))
     (/ (flag-save 2))
     (/ (flag-save 3))
     (/ (flag-save 4))
     (/ (flag-save 5))
     (/ (flag-save 6))
     (/ (flag-save 7))
     (/ (flag-save 8))
     (/ (nop@))))
   (text-frame 17 284 76 340)
   (text-reset 14)
   (exec-mem 16384 0 0 1 1)
   (exec-mem 256 2)
   (nop@)
   (set-reg 0 #f)
   (set-reg 1 #t))
 (seg (? (= Q 7))
   (exec-mem 16384 0 0 1 7)
   (exec-mem 256 6)
   (str "Select Load Number.")
   (menu1
    20
    305
    34
    305
    48
    305
    62
    305
    20
    325
    34
    325
    48
    325
    62
    325
    68
    285
    (</>
     (/ (str " LOAD No.1 "))
     (/ (str " LOAD No.2 "))
     (/ (str " LOAD No.3 "))
     (/ (str " LOAD No.4 "))
     (/ (str " LOAD No.5 "))
     (/ (str " LOAD No.6 "))
     (/ (str " LOAD No.7 "))
     (/ (str " LOAD No.8 "))
     (/ (str "[CANCEL]"))))
   (text-reset 14)
   (branch-var
    S
    (</>
     (/
      (exec-mem 10496 2 32 5 127 66 32 36 127 36 0 50)
      (exec-mem 10496 0 32 5 127 66 0)
      (flag-load 1))
     (/
      (exec-mem 10496 2 32 5 127 66 32 36 127 36 0 50)
      (exec-mem 10496 0 32 5 127 66 0)
      (flag-load 2))
     (/
      (exec-mem 10496 2 32 5 127 66 32 36 127 36 0 50)
      (exec-mem 10496 0 32 5 127 66 0)
      (flag-load 3))
     (/
      (exec-mem 10496 2 32 5 127 66 32 36 127 36 0 50)
      (exec-mem 10496 0 32 5 127 66 0)
      (flag-load 4))
     (/
      (exec-mem 10496 2 32 5 127 66 32 36 127 36 0 50)
      (exec-mem 10496 0 32 5 127 66 0)
      (flag-load 5))
     (/
      (exec-mem 10496 2 32 5 127 66 32 36 127 36 0 50)
      (exec-mem 10496 0 32 5 127 66 0)
      (flag-load 6))
     (/
      (exec-mem 10496 2 32 5 127 66 32 36 127 36 0 50)
      (exec-mem 10496 0 32 5 127 66 0)
      (flag-load 7))
     (/
      (exec-mem 10496 2 32 5 127 66 32 36 127 36 0 50)
      (exec-mem 10496 0 32 5 127 66 0)
      (flag-load 8))
     (/ (nop@))))
   (exec-mem 16384 0 0 1 1)
   (exec-mem 256 2)
   (nop@)
   (set-reg 0 #f)
   (set-reg 1 #t))
 (seg*))