(mes
 (meta (engine 'ADV) (charset "pc98"))
 (seg*
  ((cmd 206) 1 1)
  ((cmd 197) 0 0)
  ((cmd 197) 1 0)
  (image-file "A:¥GRAPH¥BL054.GPC") (image-mem 1 1)
  (image-file "A:¥GRAPH¥BL055.GPC") (image-mem 1 1)
  ((cmd 198) 32 5 127 66 15)
  (text-frame 17 284 76 340)
  (text-reset 14)
  (sound '|| 0)
  (sound '|se | 10)
  (if (</>
       (//
        (? (= 68 #f))
        (proc 4) (str "Cole: ") (proc 0)
         (str "It seems people died here. Doc, do you see any" 'br)
   (str "zombies?")
        (proc 3)
        (proc 4) (str "Cooger: ") (proc 1)
           (str "No. None here, but who knows where they're hiding." 'br)
   (str "Be alert!")
        (set-reg 68 #t)
        (proc 3))
       (//
        (proc 4) (str "Cole: ") (proc 0)
         (str "No sign of zombies from what I saw.")
        (proc 3)
        (proc 4) (str "Cooger: ") (proc 1)
           (str "They're probably hiding. We have to be careful.")
        (proc 3))))
  ((cmd 182) "A:¥CLM¥BL055.CLM")
  (exec-mem 16384 0 0 1 1)
  (exec-mem 256 2)
  (nop@)
  (set-reg 0 #f)
  (loop
   ((cmd 182) P 0)
   (if (</>
        (//
         (? (= Q 1))
         (nop@)
         (exec-mem 16384 0 0 1 1)
         (exec-mem 256 2)
         (set-reg 0 #f))
        (//
         (? (= Q 6))
         (nop@)
         (exec-mem 16384 0 0 1 6)
         (exec-mem 256 4)
         (set-reg 0 #t))))
   (seg-call)))
 (seg (? (= Q 9) (= 0 #f) (= 69 #f))
   (proc 4) (str "Cole: ") (proc 0)
    (str "Maybe we should check that box there?")
   (proc 3)
   (proc 4) (str "Cole: ") (proc 0)
    (str "What the? There's nothing in it. I guess it's just" 'br)
   (str "sitting there.")
   (set-reg 69 #t)
   (proc 3))
 (seg (? (= Q 9) (= 0 #f) (= 70 #f))
   (proc 4) (str "Cole: ") (proc 0)
    (str "Nothing in the box, nor a hiding zombie there.")
   (set-reg 70 #t)
   (proc 3))
 (seg (? (= Q 9) (= 0 #f))
   (proc 4) (str "Cole: ") (proc 0)
    (str "That must be for construction.")
   (proc 3))
 (seg (? (= Q 10) (= 0 #f) (= 71 #f))
   (proc 4) (str "Cole: ") (proc 0)
    (str "What's in this here box?")
   (proc 3)
   (proc 4) (str "Cole: ") (proc 0)
    (str "God, there's so much trash here. Did they not have" 'br)
   (str "any trash cans?")
   (set-reg 71 #t)
   (proc 3))
 (seg (? (= Q 10) (= 0 #f))
   (proc 4) (str "Cole: ") (proc 0)
    (str "The box contains a lot of trash. Boxes, trash, and" 'br)
   (str "zombies. That's all this place is, huh?")
   (proc 3))
 (seg (? (= Q 11) (= 0 #f) (= 72 #f))
   (proc 4) (str "Cole: ") (proc 0)
    (str "Nothing's in this box. Whatever was here was probably" 'br)
   (str "for the construction.")
   (set-reg 72 #t)
   (proc 3))
 (seg (? (= Q 11) (= 0 #f))
   (proc 4) (str "Cole: ") (proc 0)
    (str "Just a typical cardboard box. It would be a waste of" 'br)
   (str "time to examine it any further.")
   (proc 3))
 (seg (? (= Q 12) (= 0 #f) (= 73 #f))
   (proc 4) (str "Cole: ") (proc 0)
    (str "No windows were installed yet. Glad it's not that" 'br)
   (str "cold out tonight.")
   (set-reg 73 #t)
   (proc 3))
 (seg (? (= Q 12) (= 0 #f) (= 74 #f))
   (proc 4) (str "Cole: ") (proc 0)
    (str "If I look it, I should be able to see the Needle" 'br)
   (str "River, but it's so dark out, so I can only hear it.")
   (set-reg 74 #t)
   (proc 3))
 (seg (? (= Q 12) (= 0 #f))
   (proc 4) (str "Cole: ") (proc 0)
    (str "It's so dark out. You know what time it is, Doc?")
   (proc 3)
   (proc 4) (str "Cooger: ") (proc 1)
      (str "I don't have my watch, so I don't know.")
   (proc 3))
 (seg (? (= Q 13) (= 0 #f) (= 75 #f))
   (proc 4) (str "Cole: ") (proc 0)
    (str "There's no blood on the floor. That must mean there" 'br)
   (str "haven't been zombies here, but I'm not sure.")
   (set-reg 75 #t)
   (proc 3))
 (seg (? (= Q 13) (= 0 #f) (= 76 #f))
   (proc 4) (str "Cole: ") (proc 0)
    (str "There's a lot of junk and trash on the floor because" 'br)
   (str "of the construction.")
   (set-reg 76 #t)
   (proc 3))
 (seg (? (= Q 13) (= 0 #f))
   (proc 4) (str "Cole: ") (proc 0)
    (str "There are no zombies here, for now at least.")
   (proc 3))
 (seg (? (= Q 14) (= 0 #f) (= 77 #f))
   (proc 4) (str "Cole: ") (proc 0)
    (str "Hm? There's something in that corner over there. Is" 'br)
   (str "that a cord for something?")
   (proc 3)
   (proc 4) (str "Cooger: ") (proc 1)
      (str "Maybe it's a phone cord or some TV? Maybe for an" 'br)
   (str "antenna?")
   (set-reg 77 #t)
   (proc 3))
 (seg (? (= Q 14) (= 0 #f))
   (proc 4) (str "Cole: ") (proc 0)
    (str "Hmm, I don't see anything on the wall besides this" 'br)
   (str "cord.")
   (proc 3))
 (seg (? (= Q 15) (= 0 #f))
   (proc 4) (str "Cole: ") (proc 0)
    (str "Oh? A toolbox? I wonder what's in it...")
   (proc 3)
   (proc 4) (str "Cooger: ") (proc 1)
      (str "Huh? Did you open it?")
   (proc 3)
   (proc 4) (str "Cole: ") (proc 0)
    (str "No good. Maybe I should give up.")
   (set-reg 47 #t)
   (set-reg 32 #t)
   (str " Ah! It's open.")
   (proc 3)
   ((cmd 198) 32 5 127 66 0)
   (image-file "A:¥GRAPH¥BL056.GPC") (image-mem 1 1)
   (image-file "A:¥GRAPH¥BL057.GPC") (image-mem 1 1)
   ((cmd 198) 32 5 127 66 15)
   (proc 4) (str "Cooger: ") (proc 1)
      (str "Hm? Is there anything interesting in there, Cole?")
   (proc 3)
   (proc 4) (str "Cole: ") (proc 0)
    (str "Just all kinds of tools. A hammer, screwdriver," 'br)
   (str "spanner...")
   (proc 3)
   (proc 4) (str "Cooger: ") (proc 1)
      (str "Hurry it up, Cole. There are still zombies around.")
   (proc 3)
   (proc 4) (str "Cole: ") (proc 0)
    (str "Right, right. Hmm, the rest of it is just nails upon nails...")
   (proc 3)
   (image-file "A:¥GRAPH¥BL056.GPC")
   ((cmd 198) 32 5 127 66 0)
   (image-mem 1 1)
   (image-file "A:¥GRAPH¥BL058.GPC") (image-mem 1 1)
   ((cmd 193) 0 "A:¥ANIME¥BL058.GPA")
   ((cmd 194) 0 "ｴ. ..ｵ..ｶ..ｴ. .ｵ..ｴ.. .")
   ((cmd 193) 1 "A:¥ANIME¥BL058.GPA")
   ((cmd 194) 1 "ｷ. ..ｸ..ｹ..ｸ..ｹ..ｸ..ｹ..ｸ..ｹ..ｸ..ｹ..ｸ..ｹ...")
   ((cmd 198) 32 5 127 66 15)
   (sound '|| 0)
   (sound '|| "A:¥MUSIC¥B0N_03.USO")
   (sound '|| 1)
   ((cmd 197) 0 15)
   ((cmd 197) 1 15)
   (proc 4) (str "Cooger: ") (proc 1)
      (str "Shit! Cole!!!")
   (proc 3)
   ((cmd 194) 1 "ｱ. ..ｳ..ｲ..ｱ...ｲ...ｱ..")
   ((cmd 197) 0 0)
   ((cmd 197) 1 15)
   (proc 4) (str "Cole: ") (proc 0)
    (str "Doc!!")
   (proc 3)
   ((cmd 197) 0 0)
   ((cmd 197) 1 0)
   (exec-mem 2048 0 0 1 0 1 3328)
   (exec-mem 2048 1 0 0 0 "Y")
   (exec-mem 2048 2)
   (exec-mem 2048 3)
   (exec-mem 16384 0 0 2 1)
   (exec-mem 256 9)
   ((cmd 182) P 0)
   (sound '|se | 8)
   (delay 40 0)
   (exec-mem 2048 4)
   (proc 4) (str "Cole: ") (proc 0)
    (str "Damn! It got away!")
   (proc 3)
   (sound '|| 0)
   ((cmd 198) 32 5 127 66 0)
   (image-file "A:¥GRAPH¥BL059.GPC") (image-mem 1 1)
   (image-file "A:¥GRAPH¥BL060.GPC") (image-mem 1 1)
   ((cmd 193) 0 "A:¥ANIME¥BL060.GPA")
   ((cmd 194) 0 "ｱ.. ..ｶ.....ｵ......ｷ........ｵ.....ｶ.......ｵ....ｷ...ｲ..ｳ..ｴ...ｳ..ｲ..ｱ .")
   ((cmd 198) 32 5 127 66 15)
   (sound '|| "A:¥MUSIC¥B0N_04.USO")
   (sound '|| 1)
   (proc 4) (str "Cole: ") (proc 0)
    (str "Doc! Stay with me! We'll get you an ambulance..." 'br)
   (str "wait, no. I'll bring you back upstairs!")
   (proc 3)
   ((cmd 197) 0 15)
   ((cmd 197) 1 0)
   (proc 4) (str "Cooger: ") (proc 1)
      (str "Ugh, Cole... it's already too late for me...")
   (proc 3)
   ((cmd 197) 0 0)
   ((cmd 197) 1 0)
   (proc 4) (str "Cole: ") (proc 0)
    (str "Don't say that, Doc! It's alright! I'll take you" 'br)
   (str "upstairs and we'll treat your wound! You're gonna be fine!")
   (proc 3)
   ((cmd 197) 0 15)
   ((cmd 197) 1 0)
   (proc 4) (str "Cooger: ") (proc 1)
      (str "Cole... the serum infects the blood like a virus..." 'br)
   (str "We saw that happened to the officer at the lab... I'll" 'br)
   (str "become one of them soon.")
   (proc 3)
   ((cmd 197) 0 0)
   ((cmd 197) 1 0)
   (proc 4) (str "Cole: ") (proc 0)
    (str "What? Why are you saying all this bullshit! You're" 'br)
   (str "gonna be okay, Doc, I'm sure of it!")
   (proc 3)
   ((cmd 197) 0 15)
   ((cmd 197) 1 0)
   (proc 4) (str "Cooger: ") (proc 1)
      (str "This was all my fault in the first place... I made" 'br)
   (str "that drug... it wouldn't be fitting for me to survive...")
   (proc 3)
   (proc 4) (str "Cooger: ") (proc 1)
      (str "Cole... I'm sorry for everything... tell Sheila to" 'br)
   (str "not be sad...")
   (proc 3)
   (proc 4) (str "Cooger: ") (proc 1)
      (str "Ray's girlfriend's death was also my fault...")
   (proc 3)
   ((cmd 197) 0 0)
   ((cmd 197) 1 0)
   (proc 4) (str "Cole: ") (proc 0)
    (str "Doc! You're gonna make it, I swear! We'll get rid of" 'br)
   (str "all these zombies and the three of us will be alright! Doc," 'br)
   (str "please don't die on me!!")
   (proc 3)
   ((cmd 197) 0 15)
   ((cmd 197) 1 0)
   (proc 4) (str "Cooger: ") (proc 1)
      (str "Cole, can you still hear me? I have one last" 'br)
   (str "request for you.")
   (proc 3)
   ((cmd 197) 0 0)
   ((cmd 197) 1 0)
   (proc 4) (str "Cole: ") (proc 0)
    (str "A last request? Yes, I'm listening.")
   (proc 3)
   ((cmd 197) 0 15)
   ((cmd 197) 1 0)
   (proc 4) (str "Cooger: ") (proc 1)
      (str "I don't want to become one of those zombies." 'br)
   (str "Please, kill me first.")
   (proc 3)
   ((cmd 197) 0 0)
   ((cmd 197) 1 0)
   (proc 4) (str "Cole: ") (proc 0)
    (str "What?! No, I can't do that! What are you talking" 'br)
   (str "about?!")
   (proc 3)
   ((cmd 197) 0 15)
   ((cmd 197) 1 0)
   (proc 4) (str "Cooger: ") (proc 1)
      (str "Cole, please I'm begging you. I don't want to scare" 'br)
   (str "Sheila as a zombie.")
   (proc 3)
   (proc 4) (str "Cooger: ") (proc 1)
      (str "Cole, you're the last friend I can trust fully." 'br)
   (str "Please... just do it.")
   (proc 3)
   ((cmd 197) 0 0)
   ((cmd 197) 1 0)
   (proc 4) (str "Cole: ") (proc 0)
    (str "...")
   (proc 3)
   ((cmd 197) 0 15)
   ((cmd 197) 1 0)
   (proc 4) (str "Cooger: ") (proc 1)
      (str "Cole, don't cry. Be strong. Tears don't suit you" 'br)
   (str "anyway. Oh, it's getting dark...")
   (proc 3)
   ((cmd 197) 0 0)
   ((cmd 197) 1 0)
   (proc 4) (str "Cole: ") (proc 0)
    (str "Alright, Doc. I understand. Please, even after" 'br)
   (str "everything you've done, make sure you go to Heaven.")
   (proc 3)
   ((cmd 197) 0 15)
   ((cmd 197) 1 0)
   (proc 4) (str "Cooger: ") (proc 1)
      (str "...I'll try... I'll be waiting. Make sure to live a" 'br)
   (str "happy life with Sheila...")
   (set-reg 78 #t)
   (proc 3)
   ((cmd 197) 0 0)
   ((cmd 197) 1 0)
   (sound '|| 0)
   (sound '|se | 9)
   (image-file "A:¥GRAPH¥BL061.GPC") (image-mem 1 1)
   (text-color 15)
   (str "4 years ago, when I came to this city, I first met Doc.")
   (proc 3)
   (str "Unlike most people, he was really friendly to me.")
   (proc 3)
   (str "He was more than just another scientist, he was my best" 'br)
   (str "friend.")
   (proc 3)
   (str "His experiments weren't successful most of the time, but" 'br)
   (str "his determination is what made me admire him.")
   (proc 3)
   (str "However, he made one massive mistake that cost people their" 'br)
   (str "lives.")
   (proc 3)
   (str "That mistake cost him his own life as well.")
   (proc 3)
   (str "Doc, I will never forget you. Rest easy...")
   (proc 3)
   ((cmd 198) 32 5 127 66 0)
   (mes-jump "A:¥MES¥000020.MES")
   (str "Looks good...")
   (proc 3))
 (seg (? (= Q 6))
   (menu1 30 300 52 300 (</> (/ (text "ＬＥＡＶＥ　")) (/ (text "ＳＴＡＹ　"))))
   (text-reset 14)
   (branch-var
    S
    (</>
     (/
      (proc 4) (str "Cole: ") (proc 0)
       (str "I think it's time to look somewhere else.")
      (proc 3)
      ((cmd 198) 32 5 127 66 0)
      (mes-jump "A:¥MES¥000020.MES"))
     (/
      (proc 4) (str "Cole: ") (proc 0)
       (str "Let's check this room out more")
      (proc 14)
      (proc 14)
      (proc 14)
      (str ".")
      (proc 3)))))
 (seg (? (= Q 8))
   (exec-mem 16384 0 0 1 8)
   (exec-mem 256 7)
   (str "Select Save Number.")
   (menu1
    20
    305
    34
    305
    48
    305
    62
    305
    20
    325
    34
    325
    48
    325
    62
    325
    68
    285
    (</>
     (/ (str " SAVE No.1 "))
     (/ (str " SAVE No.2 "))
     (/ (str " SAVE No.3 "))
     (/ (str " SAVE No.4 "))
     (/ (str " SAVE No.5 "))
     (/ (str " SAVE No.6 "))
     (/ (str " SAVE No.7 "))
     (/ (str " SAVE No.8 "))
     (/ (str "[CANCEL]"))))
   (text-reset 14)
   (text-frame 41 305)
   (set-reg 48 #t)
   (text-color 15)
   (str "WAIT....")
   (branch-var
    S
    (</>
     (/ (flag-save 1))
     (/ (flag-save 2))
     (/ (flag-save 3))
     (/ (flag-save 4))
     (/ (flag-save 5))
     (/ (flag-save 6))
     (/ (flag-save 7))
     (/ (flag-save 8))
     (/ (nop@))))
   (text-frame 17 284 76 340)
   (text-reset 14)
   (exec-mem 16384 0 0 1 1)
   (exec-mem 256 2)
   (nop@)
   (set-reg 0 #f))
 (seg (? (= Q 7))
   (exec-mem 16384 0 0 1 7)
   (exec-mem 256 6)
   (str "Select Load Number.")
   (menu1
    20
    305
    34
    305
    48
    305
    62
    305
    20
    325
    34
    325
    48
    325
    62
    325
    68
    285
    (</>
     (/ (str " LOAD No.1 "))
     (/ (str " LOAD No.2 "))
     (/ (str " LOAD No.3 "))
     (/ (str " LOAD No.4 "))
     (/ (str " LOAD No.5 "))
     (/ (str " LOAD No.6 "))
     (/ (str " LOAD No.7 "))
     (/ (str " LOAD No.8 "))
     (/ (str "[CANCEL]"))))
   (text-reset 14)
   (branch-var
    S
    (</>
     (/
      (exec-mem 10496 2 32 5 127 66 32 36 127 36 0 50)
      (exec-mem 10496 0 32 5 127 66 0)
      (flag-load 1))
     (/
      (exec-mem 10496 2 32 5 127 66 32 36 127 36 0 50)
      (exec-mem 10496 0 32 5 127 66 0)
      (flag-load 2))
     (/
      (exec-mem 10496 2 32 5 127 66 32 36 127 36 0 50)
      (exec-mem 10496 0 32 5 127 66 0)
      (flag-load 3))
     (/
      (exec-mem 10496 2 32 5 127 66 32 36 127 36 0 50)
      (exec-mem 10496 0 32 5 127 66 0)
      (flag-load 4))
     (/
      (exec-mem 10496 2 32 5 127 66 32 36 127 36 0 50)
      (exec-mem 10496 0 32 5 127 66 0)
      (flag-load 5))
     (/
      (exec-mem 10496 2 32 5 127 66 32 36 127 36 0 50)
      (exec-mem 10496 0 32 5 127 66 0)
      (flag-load 6))
     (/
      (exec-mem 10496 2 32 5 127 66 32 36 127 36 0 50)
      (exec-mem 10496 0 32 5 127 66 0)
      (flag-load 7))
     (/
      (exec-mem 10496 2 32 5 127 66 32 36 127 36 0 50)
      (exec-mem 10496 0 32 5 127 66 0)
      (flag-load 8))
     (/ (nop@))))
   (exec-mem 16384 0 0 1 1)
   (exec-mem 256 2)
   (nop@)
   (set-reg 0 #f))
 (seg*))