(mes
 (meta (engine 'ADV) (charset "pc98"))
 (seg*
  ((cmd 206) 1 1)
  ((cmd 197) 0 0)
  ((cmd 197) 1 0)
  (image-file "A:¥GRAPH¥BL034.GPC") (image-mem 1 1)
  (image-file "A:¥GRAPH¥BL035G.GPC") (image-mem 1 1)
  (image-file "A:¥GRAPH¥BL035K.GPC") (image-mem 1 1)
  (image-file "A:¥GRAPH¥BL035S.GPC") (image-mem 1 1)
  (image-file "A:¥GRAPH¥BL035C.GPC") (image-mem 1 1)
  (image-file "A:¥GRAPH¥BL035N.GPC") (image-mem 1 1)
  (image-file "A:¥GRAPH¥BL035R.GPC") (image-mem 1 1)
  (sound '|| 0)
  (sound '|| "A:¥MUSIC¥B0N_07.USO")
  (sound '|| 1)
  ((cmd 198) 32 5 127 66 15)
  (text-frame 17 284 76 340)
  (text-reset 14)
  (proc 4) (str "Killer: ") (proc 1)
     (str "I found these survivors outside. I think they couldbe useful.")
  (proc 19)
  (proc 4) (str "Cole: ") (proc 0)
   (str "(They're probably talking about us.)")
  (proc 3)
  (text-color 15)
  (proc 4) (str "Guy in the middle") (proc 1)
                (str "This place is locked down tight. How'd  you get in?")
  (proc 3)
  (proc 4) (str "Cole: ") (proc 0)
   (str "We invited ourselves in, actually.")
  (proc 3)
  (text-color 15)
  (proc 4) (str "Guy in the middle: ") (proc 1)
                (str "You needed a PIN to get in here. How'd  you find that?")
  (proc 3)
  (proc 4) (str "Cole: ") (proc 0)
   (str "We found a note at the 16th Precinct, but everyone   there was killed by zombies.")
  (proc 3)
  (text-color 15)
  (proc 4) (str "Guy in the middle: ") (proc 1)
                (str "Ah, the chief's office. That station wasoverwhelmed by zombies.")
  (proc 3)
  (text-color 15)
  (proc 4) (str "Guy in the middle: ") (proc 1)
                (str "Did you manage to get into the armory?")
  (proc 3)
  (proc 4) (str "Cole: ") (proc 0)
   (str "Yeah, I was attacked, but I didn't get bit.")
  (proc 3)
  (text-color 15)
  (proc 4) (str "Guy in the middle: ") (proc 1)
                (str "You got here without weapons? Nice. We  took all the weapons here, so that's why it was empty.")
  (proc 3)
  (proc 4) (str "Cole: ") (proc 0)
   (str "Oh really? So that's why it was empty. So you're the chief, right?")
  (proc 3)
  (text-color 15)
  (proc 4) (str "Guy in the middle: ") (proc 1)
                (str "Oh, I forgot to introduce myself. My" 'br)
   (str "name's Richard Gris, but you can call me Ghoul.")
  (proc 3)
  (proc 4) (str "Ghoul: ") (proc 1)
    (str "I don't know how I got the nickname, but at one" 'br)
   (str "point, everyone began to call me Ghoul. I think it's a good nickname.")
  (proc 3)
  (proc 4) (str "Cole: ") (proc 0)
   (str "Cole, this is Doctor Cooger and Sheila. I figured" 'br)
   (str "more people would be here, not just six.")
  (proc 3)
  (proc 4) (str "Ghoul: ") (proc 1)
    (str "Yes, there are only 6 of us, but we've been fighting" 'br)
   (str "hard against those damn zombie forces.")
  (proc 3)
  (proc 4) (str "Ghoul: ") (proc 1)
    (str "It's a tough, thankless job, but we must do it. How" 'br)
   (str "about you? Could you three be of any help?")
  (proc 3)
  (text-color 15)
  (proc 4) (str "Guy with feet up: ") (proc 1)
              (str "I don't think this kid'll be useful. I" 'br)
   (str "don't even approve of you being a leader!")
  (proc 3)
  (text-color 15)
  (proc 4) (str "Woman with Glasses: ") (proc 2)
                 (str "Knock it off, Ray. Ghoul is the chief" 'br)
   (str "so his first priority is to protect the people.")
  (proc 3)
  (proc 4) (str "Ray: ") (proc 1)
  (str "Would you REALLY trust these people with your life?")
  (proc 3)
  (proc 4) (str "Cole: ") (proc 0)
   (str "(Ray and Sally, huh. It seems like they've got some" 'br)
   (str "problems to work out.)")
  (proc 3)
  (proc 4) (str "Sally: ") (proc 2)
    (str "This is a desperate predicament, the more the" 'br)
   (str "merrier.")
  (proc 3)
  (proc 4) (str "Ray: ") (proc 1)
  (str "What if that radio is busted, or if we're out of" 'br)
   (str "range? We should just move on.")
  (proc 3)
  (text-color 15)
  (proc 4) (str "Bald guy: ") (proc 1)
       (str "How are we gonna get outta here? It's all undead" 'br)
   (str "out there. And the train seems like a bad idea unless you're" 'br)
   (str "cool with a zombie in the driver's seat.")
  (proc 3)
  (proc 4) (str "Ray: ") (proc 1)
  (str "C-...")
  (proc 3)
  (proc 4) (str "Sheila: ") (proc 2)
     (str "Cole, what do we do?")
  (if (</> (// (? (= 600 #f)) (nop@) (sound '|se | 29) (text-delay 0))))
  (exec-mem 256 0)
  (menu1 30 300 52 300 (</> (/ (text "　ＪＯＩＮ　")) (/ (text "　ＱＵＩＴ　"))))
  (text-reset 14)
  (branch-var
   S
   (</>
    (/ (proc 4) (str "Cole: ") (proc 0) (str "We're in") (str "."))
    (/
     (proc 4) (str "Cole: ") (proc 0)
      (str "Maybe Ray's right, we probably aren't cut out for it.")
     (text 'br)
     (set-reg 800 #t)
     (str "Ray: This is dumb. This kid doesn't have the guts.")
     (proc 3)
     (proc 4) (str "Cole: ") (proc 0)
      (str "Fine, I'll join")
     (str "."))))
  (proc 3)
  (proc 4) (str "Ghoul: ") (proc 1)
    (str "Thanks. You people should get some rest. Sally, give" 'br)
   (str "them their cards and guns.")
  (proc 3)
  (image-file "A:¥GRAPH¥BL041.GPC") (image-mem 1 1)
  (proc 4) (str "Sally: ") (proc 2)
    (str "Yep, here you go.")
  (proc 3)
  (proc 4) (str "Ghoul: ") (proc 1)
    (str "Your room is 220. Here's a card for it, a gun, and a" 'br)
   (str "grenade. These are for the undead, so don't point this at" 'br)
   (str "anything you don't want to kill.")
  (proc 3)
  (proc 4) (str "Ghoul: ") (proc 1)
    (str "We have some operations in the works. If you come" 'br)
   (str "back in 30 minutes, I can tell you about them.")
  (proc 3)
  (proc 4) (str "Ghoul: ") (proc 1)
    (str "We're a team. We may have different opinions and" 'br)
   (str "such, but we're all humans trying to survive.")
  (proc 3)
  (proc 4) (str "Sheila: ") (proc 2)
     (str "Cole, let's go rest a little...")
  (proc 19)
  (proc 4) (str "Cole: ") (proc 0)
   (str "Yeah.")
  (proc 3)
  ((cmd 198) 32 5 127 66 0)
  (sound '|| 0)
  (mes-jump "A:¥MES¥000017.MES"))
 (seg*))