(mes
 (meta (engine 'ADV) (charset "pc98"))
 (seg*
  ((cmd 206) 1 2)
  (text-frame 17 284 76 340)
  (text-reset 14)
  (exec-mem 16384 0 0 1 1)
  (exec-mem 256 2)
  (loop
   (menu1
    18
    300
    38
    300
    (</>
     (/ (set-reg 10 #f) (text "　") (str "Book") (text "　"))
     (/ (set-reg 10 #t) (text "　") (str "Diary") (text "　"))
     (/ (set-reg 12 #f) (text "　") (str "Envelope") (text "　"))
     (/ (set-reg 12 #t) (text "　") (str "Photo") (text "　"))
     (/)))
   (text-reset 14)
   (seg-call)))
 (seg (? (= T 0) (= 11 #t) (= 14 #t) (= 15 #f))
   (proc 4) (str "Cole: ") (proc 0)
    (str "In the diary, Jan 24 and Feb 6 jump out. Feb 6 was" 'br)
   (str "also the same date as that photo. What was Doc doing on thatday?")
   (set-reg 15 #t)
   (proc 3))
 (seg (? (= T 0) (= 11 #t) (= 14 #t) (= 16 #f))
   (proc 4) (str "Cole: ") (proc 0)
    (str "Let's start with Jan 24.")
   (proc 3)
   (str "Jan24: The experiments on dead guinea pigs suggest that" 'br)
   (str "only cells near the injection site are revived. This could" 'br)
   (str "be due to poor drug penetration.")
   (proc 3)
   (str "To revive the full body, I had to inject into the brain," 'br)
   (str "heart, and limbs. However, the revived guinea pigs were" 'br)
   (str "violent. The cause here seems to be the brain.")
   (proc 3)
   (proc 4) (str "Cole: ") (proc 0)
    (str "I wonder if he was worried about the rabidity of the drug even then?")
   (set-reg 16 #t)
   (proc 3))
 (seg (? (= T 0) (= 11 #t) (= 14 #t) (= 17 #f))
   (proc 4) (str "Cole: ") (proc 0)
    (str "Next is from Feb 6...")
   (proc 3)
   (str "Feb6: I spoke at a conference about the prototype drug. I" 'br)
   (str "was mocked and lost my temper. I regret that, but they didn't" 'br)
   (str "believe a word I said.")
   (proc 3)
   (proc 4) (str "Cole: ") (proc 0)
    (str "If anyone actually believed what Doc said at this    time...")
   (proc 3)
   (proc 4) (str "Cole: ") (proc 0)
    (str "Anyways, next entry...")
   (set-reg 17 #t)
   (proc 3))
 (seg (? (= T 0) (= 11 #t) (= 14 #t) (= 18 #f))
   (proc 4) (str "Cole: ") (proc 0)
    (str "This one is from Feb 25...")
   (proc 3)
   (str "Feb25: The violent effects of the revival are still" 'br)
   (str "unknown. My hypothesis is that as time passes after brain" 'br)
   (str "death, violent pulses increase but I have no clue why.")
   (proc 3)
   (str "If I can solve this issue, the Nobel Prize is mine! I can't" 'br)
   (str "wait to see the look on the other scientists' faces...")
   (proc 3)
   (proc 4) (str "Cole: ") (proc 0)
    (str "That cop Jack was revived immediately and went" 'br)
   (str "berserk. It must've been the same with the small animals.")
   (set-reg 18 #t)
   (proc 3))
 (seg (? (= T 0) (= 11 #t) (= 14 #t) (= 19 #f))
   (proc 4) (str "Cole: ") (proc 0)
    (str "Feb 27...")
   (proc 3)
   (str "Feb27: Someone has stolen the resurrection drug. The lab" 'br)
   (str "was destroyed, but there was a pile of materials in one" 'br)
   (str "place.")
   (proc 3)
   (str "Perhaps the culprit snapped photos of documents and the" 'br)
   (str "equipment. I contacted the police but it doesn't seem to be" 'br)
   (str "going anywhere.")
   (proc 3)
   (str "The culprit must be someone who knows my work. Maybe the" 'br)
   (str "person was at the conference. I will look around again" 'br)
   (str "tomorrow.")
   (proc 3)
   (proc 4) (str "Cole: ") (proc 0)
    (str "Huh? Someone broke into Doc's house and took his" 'br)
   (str "work?")
   (proc 3)
   (proc 4) (str "Cole: ") (proc 0)
    (str "Cain said that someone unleashed the drug a month" 'br)
   (str "ago...")
   (set-reg 19 #t)
   (proc 3))
 (seg (? (= T 0) (= 11 #t) (= 14 #t) (= 20 #f))
   (str "Feb28: I still don't have any leads, but I'm working on" 'br)
   (str "remaking the drug. If I don't complete it soon, my thunder" 'br)
   (str "will be stolen. Maybe I should surprise Cole with this.")
   (proc 3)
   (proc 4) (str "Cole: ") (proc 0)
    (str "Doc would've looked forward to seeing my shocked face" 'br)
   (str "when he dropped this on me.")
   (proc 3)
   (proc 4) (str "Cole: ") (proc 0)
    (str "No clue to the culprit... I mean, Doc's address is" 'br)
   (str "public so it could've been anyone.")
   (set-reg 20 #t)
   (proc 3))
 (seg (? (= T 0) (= 11 #t) (= 14 #t) (= 21 #f))
   (proc 4) (str "Cole: ") (proc 0)
    (str "March 25... this is a week ago.")
   (proc 3)
   (str "Mar25: The drug is complete again. The rabidity problem is" 'br)
   (str "still unsolved, but releasing it now is best to stay ahead" 'br)
   (str "of that thief.")
   (proc 3)
   (proc 4) (str "Cole: ") (proc 0)
    (str "That's all?")
   (proc 3)
   (proc 4) (str "Cole: ") (proc 0)
    (str "No doubt someone stole Doc's work. Last month's" 'br)
   (str "zombie outbreak that Cain mentioned... That's proof of the" 'br)
   (str "thief's work.")
   (set-reg 21 #t)
   (proc 3))
 (seg (? (= T 0) (= 11 #t) (= 14 #t))
   (proc 4) (str "Cole: ") (proc 0)
    (str "Should I re-read this?")
   (proc 3)
   (str "Jan24: The experiments on dead guinea pigs suggest that" 'br)
   (str "only cells near the injection site are revived. This could" 'br)
   (str "be due to poor drug penetration.")
   (proc 3)
   (str "To revive the full body, I had to inject into the brain," 'br)
   (str "heart, and limbs. However, the revived guinea pigs were" 'br)
   (str "violent. The cause here seems to be the brain.")
   (proc 3)
   (str "Feb6: I spoke at a conference about the prototype drug. I" 'br)
   (str "was mocked and lost my temper. I regret that, but they didn't" 'br)
   (str "believe a word I said.")
   (proc 3)
   (str "Feb25: The violent effects of the revival are still" 'br)
   (str "unknown. My hypothesis is that as time passes after brain" 'br)
   (str "death, violent pulses increase but I have no clue why.")
   (proc 3)
   (str "If I can solve this issue, the Nobel Prize is mine! I can't" 'br)
   (str "wait to see the look on the other scientists' faces...")
   (proc 3)
   (str "Feb27: Someone has stolen the resurrection drug. The lab" 'br)
   (str "was destroyed, but there was a pile of materials in one" 'br)
   (str "place.")
   (proc 3)
   (str "Perhaps the culprit snapped photos of documents and the" 'br)
   (str "equipment. I contacted the police but it doesn't seem to be" 'br)
   (str "going anywhere.")
   (proc 3)
   (str "The culprit must be someone who knows my work. Maybe the" 'br)
   (str "person was at the conference. I will look around again" 'br)
   (str "tomorrow.")
   (proc 3)
   (str "Feb28: I still don't have any leads, but I'm working on" 'br)
   (str "remaking the drug. If I don't complete it soon, my thunder" 'br)
   (str "will be stolen. Maybe I should surprise Cole with this.")
   (proc 3)
   (str "Mar25: The drug is complete again. The rabidity problem is" 'br)
   (str "still unsolved, but releasing it now is best to stay ahead" 'br)
   (str "of that thief.")
   (proc 3)
   (proc 4) (str "Cole: ") (proc 0)
    (str "I wonder who stole Doc's work?")
   (proc 3))
 (seg (? (= T 0) (= 10 #f))
   (proc 4) (str "Cole: ") (proc 0)
    (str "This book... is a little strange.")
   (proc 3)
   (proc 4) (str "Cole: ") (proc 0)
    (str "This looks like some kind of diary, not a textbook. I" 'br)
   (str "didn't know Doc kept one.")
   (set-reg 10 #t)
   (proc 3))
 (seg (? (= T 0))
   (proc 4) (str "Cole: ") (proc 0)
    (str "I get keeping a diary private... but keeping it in a" 'br)
   (str "safe?")
   (set-reg 11 #t)
   (proc 3))
 (seg (? (= T 1) (= 11 #t) (= 14 #t) (= 15 #f))
   (proc 4) (str "Cole: ") (proc 0)
    (str "In the diary, Jan 24 and Feb 6 jump out. Feb 6 was" 'br)
   (str "also the same date as that photo. What was Doc doing on thatday?")
   (set-reg 15 #t)
   (proc 3))
 (seg (? (= T 1) (= 11 #t) (= 14 #t) (= 16 #f))
   (proc 4) (str "Cole: ") (proc 0)
    (str "Let's start with Jan 24.")
   (proc 3)
   (str "Jan24: The experiments on dead guinea pigs suggest that" 'br)
   (str "only cells near the injection site are revived. This could" 'br)
   (str "be due to poor drug penetration.")
   (proc 3)
   (str "To revive the full body, I had to inject into the brain," 'br)
   (str "heart, and limbs. However, the revived guinea pigs were" 'br)
   (str "violent. The cause here seems to be the brain.")
   (proc 3)
   (proc 4) (str "Cole: ") (proc 0)
    (str "I wonder if he was worried about the rabidity of the" 'br)
   (str "drug even then?")
   (set-reg 16 #t)
   (proc 3))
 (seg (? (= T 1) (= 11 #t) (= 14 #t) (= 17 #f))
   (proc 4) (str "Cole: ") (proc 0)
    (str "Next is from Feb 6...")
   (proc 3)
   (str "Feb6: I spoke at a conference about the prototype drug. I" 'br)
   (str "was mocked and lost my temper. I regret that, but they didn't" 'br)
   (str "believe a word I said.")
   (proc 3)
   (proc 4) (str "Cole: ") (proc 0)
    (str "If anyone actually believed what Doc said at this" 'br)
   (str "time...")
   (proc 3)
   (proc 4) (str "Cole: ") (proc 0)
    (str "Anyways, next entry...")
   (set-reg 17 #t)
   (proc 3))
 (seg (? (= T 1) (= 11 #t) (= 14 #t) (= 18 #f))
   (proc 4) (str "Cole: ") (proc 0)
    (str "This one is from Feb 25...")
   (proc 3)
   (str "Feb25: The violent effects of the revival are still" 'br)
   (str "unknown. My hypothesis is that as time passes after brain" 'br)
   (str "death, violent pulses increase but I have no clue why.")
   (proc 3)
   (str "If I can solve this issue, the Nobel Prize is mine! I can't wait to see the look on the other scientists' faces...")
   (proc 3)
   (proc 4) (str "Cole: ") (proc 0)
    (str "That cop Jack was revived immediately and went" 'br)
   (str "berserk. It must've been the same with the small animals.")
   (set-reg 18 #t)
   (proc 3))
 (seg (? (= T 1) (= 11 #t) (= 14 #t) (= 19 #f))
   (proc 4) (str "Cole: ") (proc 0)
    (str "Feb 27...")
   (proc 3)
   (str "Feb27: Someone has stolen the resurrection drug. The lab" 'br)
   (str "was destroyed, but there was a pile of materials in one" 'br)
   (str "place.")
   (proc 3)
   (str "Perhaps the culprit snapped photos of documents and the" 'br)
   (str "equipment. I contacted the police but it doesn't seem to be" 'br)
   (str "going anywhere.")
   (proc 3)
   (str "The culprit must be someone who knows my work. Maybe the" 'br)
   (str "person was at the conference. I will look around again" 'br)
   (str "tomorrow.")
   (proc 3)
   (proc 4) (str "Cole: ") (proc 0)
    (str "Huh? Someone broke into Doc's house and took his" 'br)
   (str "work?")
   (proc 3)
   (proc 4) (str "Cole: ") (proc 0)
    (str "Cain said that someone unleashed the drug a month" 'br)
   (str "ago...")
   (set-reg 19 #t)
   (proc 3))
 (seg (? (= T 1) (= 11 #t) (= 14 #t) (= 20 #f))
   (str "Feb28: I still don't have any leads, but I'm working on" 'br)
   (str "remaking the drug. If I don't complete it soon, my thunder" 'br)
   (str "will be stolen. Maybe I should surprise Cole with this.")
   (proc 3)
   (proc 4) (str "Cole: ") (proc 0)
    (str "Doc would've looked forward to seeing my shocked face" 'br)
   (str "when he dropped this on me.")
   (proc 3)
   (proc 4) (str "Cole: ") (proc 0)
    (str "No clue to the culprit... I mean, Doc's address is" 'br)
   (str "public so it could've been anyone.")
   (set-reg 20 #t)
   (proc 3))
 (seg (? (= T 1) (= 11 #t) (= 14 #t) (= 21 #f))
   (proc 4) (str "Cole: ") (proc 0)
    (str "March 25... this is a week ago.")
   (proc 3)
   (str "Mar25: The drug is complete again. The rabidity problem is" 'br)
   (str "still unsolved, but releasing it now is best to stay ahead" 'br)
   (str "of that thief.")
   (proc 3)
   (proc 4) (str "Cole: ") (proc 0)
    (str "That's all?")
   (proc 3)
   (proc 4) (str "Cole: ") (proc 0)
    (str "No doubt someone stole Doc's work. Last month's" 'br)
   (str "zombie outbreak that Cain mentioned... That's proof of the" 'br)
   (str "thief's work.")
   (set-reg 21 #t)
   (proc 3))
 (seg (? (= T 1) (= 11 #t) (= 14 #t))
   (proc 4) (str "Cole: ") (proc 0)
    (str "Should I re-read this?")
   (proc 3)
   (str "Jan24: The experiments on dead guinea pigs suggest that" 'br)
   (str "only cells near the injection site are revived. This could" 'br)
   (str "be due to poor drug penetration.")
   (proc 3)
   (str "To revive the full body, I had to inject into the brain," 'br)
   (str "heart, and limbs. However, the revived guinea pigs were" 'br)
   (str "violent. The cause here seems to be the brain.")
   (proc 3)
   (str "Feb6: I spoke at a conference about the prototype drug. I" 'br)
   (str "was mocked and lost my temper. I regret that, but they didn't" 'br)
   (str "believe a word I said.")
   (proc 3)
   (str "Feb25: The violent effects of the revival are still" 'br)
   (str "unknown. My hypothesis is that as time passes after brain" 'br)
   (str "death, violent pulses increase but I have no clue why.")
   (proc 3)
   (str "If I can solve this issue, the Nobel Prize is mine! I can't" 'br)
   (str "wait to see the look on the other scientists' faces...")
   (proc 3)
   (str "Feb27: Someone has stolen the resurrection drug. The lab" 'br)
   (str "was destroyed, but there was a pile of materials in one" 'br)
   (str "place.")
   (proc 3)
   (str "Perhaps the culprit snapped photos of documents and the" 'br)
   (str "equipment. I contacted the police but it doesn't seem to be" 'br)
   (str "going anywhere.")
   (proc 3)
   (str "The culprit must be someone who knows my work. Maybe the" 'br)
   (str "person was at the conference. I will look around again" 'br)
   (str "tomorrow.")
   (proc 3)
   (str "Feb28: I still don't have any leads, but I'm working on" 'br)
   (str "remaking the drug. If I don't complete it soon, my thunder" 'br)
   (str "will be stolen. Maybe I should surprise Cole with this.")
   (proc 3)
   (str "Mar25: The drug is complete again. The rabidity problem is" 'br)
   (str "still unsolved, but releasing it now is best to stay ahead" 'br)
   (str "of that thief.")
   (proc 3)
   (proc 4) (str "Cole: ") (proc 0)
    (str "I wonder who stole Doc's work?")
   (proc 3))
 (seg (? (= T 1) (= 10 #f))
   (proc 4) (str "Cole: ") (proc 0)
    (str "This book... is a little strange.")
   (proc 3)
   (proc 4) (str "Cole: ") (proc 0)
    (str "This looks like some kind of diary, not a textbook. I" 'br)
   (str "didn't know Doc kept one.")
   (set-reg 10 #t)
   (proc 3))
 (seg (? (= T 1))
   (proc 4) (str "Cole: ") (proc 0)
    (str "I get keeping a diary private... but keeping it in a safe?")
   (set-reg 11 #t)
   (proc 3))
 (seg (? (= T 2) (= 21 #t) (= 22 #f))
   (proc 4) (str "Cole: ") (proc 0)
    (str "If the person who stole Doc's work was in that photo," 'br)
   (str "they were either killed by zombies or laughing their heads" 'br)
   (str "off now.")
   (set-reg 22 #t)
   (proc 3))
 (seg (? (= T 2) (= 21 #t) (= 23 #f))
   (proc 4) (str "Cole: ") (proc 0)
    (str "Doc looks so happy in this photo. Was he announcing" 'br)
   (str "his work on the drug?")
   (set-reg 23 #t)
   (proc 3))
 (seg (? (= T 2) (= 21 #t))
   (proc 4) (str "Cole: ") (proc 0)
    (str "There are other scientists in this photo...")
   (proc 3)
   (proc 4) (str "Cole: ") (proc 0)
    (str "That man in front of Doc... is that Killer?")
   (proc 3)
   (image-file "A:¥GRAPH¥BL081.GPC") (image-mem 1 1)
   (proc 4) (str "Sheila: ") (proc 2)
      (str "Now that you mention it, yeah he does look like" 'br)
   (str "Killer. What's a policeman doing in a photo of" 'br)
   (str "scientists?")
   (proc 3)
   (proc 4) (str "Cole: ") (proc 0)
    (str "Hang on...")
   (proc 3)
   (proc 4) (str "Cole: ") (proc 0)
    (str "Didn't Doc say he might've seen Killer before?")
   (proc 3)
   (proc 4) (str "Cole: ") (proc 0)
    (str "Could Killer have been listening to Doc at the" 'br)
   (str "conference?")
   (proc 3)
   (proc 4) (str "Sheila: ") (proc 2)
      (str "What kind of man is Killer?")
   (proc 3)
   (proc 4) (str "Cole: ") (proc 0)
    (str "I don't want to believe it either, Sheila.")
   (proc 3)
   (proc 4) (str "Sheila: ") (proc 2)
      (str "Maybe Killer was investigating the zombies in that" 'br)
   (str "other city, and it led him to Doc?")
   (proc 3)
   (proc 4) (str "Cole: ") (proc 0)
    (str "Probably not. If that was the case, wouldn't a" 'br)
   (str "policeman help evacuate the city before the outbreak? But...")
   (proc 3)
   (proc 4) (str "Sheila: ") (proc 2)
      (str "But what?")
   (proc 3)
   (proc 4) (str "Cole: ") (proc 0)
    (str "If Killer stole Doc's work, why didn't he kill him" 'br)
   (str "when we got to the hotel?")
   (proc 3)
   (proc 4) (str "Sheila: ") (proc 2)
      (str "Well, he couldn't do that with us there.")
   (proc 3)
   (proc 4) (str "Cole: ") (proc 0)
    (str "He could've killed all three of us, right?")
   (proc 3)
   (proc 4) (str "Sheila: ") (proc 2)
      (str "...Ah!")
   (proc 3)
   (proc 4) (str "Sheila: ") (proc 2)
      (str "Look at the time! We have to leave now to see Cain!")
   (proc 3)
   (proc 4) (str "Cole: ") (proc 0)
    (str "Shit, I lost track of time. Let's go, Sheila!")
   (proc 3)
   (exec-mem 10496 2 32 5 127 66 32 36 127 36 0 50)
   (exec-mem 10496 0 32 5 127 66 0)
   (nop@)
   (set-reg 24 #t)
   (mes-jump "A:¥MES¥000052.MES"))
 (seg (? (= T 2) (= 12 #f))
   (proc 4) (str "Cole: ") (proc 0)
    (str "What's in this envelope?")
   (proc 3)
   (proc 4) (str "Cole: ") (proc 0)
    (str "It contains a photo. The snapshot shows Doc at a" 'br)
   (str "conference with other scientists.")
   (set-reg 12 #t)
   (proc 3))
 (seg (? (= T 2) (= 13 #f))
   (proc 4) (str "Cole: ") (proc 0)
    (str "There's nothing in the envelope but the photo.")
   (set-reg 13 #t)
   (proc 3))
 (seg (? (= T 2))
   (proc 4) (str "Cole: ") (proc 0)
    (str "Looking at the photo, it's from Feb 6 of this year." 'br)
   (str "So almost two months ago.")
   (set-reg 14 #t)
   (proc 3))
 (seg (? (= T 3) (= 21 #t) (= 22 #f))
   (proc 4) (str "Cole: ") (proc 0)
    (str "If the person who stole Doc's work was in that photo," 'br)
   (str "they were either killed by zombies or laughing their heads" 'br)
   (str "off now.")
   (set-reg 22 #t)
   (proc 3))
 (seg (? (= T 3) (= 21 #t) (= 23 #f))
   (proc 4) (str "Cole: ") (proc 0)
    (str "Doc looks so happy in this photo. Was he announcing" 'br)
   (str "his work on the drug?")
   (set-reg 23 #t)
   (proc 3))
 (seg (? (= T 3) (= 21 #t))
   (proc 4) (str "Cole: ") (proc 0)
    (str "There are other scientists in this photo...")
   (proc 3)
   (proc 4) (str "Cole: ") (proc 0)
    (str "That man in front of Doc... is that Killer?")
   (proc 3)
   (image-file "A:¥GRAPH¥BL081.GPC") (image-mem 1 1)
   (proc 4) (str "Sheila: ") (proc 2)
      (str "Now that you mention it, yeah he does look like" 'br)
   (str "Killer. What's a policeman doing in a photo of" 'br)
   (str "scientists?")
   (proc 3)
   (proc 4) (str "Cole: ") (proc 0)
    (str "Hang on...")
   (proc 3)
   (proc 4) (str "Cole: ") (proc 0)
    (str "Didn't Doc say he might've seen Killer before?")
   (proc 3)
   (proc 4) (str "Cole: ") (proc 0)
    (str "Could Killer have been listening to Doc at the" 'br)
   (str "conference?")
   (proc 3)
   (proc 4) (str "Sheila: ") (proc 2)
      (str "What kind of man is Killer?")
   (proc 3)
   (proc 4) (str "Cole: ") (proc 0)
    (str "I don't want to believe it either, Sheila.")
   (proc 3)
   (proc 4) (str "Sheila: ") (proc 2)
      (str "Maybe Killer was investigating the zombies in that" 'br)
   (str "other city, and it led him to Doc?")
   (proc 3)
   (proc 4) (str "Cole: ") (proc 0)
    (str "Probably not. If that was the case, wouldn't a" 'br)
   (str "policeman help evacuate the city before the outbreak? But...")
   (proc 3)
   (proc 4) (str "Sheila: ") (proc 2)
      (str "But what?")
   (proc 3)
   (proc 4) (str "Cole: ") (proc 0)
    (str "If Killer stole Doc's work, why didn't he kill him" 'br)
   (str "when we got to the hotel?")
   (proc 3)
   (proc 4) (str "Sheila: ") (proc 2)
      (str "Well, he couldn't do that with us there.")
   (proc 3)
   (proc 4) (str "Cole: ") (proc 0)
    (str "He could've killed all three of us, right?")
   (proc 3)
   (proc 4) (str "Sheila: ") (proc 2)
      (str "...Ah!")
   (proc 3)
   (proc 4) (str "Sheila: ") (proc 2)
      (str "Look at the time! We have to leave now to see Cain!")
   (proc 3)
   (proc 4) (str "Cole: ") (proc 0)
    (str "Shit, I lost track of time. Let's go, Sheila!")
   (proc 3)
   (exec-mem 10496 2 32 5 127 66 32 36 127 36 0 50)
   (exec-mem 10496 0 32 5 127 66 0)
   (nop@)
   (set-reg 24 #t)
   (mes-jump "A:¥MES¥000052.MES"))
 (seg (? (= T 3) (= 12 #f))
   (proc 4) (str "Cole: ") (proc 0)
    (str "What's in this envelope?")
   (proc 3)
   (proc 4) (str "Cole: ") (proc 0)
    (str "It contains a photo. The snapshot shows Doc at a" 'br)
   (str "conference with other scientists.")
   (set-reg 12 #t)
   (proc 3))
 (seg (? (= T 3) (= 13 #f))
   (proc 4) (str "Cole: ") (proc 0)
    (str "There's nothing in the envelope but the photo.")
   (set-reg 13 #t)
   (proc 3))
 (seg (? (= T 3))
   (proc 4) (str "Cole: ") (proc 0)
    (str "Looking at the photo, it's from Feb 6 of this year." 'br)
   (str "So almost two months ago.")
   (set-reg 14 #t)
   (proc 3))
 (seg*))