(mes
 (meta (engine 'ADV) (charset "pc98"))
 (seg*
  ((cmd 206) 1 2)
  ((cmd 197) 0 0)
  ((cmd 197) 1 0)
  (image-file "A:¥GRAPH¥BL100.GPC") (image-mem 1 1)
  (sound '|| 0)
  ((cmd 193) 0 "A:¥ANIME¥BL100.GPA")
  ((cmd 194) 0 "ｱ. .......... ｴ.......ｵ..............ｴ......ｱ .")
  ((cmd 193) 1 "A:¥ANIME¥BL100.GPA")
  ((cmd 194) 1 "ｶ. ...ｷ...ｸ....ｶ.. ..ｷ..ｸ..ｶ.. ..ｷ...ｶ .")
  (exec-mem 10496 1 32 36 127 36 32 5 127 66 8 50)
  (text-frame 17 284 76 340)
  (text-reset 14)
  (proc 4) (str "Cole: ") (proc 0)
   (str "Sheila...")
  (proc 3)
  (proc 4) (str "Cole: ") (proc 0)
   (str "Are you okay? ...Sheila?")
  (proc 3)
  (text-frame 17 284 76 340)
  (text-reset 14)
  ((cmd 182) "A:¥CLM¥BL100.CLM")
  (exec-mem 16384 0 0 1 1)
  (exec-mem 256 2)
  (nop@)
  (set-reg 0 #f)
  (loop
   ((cmd 182) P 0)
   (if (</>
        (//
         (? (= Q 1))
         (nop@)
         (exec-mem 16384 0 0 1 1)
         (exec-mem 256 2)
         (set-reg 0 #f))
        (//
         (? (= Q 2))
         (nop@)
         (exec-mem 16384 0 0 1 2)
         (exec-mem 256 1)
         (set-reg 0 #t))))
   (seg-call)
   ((cmd 197) 0 0)
   ((cmd 197) 1 0)))
 (seg (? (= Q 9) (= 0 #f) (= 10 #f))
   (proc 4) (str "Cole: ") (proc 0)
    (str "Still breathing. She's unconscious.")
   (set-reg 10 #t)
   (proc 3))
 (seg (? (= Q 9) (= 0 #f) (= 11 #f))
   (proc 4) (str "Cole: ") (proc 0)
    (str "If only I got here faster, this must not have" 'br)
   (str "happened.")
   (set-reg 11 #t)
   (proc 3))
 (seg (? (= Q 9) (= 0 #f))
   (proc 4) (str "Cole: ") (proc 0)
    (str "I'm sorry, Sheila. I was so worried about you.")
   (proc 3))
 (seg (? (= Q 10) (= 0 #f) (= 12 #f))
   (proc 4) (str "Cole: ") (proc 0)
    (str "Put something on, you'll catch a cold...")
   (set-reg 12 #t)
   (proc 3))
 (seg (? (= Q 10) (= 0 #f))
   (proc 4) (str "Cole: ") (proc 0)
    (str "I'm so sorry this happened...")
   (proc 3))
 (seg (? (= Q 9) (= 0 #t) (= 23 #t))
   ((cmd 196) 0 0)
   (delay 6)
   ((cmd 196) 0 1)
   (delay 6)
   ((cmd 197) 0 0)
   (proc 4) (str "Sheila: ") (proc 2)
      (str "Ugh... Cole?")
   (proc 3)
   (proc 4) (str "Cole: ") (proc 0)
    (str "Sheila, you alright?")
   (proc 3)
   (proc 4) (str "Sheila: ") (proc 2)
      (str "Yeah I'm fine. Where are we?")
   (proc 19)
   (proc 4) (str "Cole: ") (proc 0)
    (str "The hospital.")
   (proc 3)
   (proc 4) (str "Sheila: ") (proc 2)
      (str "Where are my clothes?")
   (proc 19)
   (proc 4) (str "Cole: ") (proc 0)
    (str "Here, put this on.")
   (proc 3)
   (str "I decided to go to the Bayside Research Lab, where Ghoul is," 'br)
   (str "to avenge everyone.")
   (proc 3)
   (str "I told Sheila everything, and she listened intently.")
   (proc 3)
   (str "I told her that she should stay here...")
   (proc 3)
   (str "Sheila thought it was the best course of action to go..." 'br)
   (str "together.")
   (set-reg 504 #t)
   (proc 3)
   (exec-mem 10496 2 32 5 127 66 32 36 127 36 0 50)
   (exec-mem 10496 0 32 5 127 66 0)
   ((cmd 204) 99)
   (mes-jump "A:¥MES¥TOWNS.MES"))
 (seg (? (= Q 9) (= 0 #t) (= 14 #t) (= 15 #t) (= 32 #f))
   ((cmd 197) 0 0)
   ((cmd 197) 1 15)
   (proc 4) (str "Killer: ") (proc 1)
      (str "Cole, I swear... I didn't lay a finger on her...")
   (proc 3)
   ((cmd 197) 0 0)
   ((cmd 197) 1 0)
   (proc 4) (str "Cole: ") (proc 0)
    (str "...!!")
   (proc 3)
   ((cmd 197) 0 0)
   ((cmd 197) 1 15)
   (proc 4) (str "Killer: ") (proc 1)
      (str "It's too late for me. I'm done for.")
   (proc 3)
   ((cmd 197) 0 0)
   ((cmd 197) 1 0)
   (proc 4) (str "Cole: ") (proc 0)
    (str "Why? Why would you do this?")
   (set-reg 16 #t)
   (proc 3))
 (seg (? (= Q 9) (= 0 #t) (= 14 #t) (= 15 #t))
   (proc 4) (str "Cole: ") (proc 0)
    (str "Sheila, try to rest a bit.")
   (proc 3))
 (seg (? (= Q 9) (= 0 #t))
   (proc 4) (str "Cole: ") (proc 0)
    (str "Sheila, are you alright?")
   (proc 3)
   ((cmd 197) 0 15)
   ((cmd 197) 1 0)
   (proc 4) (str "Sheila: ") (proc 2)
      (str "Ugh... uh... Uh... mmm...")
   (proc 3)
   ((cmd 197) 0 0)
   ((cmd 197) 1 0)
   (proc 4) (str "Cole: ") (proc 0)
    (str "I guess I should let her rest a little.")
   (proc 3))
 (seg (? (= Q 11) (= 0 #f) (= 23 #t))
   (proc 4) (str "Cole: ") (proc 0)
    (str "Killer was threatened by Ghoul. He took his family" 'br)
   (str "away and took advantage of Killer.")
   (proc 3))
 (seg (? (= Q 11) (= 0 #f) (= 16 #t))
   (proc 4) (str "Cole: ") (proc 0)
    (str "I can't believe Killer is still alive now.")
   (proc 3))
 (seg (? (= Q 11) (= 0 #f) (= 13 #f))
   (proc 4) (str "Cole: ") (proc 0)
    (str "Killer's done for.")
   (set-reg 13 #t)
   (proc 3))
 (seg (? (= Q 11) (= 0 #f) (= 14 #f))
   (proc 4) (str "Cole: ") (proc 0)
    (str "I wouldn't be alive if it wasn't for Nose.")
   (set-reg 14 #t)
   (proc 3))
 (seg (? (= Q 11) (= 0 #f))
   (proc 4) (str "Cole: ") (proc 0)
    (str "My bullet hit Killer in the brain, but he's not dead" 'br)
   (str "yet.")
   (proc 3))
 (seg (? (= Q 11) (= 0 #t) (= 16 #t) (= 17 #f))
   ((cmd 197) 0 0)
   ((cmd 197) 1 15)
   (proc 4) (str "Killer: ") (proc 1)
      (str "You surprised? This is the power of the" 'br)
   (str "resurrection drug!")
   (proc 3)
   ((cmd 197) 0 0)
   ((cmd 197) 1 0)
   (proc 4) (str "Cole: ") (proc 0)
    (str "What the shit?! How are you not dead?!")
   (proc 3)
   ((cmd 197) 0 0)
   ((cmd 197) 1 15)
   (proc 4) (str "Killer: ") (proc 1)
      (str "Cooger was thinking of the resurrection properties," 'br)
   (str "but the drug can also give humans eternal life!")
   (proc 3)
   ((cmd 197) 0 0)
   ((cmd 197) 1 0)
   (proc 4) (str "Cole: ") (proc 0)
    (str "What? Wait, you gave yourself the drug? You're crazy")
   (str ".")
   (set-reg 17 #t)
   (proc 3))
 (seg (? (= Q 11) (= 0 #t) (= 16 #t) (= 18 #f))
   ((cmd 197) 0 0)
   ((cmd 197) 1 15)
   (proc 4) (str "Killer: ") (proc 1)
      (str "No, Ghoul injected me with it!")
   (proc 3)
   ((cmd 197) 0 0)
   ((cmd 197) 1 0)
   (proc 4) (str "Cole: ") (proc 0)
    (str "Ghoul? Didn't you kill him as well?")
   (proc 3)
   ((cmd 197) 0 0)
   ((cmd 197) 1 15)
   (proc 4) (str "Killer: ") (proc 1)
      (str "No. I've been acting under his direction the whole time!")
   (proc 3)
   ((cmd 197) 0 0)
   ((cmd 197) 1 0)
   (proc 4) (str "Cole: ") (proc 0)
    (str "Huh?!?!")
   (proc 3)
   ((cmd 197) 0 0)
   ((cmd 197) 1 15)
   (proc 4) (str "Killer: ") (proc 1)
      (str "Strange things were happening around Cooger's lab." 'br)
   (str "Ghoul made me keep an eye on him. I even got a photo with" 'br)
   (str "him at a conference.")
   (proc 3)
   (proc 4) (str "Killer: ") (proc 1)
      (str "Other scientists didn't take him seriously. They" 'br)
   (str "thought a drug like this was impossible. Cooger got pissed" 'br)
   (str "about it.")
   (proc 3)
   (proc 4) (str "Killer: ") (proc 1)
      (str "He was excited until he got that terrible" 'br)
   (str "reception. Then he said...")
   (proc 3)
   (proc 4) (str "Killer: ") (proc 1)
      (str "'No one can underestimate the work I'm doing! I'll" 'br)
   (str "overcome death itself!'")
   (proc 3)
   (proc 4) (str "Killer: ") (proc 1)
      (str "It was tricky to keep track of all of Cooger's" 'br)
   (str "work, but then Ghoul ordered me to raid his home. I didn't" 'br)
   (str "think the drug would truly work.")
   (proc 3)
   (proc 4) (str "Killer: ") (proc 1)
      (str "I thought it was pointless, but Ghoul threatened to" 'br)
   (str "fire me, and I have a family to provide for...")
   (proc 3)
   ((cmd 197) 0 0)
   ((cmd 197) 1 0)
   (proc 4) (str "Cole: ") (proc 0)
    (str "So Ghoul was the culprit")
   (str ".")
   (set-reg 18 #t)
   (proc 3))
 (seg (? (= Q 11) (= 0 #t) (= 16 #t) (= 19 #f))
   ((cmd 197) 0 0)
   ((cmd 197) 1 15)
   (proc 4) (str "Killer: ") (proc 1)
      (str "Then Ghoul used my family for testing when I" 'br)
   (str "brought the drug back...")
   (proc 3)
   ((cmd 197) 0 0)
   ((cmd 197) 1 0)
   (proc 4) (str "Cole: ") (proc 0)
    (str "How could he?!")
   (proc 3)
   ((cmd 197) 0 0)
   ((cmd 197) 1 15)
   (proc 4) (str "Killer: ") (proc 1)
      (str "I wanted him dead, but he has an army of zombies" 'br)
   (str "with him, and for some reason they don't attack their" 'br)
   (str "creator, I guess.")
   (proc 3)
   ((cmd 197) 0 0)
   ((cmd 197) 1 0)
   (proc 4) (str "Cole: ") (proc 0)
    (str "But, Doc was attacked by zombies...")
   (proc 3)
   ((cmd 197) 0 0)
   ((cmd 197) 1 15)
   (proc 4) (str "Killer: ") (proc 1)
      (str "I thought it was best to watch Cooger, to see if he" 'br)
   (str "would be attacked by zombies. After all, I was experimented" 'br)
   (str "on as well.")
   (set-reg 19 #t)
   (proc 3))
 (seg (? (= Q 11) (= 0 #t) (= 16 #t) (= 20 #f))
   (proc 4) (str "Cole: ") (proc 0)
    (str "Why didn't you kill Doc when he got to the hotel? Was" 'br)
   (str "it because he didn't recognize you?")
   (proc 3)
   ((cmd 197) 0 0)
   ((cmd 197) 1 15)
   (proc 4) (str "Killer: ") (proc 1)
      (str "I was shocked to see him. That night, a cop" 'br)
   (str "attacked his lab and wreaked havoc on the station.")
   (proc 3)
   ((cmd 197) 0 0)
   ((cmd 197) 1 0)
   (proc 4) (str "Cole: ") (proc 0)
    (str "You mean Officer Jack...")
   (proc 3)
   ((cmd 197) 0 0)
   ((cmd 197) 1 15)
   (proc 4) (str "Killer: ") (proc 1)
      (str "If you inject the drug into a living person," 'br)
   (str "nothing happens. But when they die, they're revived as" 'br)
   (str "normal.")
   (proc 3)
   (proc 4) (str "Killer: ") (proc 1)
      (str "So if you inject someone who's about to die, they" 'br)
   (str "get eternal life. Cooger's drug was complete!")
   (proc 3)
   ((cmd 197) 0 0)
   ((cmd 197) 1 0)
   (proc 4) (str "Cole: ") (proc 0)
    (str "Doc said it wasn't ready yet, though.")
   (proc 3)
   (proc 4) (str "Cole: ") (proc 0)
    (str "Also, Jack tried to kill us.")
   (proc 3)
   ((cmd 197) 0 0)
   ((cmd 197) 1 15)
   (proc 4) (str "Killer: ") (proc 1)
      (str "Jack was also threatened by Ghoul. If he didn't" 'br)
   (str "die, he would've killed Cooger.")
   (proc 3)
   (proc 4) (str "Killer: ") (proc 1)
      (str "Maybe he was still partly human as a zombie...")
   (proc 3)
   ((cmd 197) 0 0)
   ((cmd 197) 1 0)
   (proc 4) (str "Cole: ") (proc 0)
    (str "Why did Jack die? Shouldn't he have gotten" 'br)
   (str "immortality?")
   (proc 3)
   ((cmd 197) 0 0)
   ((cmd 197) 1 15)
   (proc 4) (str "Killer: ") (proc 1)
      (str "I don't know. I can say that the drug has to move" 'br)
   (str "through the whole body. Maybe Jack had a gaping wound and it" 'br)
   (str "didn't work.")
   (set-reg 20 #t)
   (proc 3))
 (seg (? (= Q 11) (= 0 #t) (= 16 #t) (= 21 #f))
   (proc 4) (str "Cole: ") (proc 0)
    (str "But anyways, you didn't do anything when Doc came to" 'br)
   (str "the hotel.")
   (proc 3)
   ((cmd 197) 0 0)
   ((cmd 197) 1 15)
   (proc 4) (str "Killer: ") (proc 1)
      (str "Or did I? After I saw him, I informed Ghoul, and" 'br)
   (str "the zombies went to take care of Cooger for us.")
   (proc 3)
   (proc 4) (str "Killer: ") (proc 1)
      (str "And when I told him all that, he knew you weren't" 'br)
   (str "ordinary. Ghoul knew you would be the last person to stand" 'br)
   (str "in his way.")
   (proc 3)
   (proc 4) (str "Killer: ") (proc 1)
      (str "The zombies won't attack Ghoul and he can even" 'br)
   (str "control them. How do you think I survived all this time?")
   (proc 3)
   ((cmd 197) 0 0)
   ((cmd 197) 1 0)
   (proc 4) (str "Cole: ") (proc 0)
    (str "I guess an army of undead is quite an advantage.")
   (set-reg 21 #t)
   (proc 3))
 (seg (? (= Q 11) (= 0 #t) (= 16 #t) (= 22 #f))
   ((cmd 197) 0 0)
   ((cmd 197) 1 15)
   (proc 4) (str "Killer: ") (proc 1)
      (str "I was going to go to Cooger's house to destroy the" 'br)
   (str "evidence but you were already there finding the proof.")
   (proc 3)
   (proc 4) (str "Killer: ") (proc 1)
      (str "So I set up a bomb at the hotel and also kidnapped" 'br)
   (str "your girl, so if you survived, I'd still have the advantage.")
   (proc 3)
   (proc 4) (str "Killer: ") (proc 1)
      (str "Well, all my plans failed. You're quite the man.")
   (set-reg 22 #t)
   (proc 3))
 (seg (? (= Q 11) (= 0 #t) (= 16 #t) (= 23 #f))
   (proc 4) (str "Cole: ") (proc 0)
    (str "Where's Ghoul now?")
   (proc 3)
   ((cmd 197) 0 0)
   ((cmd 197) 1 15)
   (proc 4) (str "Killer: ") (proc 1)
      (str "He took a helicopter to the Bayside Research Lab." 'br)
   (str "But watch out, you saw what happened to Ray and Sally.")
   (proc 3)
   ((cmd 197) 0 0)
   ((cmd 197) 1 0)
   (proc 4) (str "Cole: ") (proc 0)
    (str "Did his zombies kill them?")
   (proc 3)
   ((cmd 197) 0 0)
   ((cmd 197) 1 15)
   (proc 4) (str "Killer: ") (proc 1)
      (str "Ah, no. He has... special weapons. And you won't be" 'br)
   (str "able to believe what they are")
   (proc 3)
   (proc 4) (str "Killer: ") (proc 1)
      (str "But Cole, you should go. You can be a hero... like" 'br)
   (str "Rambo or Rocky... or something...")
   (proc 3)
   ((cmd 197) 0 0)
   ((cmd 197) 1 0)
   (proc 4) (str "Cole: ") (proc 0)
    (str "Killer...")
   (set-reg 23 #t)
   (proc 3))
 (seg (? (= Q 11) (= 0 #t) (= 16 #t))
   (proc 4) (str "Killer: ") (proc 1)
      (str "...")
   (proc 19)
   (proc 4) (str "Cole: ") (proc 0)
    (str "Seems Killer kicked the bucket.")
   (proc 3))
 (seg (? (= Q 11) (= 0 #t))
   (proc 4) (str "Killer: ") (proc 1)
      (str "...")
   (proc 3)
   (proc 4) (str "Cole: ") (proc 0)
    (str "How could he still be alive after that?!")
   (set-reg 15 #t)
   (proc 3))
 (seg (? (= Q 8))
   (exec-mem 16384 0 0 1 8)
   (exec-mem 256 7)
   (str "Select Save Number.")
   (menu1
    20
    305
    34
    305
    48
    305
    62
    305
    20
    325
    34
    325
    48
    325
    62
    325
    68
    285
    (</>
     (/ (str " SAVE No.1 "))
     (/ (str " SAVE No.2 "))
     (/ (str " SAVE No.3 "))
     (/ (str " SAVE No.4 "))
     (/ (str " SAVE No.5 "))
     (/ (str " SAVE No.6 "))
     (/ (str " SAVE No.7 "))
     (/ (str " SAVE No.8 "))
     (/ (str "[CANCEL]"))))
   (text-reset 14)
   (text-frame 41 305)
   (set-reg 48 #t)
   (text-color 15)
   (str "WAIT....")
   (branch-var
    S
    (</>
     (/ (flag-save 1))
     (/ (flag-save 2))
     (/ (flag-save 3))
     (/ (flag-save 4))
     (/ (flag-save 5))
     (/ (flag-save 6))
     (/ (flag-save 7))
     (/ (flag-save 8))
     (/ (nop@))))
   (text-frame 17 284 76 340)
   (text-reset 14)
   (exec-mem 16384 0 0 1 1)
   (exec-mem 256 2)
   (nop@)
   (set-reg 0 #f))
 (seg (? (= Q 7))
   (exec-mem 16384 0 0 1 7)
   (exec-mem 256 6)
   (str "Select Load Number.")
   (menu1
    20
    305
    34
    305
    48
    305
    62
    305
    20
    325
    34
    325
    48
    325
    62
    325
    68
    285
    (</>
     (/ (str " LOAD No.1 "))
     (/ (str " LOAD No.2 "))
     (/ (str " LOAD No.3 "))
     (/ (str " LOAD No.4 "))
     (/ (str " LOAD No.5 "))
     (/ (str " LOAD No.6 "))
     (/ (str " LOAD No.7 "))
     (/ (str " LOAD No.8 "))
     (/ (str "[CANCEL]"))))
   (text-reset 14)
   (branch-var
    S
    (</>
     (/
      (exec-mem 10496 2 32 5 127 66 32 36 127 36 0 50)
      (exec-mem 10496 0 32 5 127 66 0)
      (flag-load 1))
     (/
      (exec-mem 10496 2 32 5 127 66 32 36 127 36 0 50)
      (exec-mem 10496 0 32 5 127 66 0)
      (flag-load 2))
     (/
      (exec-mem 10496 2 32 5 127 66 32 36 127 36 0 50)
      (exec-mem 10496 0 32 5 127 66 0)
      (flag-load 3))
     (/
      (exec-mem 10496 2 32 5 127 66 32 36 127 36 0 50)
      (exec-mem 10496 0 32 5 127 66 0)
      (flag-load 4))
     (/
      (exec-mem 10496 2 32 5 127 66 32 36 127 36 0 50)
      (exec-mem 10496 0 32 5 127 66 0)
      (flag-load 5))
     (/
      (exec-mem 10496 2 32 5 127 66 32 36 127 36 0 50)
      (exec-mem 10496 0 32 5 127 66 0)
      (flag-load 6))
     (/
      (exec-mem 10496 2 32 5 127 66 32 36 127 36 0 50)
      (exec-mem 10496 0 32 5 127 66 0)
      (flag-load 7))
     (/
      (exec-mem 10496 2 32 5 127 66 32 36 127 36 0 50)
      (exec-mem 10496 0 32 5 127 66 0)
      (flag-load 8))
     (/ (nop@))))
   (exec-mem 16384 0 0 1 1)
   (exec-mem 256 2)
   (nop@)
   (set-reg 0 #f))
 (seg*))