(mes
 (meta (engine 'ADV) (charset "pc98"))
 (seg*
  ((cmd 206) 1 2)
  (text-frame 17 284 76 340)
  (text-reset 14)
  (exec-mem 16384 0 0 1 1)
  (exec-mem 256 2)
  (loop
   (menu1
    18
    300
    38
    300
    (</>
     (/ (set-reg 10 #f) (text "　") (str "Book") (text "　"))
     (/ (set-reg 10 #t) (text "　") (str "Diary") (text "　"))
     (/ (set-reg 12 #f) (text "　") (str "Envelope") (text "　"))
     (/ (set-reg 12 #t) (text "　") (str "Photo") (text "　"))
     (/)))
   (text-reset 14)
   (seg-call)))
 (seg (? (= T 0) (= 11 #t) (= 14 #t) (= 15 #f))
   (proc 0)
   (str
    "In the diary, Jan 24 and Feb 6 jump out. Feb 6 was   also the same date as that photo. What was Doc doing on thatday?")
   (set-reg 15 #t)
   (proc 3))
 (seg (? (= T 0) (= 11 #t) (= 14 #t) (= 16 #f))
   (proc 0)
   (str "Let's start with Jan 24.")
   (proc 3)
   (str
    "Jan24: The experiments on dead guinea pigs suggest that     only cells near the injection site are revived. This could  be due to poor drug penetration.")
   (proc 3)
   (str
    "To revive the full body, I had to inject into the brain,    heart, and limbs. However, the revived guinea pigs were      violent. The cause here seems to be the brain.")
   (proc 3)
   (proc 0)
   (str "I wonder if he was worried about the rabidity of the drug even then?")
   (set-reg 16 #t)
   (proc 3))
 (seg (? (= T 0) (= 11 #t) (= 14 #t) (= 17 #f))
   (proc 0)
   (str "Next is from Feb 6...")
   (proc 3)
   (str
    "Feb6: I spoke at a conference about the prototype drug. I   was mocked and lost my temper. I regret that, but they didn'tbelieve a word I said.")
   (proc 3)
   (proc 0)
   (str "If anyone actually believed what Doc said at this    time...")
   (proc 3)
   (proc 0)
   (str "Anyways, next entry...")
   (set-reg 17 #t)
   (proc 3))
 (seg (? (= T 0) (= 11 #t) (= 14 #t) (= 18 #f))
   (proc 0)
   (str "This one is from Feb 25...")
   (proc 3)
   (str
    "Feb25: The violent effects of the revival are still         unknown. My hypothesis is that as time passes after brain    death, violent pulses increase but I have no clue why.")
   (proc 3)
   (str
    "If I can solve this issue, the Nobel Prize is mine! I can't wait to see the look on the other scientists' faces...")
   (proc 3)
   (proc 0)
   (str
    "That cop Jack was revived immediately and went       berserk. It must've been the same with the small animals.")
   (set-reg 18 #t)
   (proc 3))
 (seg (? (= T 0) (= 11 #t) (= 14 #t) (= 19 #f))
   (proc 0)
   (str "Feb 27...")
   (proc 3)
   (str
    "Feb27: Someone has stolen the resurrection drug. The lab    was destroyed, but there was a pile of materials in one      place.")
   (proc 3)
   (str
    "Perhaps the culprit snapped photos of documents and the     equipment. I contacted the police but it doesn't seem to be  going anywhere.")
   (proc 3)
   (str
    "The culprit must be someone who knows my work. Maybe the    person was at the conference. I will look around again       tomorrow.")
   (proc 3)
   (proc 0)
   (str "Huh? Someone broke into Doc's house and took his     work?")
   (proc 3)
   (proc 0)
   (str "Cain said that someone unleashed the drug a month    ago...")
   (set-reg 19 #t)
   (proc 3))
 (seg (? (= T 0) (= 11 #t) (= 14 #t) (= 20 #f))
   (str
    "Feb28: I still don't have any leads, but I'm working on     remaking the drug. If I don't complete it soon, my thunder   will be stolen. Maybe I should surprise Cole with this.")
   (proc 3)
   (proc 0)
   (str
    "Doc would've looked forward to seeing my shocked facewhen he dropped this on me.")
   (proc 3)
   (proc 0)
   (str
    "No clue to the culprit... I mean, Doc's address is   public so it could've been anyone.")
   (set-reg 20 #t)
   (proc 3))
 (seg (? (= T 0) (= 11 #t) (= 14 #t) (= 21 #f))
   (proc 0)
   (str "March 25... this is a week ago.")
   (proc 3)
   (str
    "Mar25: The drug is complete again. The rabidity problem is  still unsolved, but releasing it now is best to stay ahead   of that thief.")
   (proc 3)
   (proc 0)
   (str "That's all?")
   (proc 3)
   (proc 0)
   (str
    "No doubt someone stole Doc's work. Last month's      zombie outbreak that Cain mentioned... That's proof of the  thief's work.")
   (set-reg 21 #t)
   (proc 3))
 (seg (? (= T 0) (= 11 #t) (= 14 #t))
   (proc 0)
   (str "Should I re-read this?")
   (proc 3)
   (str
    "Jan24: The experiments on dead guinea pigs suggest that     only cells near the injection site are revived. This could  be due to poor drug penetration.")
   (proc 3)
   (str
    "To revive the full body, I had to inject into the brain,    heart, and limbs. However, the revived guinea pigs were      violent. The cause here seems to be the brain.")
   (proc 3)
   (str
    "Feb6: I spoke at a conference about the prototype drug. I   was mocked and lost my temper. I regret that, but they didn'tbelieve a word I said.")
   (proc 3)
   (str
    "Feb25: The violent effects of the revival are still         unknown. My hypothesis is that as time passes after brain    death, violent pulses increase but I have no clue why.")
   (proc 3)
   (str
    "If I can solve this issue, the Nobel Prize is mine! I can't wait to see the look on the other scientists' faces...")
   (proc 3)
   (str
    "Feb27: Someone has stolen the resurrection drug. The lab    was destroyed, but there was a pile of materials in one      place.")
   (proc 3)
   (str
    "Perhaps the culprit snapped photos of documents and the     equipment. I contacted the police but it doesn't seem to be  going anywhere.")
   (proc 3)
   (str
    "The culprit must be someone who knows my work. Maybe the    person was at the conference. I will look around again       tomorrow.")
   (proc 3)
   (str
    "Feb28: I still don't have any leads, but I'm working on     remaking the drug. If I don't complete it soon, my thunder   will be stolen. Maybe I should surprise Cole with this.")
   (proc 3)
   (str
    "Mar25: The drug is complete again. The rabidity problem is  still unsolved, but releasing it now is best to stay ahead   of that thief.")
   (proc 3)
   (proc 0)
   (str "I wonder who stole Doc's work?")
   (proc 3))
 (seg (? (= T 0) (= 10 #f))
   (proc 0)
   (str "This book... is a little strange.")
   (proc 3)
   (proc 0)
   (str
    "This looks like some kind of diary, not a textbook. Ididn't know Doc kept one.")
   (set-reg 10 #t)
   (proc 3))
 (seg (? (= T 0))
   (proc 0)
   (str "I get keeping a diary private... but keeping it in a safe?")
   (set-reg 11 #t)
   (proc 3))
 (seg (? (= T 1) (= 11 #t) (= 14 #t) (= 15 #f))
   (proc 0)
   (str
    "In the diary, Jan 24 and Feb 6 jump out. Feb 6 was   also the same date as that photo. What was Doc doing on thatday?")
   (set-reg 15 #t)
   (proc 3))
 (seg (? (= T 1) (= 11 #t) (= 14 #t) (= 16 #f))
   (proc 0)
   (str "Let's start with Jan 24.")
   (proc 3)
   (str
    "Jan24: The experiments on dead guinea pigs suggest that     only cells near the injection site are revived. This could  be due to poor drug penetration.")
   (proc 3)
   (str
    "To revive the full body, I had to inject into the brain,    heart, and limbs. However, the revived guinea pigs were      violent. The cause here seems to be the brain.")
   (proc 3)
   (proc 0)
   (str "I wonder if he was worried about the rabidity of the drug even then?")
   (set-reg 16 #t)
   (proc 3))
 (seg (? (= T 1) (= 11 #t) (= 14 #t) (= 17 #f))
   (proc 0)
   (str "Next is from Feb 6...")
   (proc 3)
   (str
    "Feb6: I spoke at a conference about the prototype drug. I   was mocked and lost my temper. I regret that, but they didn'tbelieve a word I said.")
   (proc 3)
   (proc 0)
   (str "If anyone actually believed what Doc said at this    time...")
   (proc 3)
   (proc 0)
   (str "Anyways, next entry...")
   (set-reg 17 #t)
   (proc 3))
 (seg (? (= T 1) (= 11 #t) (= 14 #t) (= 18 #f))
   (proc 0)
   (str "This one is from Feb 25...")
   (proc 3)
   (str
    "Feb25: The violent effects of the revival are still         unknown. My hypothesis is that as time passes after brain    death, violent pulses increase but I have no clue why.")
   (proc 3)
   (str
    "If I can solve this issue, the Nobel Prize is mine! I can't wait to see the look on the other scientists' faces...")
   (proc 3)
   (proc 0)
   (str
    "That cop Jack was revived immediately and went       berserk. It must've been the same with the small animals.")
   (set-reg 18 #t)
   (proc 3))
 (seg (? (= T 1) (= 11 #t) (= 14 #t) (= 19 #f))
   (proc 0)
   (str "Feb 27...")
   (proc 3)
   (str
    "Feb27: Someone has stolen the resurrection drug. The lab    was destroyed, but there was a pile of materials in one      place.")
   (proc 3)
   (str
    "Perhaps the culprit snapped photos of documents and the     equipment. I contacted the police but it doesn't seem to be  going anywhere.")
   (proc 3)
   (str
    "The culprit must be someone who knows my work. Maybe the    person was at the conference. I will look around again       tomorrow.")
   (proc 3)
   (proc 0)
   (str "Huh? Someone broke into Doc's house and took his     work?")
   (proc 3)
   (proc 0)
   (str "Cain said that someone unleashed the drug a month    ago...")
   (set-reg 19 #t)
   (proc 3))
 (seg (? (= T 1) (= 11 #t) (= 14 #t) (= 20 #f))
   (str
    "Feb28: I still don't have any leads, but I'm working on     remaking the drug. If I don't complete it soon, my thunder   will be stolen. Maybe I should surprise Cole with this.")
   (proc 3)
   (proc 0)
   (str
    "Doc would've looked forward to seeing my shocked facewhen he dropped this on me.")
   (proc 3)
   (proc 0)
   (str
    "No clue to the culprit... I mean, Doc's address is   public so it could've been anyone.")
   (set-reg 20 #t)
   (proc 3))
 (seg (? (= T 1) (= 11 #t) (= 14 #t) (= 21 #f))
   (proc 0)
   (str "March 25... this is a week ago.")
   (proc 3)
   (str
    "Mar25: The drug is complete again. The rabidity problem is  still unsolved, but releasing it now is best to stay ahead   of that thief.")
   (proc 3)
   (proc 0)
   (str "That's all?")
   (proc 3)
   (proc 0)
   (str
    "No doubt someone stole Doc's work. Last month's      zombie outbreak that Cain mentioned... That's proof of the  thief's work.")
   (set-reg 21 #t)
   (proc 3))
 (seg (? (= T 1) (= 11 #t) (= 14 #t))
   (proc 0)
   (str "Should I re-read this?")
   (proc 3)
   (str
    "Jan24: The experiments on dead guinea pigs suggest that     only cells near the injection site are revived. This could  be due to poor drug penetration.")
   (proc 3)
   (str
    "To revive the full body, I had to inject into the brain,    heart, and limbs. However, the revived guinea pigs were      violent. The cause here seems to be the brain.")
   (proc 3)
   (str
    "Feb6: I spoke at a conference about the prototype drug. I   was mocked and lost my temper. I regret that, but they didn'tbelieve a word I said.")
   (proc 3)
   (str
    "Feb25: The violent effects of the revival are still         unknown. My hypothesis is that as time passes after brain    death, violent pulses increase but I have no clue why.")
   (proc 3)
   (str
    "If I can solve this issue, the Nobel Prize is mine! I can't wait to see the look on the other scientists' faces...")
   (proc 3)
   (str
    "Feb27: Someone has stolen the resurrection drug. The lab    was destroyed, but there was a pile of materials in one      place.")
   (proc 3)
   (str
    "Perhaps the culprit snapped photos of documents and the     equipment. I contacted the police but it doesn't seem to be  going anywhere.")
   (proc 3)
   (str
    "The culprit must be someone who knows my work. Maybe the    person was at the conference. I will look around again       tomorrow.")
   (proc 3)
   (str
    "Feb28: I still don't have any leads, but I'm working on     remaking the drug. If I don't complete it soon, my thunder   will be stolen. Maybe I should surprise Cole with this.")
   (proc 3)
   (str
    "Mar25: The drug is complete again. The rabidity problem is  still unsolved, but releasing it now is best to stay ahead   of that thief.")
   (proc 3)
   (proc 0)
   (str "I wonder who stole Doc's work?")
   (proc 3))
 (seg (? (= T 1) (= 10 #f))
   (proc 0)
   (str "This book... is a little strange.")
   (proc 3)
   (proc 0)
   (str
    "This looks like some kind of diary, not a textbook. Ididn't know Doc kept one.")
   (set-reg 10 #t)
   (proc 3))
 (seg (? (= T 1))
   (proc 0)
   (str "I get keeping a diary private... but keeping it in a safe?")
   (set-reg 11 #t)
   (proc 3))
 (seg (? (= T 2) (= 21 #t) (= 22 #f))
   (proc 0)
   (str
    "If the person who stole Doc's work was in that photo,they were either killed by zombies or laughing their heads  off now.")
   (set-reg 22 #t)
   (proc 3))
 (seg (? (= T 2) (= 21 #t) (= 23 #f))
   (proc 0)
   (str
    "Doc looks so happy in this photo. Was he announcing  his work on the drug?")
   (set-reg 23 #t)
   (proc 3))
 (seg (? (= T 2) (= 21 #t))
   (proc 0)
   (str "There are other scientists in this photo...")
   (proc 3)
   (proc 0)
   (str "That man in front of Doc... is that Killer?")
   (proc 3)
   (image-file "A:¥GRAPH¥BL081.GPC")
   (image-mem 1 1)
   (proc 0)
   (str "Didn't Doc say he recongized Killer before?")
   (proc 3)
   (proc 0)
   (str "Could Killer have been listening to Doc at the       conference?")
   (proc 3)
   (proc 0)
   (str
    "Maybe Killer was investigating the zombies in that   other city, and it led him to Doc?")
   (proc 3)
   (proc 0)
   (str
    "Probably not. If that was the case, wouldn't a       policeman helped evacuate the city before the outbreak?     But...")
   (proc 3)
   (proc 0)
   (str
    "If Killer stole Doc's work, why didn't he kill him when we got to the hotel?")
   (proc 3)
   (proc 0)
   (str "He could've killed all three of us, right?")
   (proc 3)
   (proc 0)
   (str "Ah! The time! I gotta go see Cain!")
   (proc 3)
   (proc 0)
   (str "It'd be best to discuss this with Cain.")
   (proc 3)
   (exec-mem 10496 2 32 5 127 66 32 36 127 36 0 50)
   (exec-mem 10496 0 32 5 127 66 0)
   (nop@)
   (set-reg 24 #f)
   (mes-jump "A:¥MES¥000052.MES"))
 (seg (? (= T 2) (= 12 #f))
   (proc 0)
   (str "What's in this envelope?")
   (proc 3)
   (proc 0)
   (str
    "It contains a photo. The snapshot shows Doc at a     conference with other scientists.")
   (set-reg 12 #t)
   (proc 3))
 (seg (? (= T 2) (= 13 #f))
   (proc 0)
   (str "There's nothing in the envelope but the photo.")
   (set-reg 13 #t)
   (proc 3))
 (seg (? (= T 2))
   (proc 0)
   (str
    "Looking at the photo, it's from Feb 6 of this year.  So almost two months ago.")
   (set-reg 14 #t)
   (proc 3))
 (seg (? (= T 3) (= 21 #t) (= 22 #f))
   (proc 0)
   (str
    "If the person who stole Doc's work was in that photo,they were either killed by zombies or laughing their heads  off now.")
   (set-reg 22 #t)
   (proc 3))
 (seg (? (= T 3) (= 21 #t) (= 23 #f))
   (proc 0)
   (str
    "Doc looks so happy in this photo. Was he announcing  his work on the drug?")
   (set-reg 23 #t)
   (proc 3))
 (seg (? (= T 3) (= 21 #t))
   (proc 0)
   (str "There are other scientists in this photo...")
   (proc 3)
   (proc 0)
   (str "That man in front of Doc... is that Killer?")
   (proc 3)
   (image-file "A:¥GRAPH¥BL081.GPC")
   (image-mem 1 1)
   (proc 0)
   (str "Didn't Doc say he recongized Killer before?")
   (proc 3)
   (proc 0)
   (str "Could Killer have been listening to Doc at the       conference?")
   (proc 3)
   (proc 0)
   (str
    "Maybe Killer was investigating the zombies in that   other city, and it led him to Doc?")
   (proc 3)
   (proc 0)
   (str
    "Probably not. If that was the case, wouldn't a       policeman helped evacuate the city before the outbreak?     But...")
   (proc 3)
   (proc 0)
   (str
    "If Killer stole Doc's work, why didn't he kill him when we got to the hotel?")
   (proc 3)
   (proc 0)
   (str "He could've killed all three of us, right?")
   (proc 3)
   (proc 0)
   (str "Ah! The time! I gotta go see Cain!")
   (proc 3)
   (proc 0)
   (str "It'd be best to discuss this with Cain.")
   (proc 3)
   (exec-mem 10496 2 32 5 127 66 32 36 127 36 0 50)
   (exec-mem 10496 0 32 5 127 66 0)
   (nop@)
   (set-reg 24 #f)
   (mes-jump "A:¥MES¥000052.MES"))
 (seg (? (= T 3) (= 12 #f))
   (proc 0)
   (str "What's in this envelope?")
   (proc 3)
   (proc 0)
   (str
    "It contains a photo. The snapshot shows Doc at a     conference with other scientists.")
   (set-reg 12 #t)
   (proc 3))
 (seg (? (= T 3) (= 13 #f))
   (proc 0)
   (str "There's nothing in the envelope but the photo.")
   (set-reg 13 #t)
   (proc 3))
 (seg (? (= T 3))
   (proc 0)
   (str
    "Looking at the photo, it's from Feb 6 of this year.  So almost two months ago.")
   (set-reg 14 #t)
   (proc 3))
 (seg*))