(mes
 (meta (engine 'ADV) (charset "pc98"))
 (seg*
  ((cmd 206) 1 2)
  ((cmd 197) 0 0)
  ((cmd 197) 1 0)
  (exec-mem 10496 2 32 5 127 66 32 36 127 36 0 50)
  (exec-mem 10496 0 32 5 127 66 0)
  (image-file "A:¥GRAPH¥BL042.GPC")
  (image-mem 1 1)
  (image-file "A:¥GRAPH¥BL042B.GPC")
  (image-mem 1 1)
  (if (</>
       (//
        (? (= 97 #t))
        (image-file "A:¥GRAPH¥BL043.GPC")
        (image-mem 1 1)
        ((cmd 193) 0 "A:¥ANIME¥BL043.GPA")
        ((cmd 194)
         0
         "ｱｶ. ..ｵ...ｶ.. .ｲ.ｳ.ｵ..ｴ.ｲ.ｱ..ｵ...ｶ...ｴ...ｶ.. .ｵ...ｶ.. .ｴ...ｶ...ｵ...ｶ"))
       (//
        (image-file "A:¥GRAPH¥BL043.GPC")
        (image-mem 1 1)
        ((cmd 193) 0 "A:¥ANIME¥BL043.GPA")
        ((cmd 194)
         0
         "ｱｴ. ..ｶ....ｵ...ｴ..ｲ.ｳ.ｵ..ｲ.ｱ..ｴ.. ..ｶ...ｴ... .ｶ..ｵ..ｴ.. ｵ..ｶ...ｴｱ"))))
  (sound '|| 0)
  (sound '|| "A:¥MUSIC¥B0N_02.USO")
  (sound '|| 1)
  (exec-mem 10496 1 32 36 127 36 32 5 127 66 8 50)
  (text-frame 17 284 76 340)
  (text-reset 14)
  (if (</>
       (//
        (? (= 80 #f))
        (proc 0)
        (str "Oh, Nice to meet you! How are you doing?")
        (proc 3)
        ((cmd 197) 0 15)
        (proc 10)
        (str "You were here yesterday, right? Your name is Cole,  right?")
        (proc 3)
        ((cmd 197) 0 0)
        (proc 0)
        (str "Yep, Cole. I'm not nervous about being in a girl's   room, no. It's just a normal hotel room.")
        (proc 3)
        ((cmd 197) 0 15)
        (proc 10)
        (str "I'm Cathy. Nice to meet ya!")
        (set-reg 80 #t)
        (proc 3)
        ((cmd 197) 0 0))
       (//
        ((cmd 197) 0 15)
        (proc 10)
        (str "Cole...")
        (proc 3)
        ((cmd 197) 0 0))))
  ((cmd 182) "A:¥CLM¥BL043.CLM")
  (exec-mem 16384 0 0 1 1)
  (exec-mem 256 2)
  (nop@)
  (set-reg 0 #f)
  (set-reg 1 #t)
  (loop
   ((cmd 182) P 0)
   (if (</>
        (//
         (? (= Q 1))
         (nop@)
         (exec-mem 16384 0 0 1 1)
         (exec-mem 256 2)
         (set-reg 0 #f)
         (set-reg 1 #t))
        (//
         (? (= Q 2))
         (nop@)
         (exec-mem 16384 0 0 1 2)
         (exec-mem 256 1)
         (set-reg 0 #t)
         (set-reg 1 #f))
        (//
         (? (= Q 6))
         (nop@)
         (exec-mem 16384 0 0 1 6)
         (exec-mem 256 4)
         (set-reg 0 #f)
         (set-reg 1 #f))))
   (seg-call)
   ((cmd 197) 0 0)))
 (seg (? (= Q 9) (= 0 #f) (= 1 #t) (= 81 #f))
   (proc 0)
   (str "She's a nice woman with short hair. I like it. Quite a unique style.")
   (set-reg 81 #t)
   (proc 3))
 (seg (? (= Q 9) (= 0 #f) (= 1 #t) (= 82 #f))
   (proc 0)
   (str "She must use shampoo every day as her hair is shiny  and healthy.")
   (set-reg 82 #t)
   (proc 3))
 (seg (? (= Q 9) (= 0 #f) (= 1 #t))
   (proc 0)
   (str "Girls are very conscious of fashion trends, so they  don't have the same haircut year round like me.")
   (proc 15)
   (proc 3))
 (seg (? (= Q 10) (= 0 #f) (= 1 #t) (= 83 #f))
   (proc 0)
   (str "Is she younger than me? She has a pretty face. I     would like a sister like her.")
   (set-reg 83 #t)
   (proc 3))
 (seg (? (= Q 10) (= 0 #f) (= 1 #t) (= 84 #f))
   (proc 0)
   (str "Her hair is kinda boyish. She's younger than me but Ifeel nervous around her anyways.")
   (set-reg 84 #t)
   (proc 3))
 (seg (? (= Q 10) (= 0 #f) (= 1 #t))
   (proc 0)
   (str "Hard to believe a woman like this is surviving a     zombie apocalypse.")
   (proc 3))
 (seg (? (= Q 11) (= 0 #f) (= 1 #t) (= 85 #f))
   (proc 0)
   (str "Her clothes look boyish. I remember reading about    clothing like this in a magazine. I guess it's the new      style.")
   (set-reg 85 #t)
   (proc 3))
 (seg (? (= Q 11) (= 0 #f) (= 1 #t) (= 86 #f))
   (proc 0)
   (str "She's pretty. I hope we can be friends after all     this.")
   (set-reg 86 #t)
   (proc 3))
 (seg (? (= Q 11) (= 0 #f) (= 1 #t))
   (proc 0)
   (str "She's petite. Smaller than even Sheila.")
   (proc 3))
 (seg (? (= Q 12) (= 0 #f) (= 1 #t) (= 87 #f))
   (proc 0)
   (str "She's got it where it counts.")
   (proc 3)
   ((cmd 197) 0 15)
   (proc 10)
   (str "Uh... what're you looking at?")
   (proc 3)
   ((cmd 197) 0 0)
   (proc 0)
   (str "Ah, oops! I'm sorry! Sorry!")
   (set-reg 87 #t)
   (proc 3))
 (seg (? (= Q 12) (= 0 #f) (= 1 #t) (= 88 #f))
   (proc 0)
   (str "If I look again, she might say something again. I    don't to make this awkward.")
   (set-reg 88 #t)
   (proc 3))
 (seg (? (= Q 12) (= 0 #f) (= 1 #t))
   (proc 0)
   (str "I'm a man and a man's eyes gravitate to there. I     don't make the rules.")
   (proc 3))
 (seg (? (= Q 13) (= 0 #f) (= 1 #t) (= 89 #f))
   (proc 0)
   (str "Same kind of bed as my room. I wonder if all rooms   have the same bed.")
   (set-reg 89 #t)
   (proc 3))
 (seg (? (= Q 13) (= 0 #f) (= 1 #t))
   (proc 0)
   (str "The bed is tidy and neatly arranged. She's a girl    alright.")
   (proc 3))
 (seg (? (= Q 14) (= 0 #f) (= 1 #t) (= 90 #f))
   (proc 0)
   (str "The view from this room is very similar to mine.")
   (set-reg 90 #t)
   (proc 3))
 (seg (? (= Q 14) (= 0 #f) (= 1 #t) (= 91 #f))
   (proc 0)
   (str "Every room seems to have the same layout. I guess    that's a hotel for you.")
   (set-reg 91 #t)
   (proc 3))
 (seg (? (= Q 14) (= 0 #f) (= 1 #t))
   ((cmd 197) 0 15)
   (proc 10)
   (str "I've been watching from the windows for a good whilenow.")
   (proc 3)
   ((cmd 197) 0 0)
   (proc 0)
   (str "Yeah.")
   (proc 3))
 (seg (? (= Q 10) (= 0 #t) (= 1 #f) (= 97 #t) (= 98 #f))
   ((cmd 197) 0 15)
   (proc 10)
   (str "Huh? Sheila hasn't come back yet?")
   (proc 3)
   ((cmd 197) 0 0)
   (proc 0)
   (if (</>
        (//
         (? (= 99 #t))
         (str "I haven't been back to my room yet, so I should      probably get going.")
         (set-reg 98 #t)
         (proc 3)))))
   (set-reg 98 #t)
   (proc 3))
 (seg (? (= Q 10) (= 0 #t) (= 1 #f) (= 97 #t))
   ((cmd 197) 0 15)
   (proc 10)
   (if (</>
        (//
         (? (= 99 #t))
         (str "If Sheila doesn't come back, I'll be up to go with  you!")
         (proc 3)
         ((cmd 197) 0 0)
         (proc 0)
         (str "No, it's alright. I'll leave now. Sheila might be    back now, so I should get going."))
        (//
         (proc 3)
         ((cmd 197) 0 0)
         (proc 0)
         (str "That's right..."))))
   (proc 3))
 (seg (? (= Q 10) (= 0 #t) (= 1 #f) (= 92 #f))
   (proc 0)
   (str "I hope I'm not being rude, but how old are you?")
   (proc 3)
   ((cmd 197) 0 15)
   (proc 10)
   (str "Ha, I'll tell you. I just turned 20. Now, I guess   you're about twenty... four?")
   (proc 3)
   ((cmd 197) 0 0)
   (proc 0)
   (str "Well, you're right! Good guess.")
   (proc 3)
   ((cmd 197) 0 15)
   (proc 10)
   (str "Well, from my perspective, I see you as a big       brother.")
   (set-reg 92 #t)
   (proc 3))
 (seg (? (= Q 10) (= 0 #t) (= 1 #f) (= 93 #f))
   ((cmd 197) 0 15)
   (proc 10)
   (str "I'm pretty glad someone like you is here.")
   (proc 3)
   ((cmd 197) 0 0)
   (proc 0)
   (str "Everyone here seems nice. When I met Nose, I thought he was quite imitating, but he's actually quite nice.")
   (proc 3)
   ((cmd 197) 0 15)
   (proc 10)
   (str "Ha, if you told them that, then he would get angry.")
   (proc 3)
   ((cmd 197) 0 0)
   (proc 0)
   (str "Can you keep that a secret?")
   (set-reg 93 #t)
   (proc 3))
 (seg (? (= Q 10) (= 0 #t) (= 1 #f) (= 94 #f))
   (proc 0)
   (str "Cathy, what do you do for a living?")
   (proc 3)
   ((cmd 197) 0 15)
   (proc 10)
   (str "Back before the city was overrun, I worked at a     restaurant near the train station. Now, I just fight        zombies.")
   (proc 3)
   ((cmd 197) 0 0)
   (proc 0)
   (str "I guess it's hard being a girl.")
   (set-reg 94 #t)
   (proc 3))
 (seg (? (= Q 10) (= 0 #t) (= 1 #f) (= 95 #f))
   ((cmd 197) 0 15)
   (proc 10)
   (str "Oh, that lady that was with you. Is that your       girlfriend?")
   (proc 3)
   ((cmd 197) 0 0)
   (proc 0)
   (str "Oh, Sheila? She's my girlfriend.")
   (proc 3)
   ((cmd 197) 0 15)
   (proc 10)
   (str "Sheila, huh. She's very pretty. You're a lucky guy.")
   (proc 3)
   ((cmd 197) 0 0)
   (proc 0)
   (str "Really? I think I'm just silly, and indecisive, and  don't have much going for myself.")
   (proc 3)
   ((cmd 197) 0 15)
   (proc 10)
   (str "No need to be sorry. Seriously, it's fine.")
   (set-reg 95 #t)
   (proc 3))
 (seg (? (= Q 10) (= 0 #t) (= 1 #f) (= 96 #f))
   ((cmd 197) 0 15)
   (proc 10)
   (str "I knew you were a nice person at first, and I was   right!")
   (proc 3)
   (proc 10)
   (str "I like that.")
   (proc 3)
   ((cmd 197) 0 0)
   (proc 0)
   (str "Thanks.")
   (set-reg 96 #t)
   (proc 3))
 (seg (? (= Q 10) (= 0 #t) (= 1 #f) (= 97 #f))
   (proc 0)
   (str "Cathy's pretty upbeat, she can even smile in this    situation.")
   (proc 3)
   ((cmd 197) 0 15)
   (proc 10)
   (str "Yeah. At first, I couldn't stop shaking. I didn't   notice it until Ghoul said something. I'll be at ease       someday. So I'll hold onto that hope.")
   (proc 3)
   ((cmd 197) 0 0)
   (proc 0)
   (str "Cathy...")
   (proc 3)
   ((cmd 197) 0 15)
   (proc 10)
   (str "But...")
   (proc 3)
   (proc 10)
   (str "But I'm not a strong woman or anything. The reason Ican smile is because I believe in Ghoul...")
   (proc 3)
   (proc 10)
   (str "Cole, and I ask you for a favor?")
   (proc 3)
   (proc 10)
   (str "Can... you hold me?")
   (proc 3)
   (proc 10)
   (str "I've been waiting for a man like you. When I'm      scared, I used to have my boyfriend to hold, but...")
   (proc 3)
   ((cmd 197) 0 0)
   (proc 0)
   (str "Cathy, I know how you feel. But...")
   (proc 3)
   ((cmd 197) 0 15)
   (proc 10)
   (str "I know I'm not as beautiful as Sheila. I'm aware of that.")
   (proc 3)
   (proc 10)
   (str "You don't have to but I'm afraid I may die soon and I can't shake that feeling.")
   (proc 3)
   (proc 10)
   (str "Please, Cole. Just now, just for right now.")
   (proc 3)
   ((cmd 197) 0 0)
   (proc 0)
   (str "Alright, Cathy. It's the least I can do.")
   (proc 3)
   ((cmd 197) 0 15)
   (proc 10)
   (str "Thanks, Cole.")
   (proc 3)
   ((cmd 198) 32 5 127 66 0)
   (image-file "A:¥GRAPH¥BL042.GPC")
   (image-mem 1 1)
   (image-file "A:¥GRAPH¥BL042B.GPC")
   (image-mem 1 1)
   (image-file "A:¥GRAPH¥BL044.GPC")
   (image-mem 1 1)
   ((cmd 193) 0 "A:¥ANIME¥BL044.GPA")
   ((cmd 194)
    0
    "ｱｶ. ..ｵ...ｶ...ｲ.ｳ.ｵ..ｴ.ｲ.ｱ..ｵ...ｶ. ..ｴ...ｶ...ｵ...ｶ.. .ｴ...ｶ.. .ｵ..ｴ..ｵ...ｴ...ｶ.")
   ((cmd 198) 32 5 127 66 15)
   ((cmd 197) 0 15)
   (proc 10)
   (str "Ah...")
   (proc 3)
   (image-file "A:¥GRAPH¥BL045.GPC")
   (image-mem 1 0)
   ((cmd 197) 0 0)
   (proc 0)
   (str "Hm? Cathy, this money here...")
   (proc 3)
   (proc 0)
   (str "I don't think there's any place to spend money now. Iguess it's worthless.")
   (proc 3)
   ((cmd 197) 0 15)
   (proc 10)
   (str "My boyfriend gave me this. He's become a zombie.")
   (proc 3)
   ((cmd 197) 0 0)
   (proc 0)
   (str "I see... her boyfriend is a zombie now... why a pennythough?")
   (proc 3)
   ((cmd 197) 0 15)
   (proc 10)
   (str "Yeah. It may be a penny, but it's a nice good luck  charm.")
   (proc 3)
   ((cmd 197) 0 0)
   (proc 0)
   (str "Cathy must've been in a young, pure relationship.    After all, she's only 20.")
   (proc 3)
   (proc 0)
   (str "I feel bad for Cathy when I look at this coin, but   maybe she'll be happy if I hold her here.")
   (proc 3)
   ((cmd 197) 0 0)
   (str "Cole： Is this really what'll make Cathy happy?")
   (menu1 26 300 48 300 (</> (/ (text "ＨＯＬＤ")) (/ (text "ＲＥＦＵＳＥ"))))
   (text-reset 14)
   (proc 0)
   (str "I can't bear to see Cathy looking so sad.")
   (proc 3)
   (menu1 26 300 48 300 (</> (/ (text "ＨＯＬＤ")) (/ (text "ＲＥＦＵＳＥ"))))
   (text-reset 14)
   (branch-var
    S
    (</>
     (/
      (proc 0)
      (str "Right. I'm starting to understand Cathy, but holding her like this is a bit embarrassing.")
      (proc 3)
      (proc 0)
      (str "Cathy...")
      (proc 3)
      ((cmd 197) 0 15)
      (proc 10)
      (str "Ah...")
      (proc 3)
      ((cmd 197) 0 0)
      ((cmd 198) 32 5 127 66 0)
      (image-file "A:¥GRAPH¥BL046.GPC")
      (image-mem 1 1)
      ((cmd 193) 0 "A:¥ANIME¥BL046.GPA")
      ((cmd 194)
       0
       "ｱ. ..ｴ...ｵ..ｱ..ｴ..ｵ..ｲ.ｳ...ｲ.ｱ...ｴ..ｱ...ｵ...ｴ...ｵ..ｱ...ｴ...ｱ")
      ((cmd 198) 32 5 127 66 15)
      ((cmd 197) 0 15)
      (proc 10)
      (str "Come here...")
      (proc 3)
      (proc 10)
      (str "Ah... Cole...")
      (proc 3)
      (proc 10)
      (str "Ah... Cole... your hands are so warm...")
      (proc 3)
      (proc 10)
      (str "Hm... ha... ha...")
      (proc 3)
      (proc 10)
      (str "Oh... Cole!")
      (proc 3)
      (proc 10)
      (str "Cole... ha... ha...")
      (proc 3)
      (proc 10)
      (str "Oh Cole...")
      (proc 3)
      (proc 10)
      (str "... ah... ah")
      (proc 3)
      (proc 10)
      (str "Ugh... ugh...")
      (proc 3)
      (proc 10)
      (str "Oh... no more... ah... ah...")
      (proc 3)
      (proc 10)
      (str "Ah... ah... ah...")
      (proc 3)
      (proc 10)
      (str "Ah.... ah... come on... come on...")
      (proc 3)
      (proc 0)
      (str "Oh! Woah!")
      (proc 19)
      (proc 10)
      (str "Oh, Cole, that was lovely.")
      (proc 3)
      (proc 10)
      (str "Man Cole, it's like you have some mysterious power.")
      (proc 3)
      ((cmd 197) 0 0)
      (proc 0)
      (str "Is that so?")
      (proc 3)
      ((cmd 197) 0 15)
      (proc 10)
      (str "I'm kinda shy but I have no trouble talking to you. I'm telling you, you've got some mysterious power.")
      (proc 3)
      ((cmd 197) 0 0)
      (proc 0)
      (str "A mysterious power, huh? I've never heard that one   before.")
      (proc 3)
      ((cmd 197) 0 15)
      (proc 10)
      (str "You've lived here a while?")
      (proc 3)
      ((cmd 197) 0 0)
      (proc 0)
      (str "Ah, yes.")
      (proc 3)
      ((cmd 197) 0 15)
      (proc 10)
      (str "So, we've never spoken, but we might've passed each other by a few times in the street.")
      (proc 3)
      ((cmd 197) 0 0)
      (proc 0)
      (str "Ah. I always use that station for my commute. I pass by that restaurant every day.")
      (proc 3)
      (proc 0)
      (str "I better get going. Sheila's gonna be back soon.")
      (proc 3)
      ((cmd 197) 0 15)
      (proc 10)
      (str "Yeah, see ya.")
      (proc 3)
      ((cmd 197) 0 0)
      (proc 0)
      (str "Ah. See you later.")
      (set-reg 97 #t)
      (proc 3)
      (exec-mem 10496 2 32 5 127 66 32 36 127 36 0 50)
      (exec-mem 10496 0 32 5 127 66 0)
      (sound '|| 0)
      ((cmd 197) 0 0)
      (mes-jump "A:¥MES¥000029.MES"))
     (/
      (proc 0)
      (str "That's right. I know how Cathy feels, and her        boyfriend just passed away. I better keep this to myself.")
      (proc 3)
      (proc 0)
      (str "I'm sorry, Cathy. I don't think that's a good idea. Idon't want to be your boyfriend's substitute.")
      (proc 3)
      ((cmd 197) 0 15)
      (proc 10)
      (str "I'm sorry I actually tried, but you're kinder than Ithought.")
      (proc 3)
      ((cmd 197) 0 0)
      (proc 0)
      (str "What if I date Cathy?")
      (proc 3)
      ((cmd 197) 0 15)
      (proc 10)
      (str "It would've made me happy, but you're thinking for  the both of us. I'm sorry I tried that, Cole.")
      (proc 3)
      ((cmd 197) 0 0)
      (proc 0)
      (str "Oh, right. Maybe it's getting late.")
      (proc 3)
      ((cmd 197) 0 15)
      (proc 10)
      (str "Too late!")
      (proc 3)
      ((cmd 197) 0 0)
      (proc 0)
      (str "Haha. Sorry. Sheila will be back soon.")
      (proc 3)
      ((cmd 197) 0 15)
      (proc 10)
      (str "Cole...")
      (proc 3)
      (proc 10)
      (str "Thank you.")
      (set-reg 97 #t)
      (proc 3)
      ((cmd 197) 0 0)
      (exec-mem 10496 2 32 5 127 66 32 36 127 36 0 50)
      (exec-mem 10496 0 32 5 127 66 0)
      (sound '|| 0)
      (mes-jump "A:¥MES¥000029.MES")))))
 (seg (? (= Q 6) (= 0 #f) (= 1 #f))
   (menu1 30 300 52 300 (</> (/ (text "ＬＥＡＶＥ　")) (/ (text "ＳＴＡＹ　"))))
   (text-reset 14)
   (branch-var
    S
    (</>
     (/
      (proc 0)
      (str "I'm sorry, but Sheila will be back soon.")
      (proc 3)
      ((cmd 197) 0 15)
      (proc 10)
      (str "Come anytime...")
      (proc 3)
      ((cmd 197) 0 0)
      (exec-mem 10496 2 32 5 127 66 32 36 127 36 0 50)
      (exec-mem 10496 0 32 5 127 66 0)
      (sound '|| 0)
      (mes-jump "A:¥MES¥000029.MES"))
     (/ (proc 0) (str "I'm gonna talk to Cathy a little longer.") (proc 15) (proc 3)))))
 (seg (? (= Q 8))
   (exec-mem 16384 0 0 1 8)
   (exec-mem 256 7)
   (str "Select Save Number.")
   (menu1
    20
    305
    34
    305
    48
    305
    62
    305
    20
    325
    34
    325
    48
    325
    62
    325
    68
    285
    (</>
     (/ (str " SAVE No.1 "))
     (/ (str " SAVE No.2 "))
     (/ (str " SAVE No.3 "))
     (/ (str " SAVE No.4 "))
     (/ (str " SAVE No.5 "))
     (/ (str " SAVE No.6 "))
     (/ (str " SAVE No.7 "))
     (/ (str " SAVE No.8 "))
     (/ (str "[CANCEL]"))))
   (text-reset 14)
   (text-frame 41 305)
   (set-reg 48 #t)
   (text-color 15)
   (str "WAIT....")
   (branch-var
    S
    (</>
     (/ (flag-save 1))
     (/ (flag-save 2))
     (/ (flag-save 3))
     (/ (flag-save 4))
     (/ (flag-save 5))
     (/ (flag-save 6))
     (/ (flag-save 7))
     (/ (flag-save 8))
     (/ (nop@))))
   (text-frame 17 284 76 340)
   (text-reset 14)
   (exec-mem 16384 0 0 1 1)
   (exec-mem 256 2)
   (nop@)
   (set-reg 0 #f)
   (set-reg 1 #t))
 (seg (? (= Q 7))
   (exec-mem 16384 0 0 1 7)
   (exec-mem 256 6)
   (str "Select Load Number.")
   (menu1
    20
    305
    34
    305
    48
    305
    62
    305
    20
    325
    34
    325
    48
    325
    62
    325
    68
    285
    (</>
     (/ (str " LOAD No.1 "))
     (/ (str " LOAD No.2 "))
     (/ (str " LOAD No.3 "))
     (/ (str " LOAD No.4 "))
     (/ (str " LOAD No.5 "))
     (/ (str " LOAD No.6 "))
     (/ (str " LOAD No.7 "))
     (/ (str " LOAD No.8 "))
     (/ (str "[CANCEL]"))))
   (text-reset 14)
   (branch-var
    S
    (</>
     (/
      (exec-mem 10496 2 32 5 127 66 32 36 127 36 0 50)
      (exec-mem 10496 0 32 5 127 66 0)
      (flag-load 1))
     (/
      (exec-mem 10496 2 32 5 127 66 32 36 127 36 0 50)
      (exec-mem 10496 0 32 5 127 66 0)
      (flag-load 2))
     (/
      (exec-mem 10496 2 32 5 127 66 32 36 127 36 0 50)
      (exec-mem 10496 0 32 5 127 66 0)
      (flag-load 3))
     (/
      (exec-mem 10496 2 32 5 127 66 32 36 127 36 0 50)
      (exec-mem 10496 0 32 5 127 66 0)
      (flag-load 4))
     (/
      (exec-mem 10496 2 32 5 127 66 32 36 127 36 0 50)
      (exec-mem 10496 0 32 5 127 66 0)
      (flag-load 5))
     (/
      (exec-mem 10496 2 32 5 127 66 32 36 127 36 0 50)
      (exec-mem 10496 0 32 5 127 66 0)
      (flag-load 6))
     (/
      (exec-mem 10496 2 32 5 127 66 32 36 127 36 0 50)
      (exec-mem 10496 0 32 5 127 66 0)
      (flag-load 7))
     (/
      (exec-mem 10496 2 32 5 127 66 32 36 127 36 0 50)
      (exec-mem 10496 0 32 5 127 66 0)
      (flag-load 8))
     (/ (nop@))))
   (exec-mem 16384 0 0 1 1)
   (exec-mem 256 2)
   (nop@)
   (set-reg 0 #f)
   (set-reg 1 #t))
 (seg*))