(mes
 (meta (engine 'ADV) (charset "pc98"))
 (seg*
  ((cmd 206) 1 1)
  (image-file "A:¥GRAPH¥BL032.GPC") (image-mem 1 1)
  (sound '|| 0)
  (sound '|| "A:¥MUSIC¥B0N_07.USO")
  (sound '|| 1)
  (image-file "A:¥GRAPH¥BL039.GPC") (image-mem 1 1)
  ((cmd 193) 0 "A:¥ANIME¥BL039.GPA")
  ((cmd 194) 0 "ｱｳ. ..ｳ...ｵ...ｴ..ｲ...ｱ.ｵ...ｳ...ｴ...ｳ...ｵ...ｳ")
  ((cmd 198) 32 5 127 66 15)
  (proc 4) (str "Cole: ") (proc 0)
   (str "Oh...")
  (proc 3)
  (proc 4) (str "Cole: ") (proc 0)
   (str "Shelia, Doc, you can go on ahead. I'll be there when" 'br)
   (str "we're done.")
  (proc 19)
  (proc 4) (str "Sheila: ") (proc 2)
     (str "Ok.")
  (proc 3)
  (proc 4) (str "Cole: ") (proc 0)
   (str "Hello there.")
  (proc 19)
  ((cmd 197) 0 15)
  (proc 4) (str "Nose: ") (proc 1)
   (str "You can call me Nose. Sorry to intrude, it's about" 'br)
   (str "Ray. You'll have to forgive him for his behavior.")
  (proc 3)
  ((cmd 197) 0 0)
  (proc 4) (str "Cole: ") (proc 0)
   (str "Uh, why?")
  (proc 3)
  ((cmd 197) 0 15)
  (proc 4) (str "Nose: ") (proc 1)
   (str "There are still some zombies on the second floor." 'br)
   (str "There could be eight or so, and Ray's girlfriend is one of  them.")
  (proc 3)
  ((cmd 197) 0 0)
  (proc 4) (str "Cole: ") (proc 0)
   (str "I see. Are you sure it's her? Zombies look nothing" 'br)
   (str "like humans.")
  (proc 3)
  ((cmd 197) 0 15)
  (proc 4) (str "Nose: ") (proc 1)
   (str "Yeah, she has this necklace he gave her. When we were" 'br)
   (str "down there, he saw that one of the zombies had it.")
  (proc 3)
  (proc 4) (str "Nose: ") (proc 1)
   (str "Earlier, Ray and I were down there, trying to kill" 'br)
   (str "her, but Ray was so repulsed. So, can you do me a favor?")
  (proc 3)
  ((cmd 197) 0 0)
  (proc 4) (str "Cole: ") (proc 0)
   (str "I don't really want to help Ray though.")
  (proc 3)
  ((cmd 197) 0 15)
  (proc 4) (str "Nose: ") (proc 1)
   (str "Well, I can't force you to do this, but if someone" 'br)
   (str "can deal with the zombies downstairs...")
  (proc 3)
  ((cmd 197) 0 0)
  (exec-mem 256 0)
  (menu1 30 300 52 300 (</> (/ (text "ＡＣＣＥＰＴ　")) (/ (text "　ＤＥＣＬＩＮＥ"))))
  (text-reset 14)
  (branch-var
   S
   (</>
    (/
     (proc 4) (str "Cole: ") (proc 0)
      (str "Alright, leave the zombies downstairs to me.")
     (proc 3)
     ((cmd 197) 0 15)
     (proc 4) (str "Nose: ") (proc 1)
      (str "Thank you. I'll tell the boss that we talked.")
     (proc 3)
     ((cmd 197) 0 0)
     (proc 4) (str "Cole: ") (proc 0)
      (str "Ah")
     (str "."))
    (/
     (proc 4) (str "Cole: ") (proc 0)
      (str "The 2nd floor is crawling with zombies, isn't it?")
     (proc 3)
     ((cmd 197) 0 15)
     (proc 4) (str "Nose: ") (proc 1)
      (str "Yes, I can't do it, because I keep thinking of Ray." 'br)
   (str "Think of this as helping him.")
     (proc 3)
     ((cmd 197) 0 0)
     (proc 4) (str "Cole: ") (proc 0)
      (str "Ah. I understand. Leave it to me. I'll help her find" 'br)
   (str "peace.")
     (proc 3)
     ((cmd 197) 0 15)
     (proc 4) (str "Nose: ") (proc 1)
      (str "I'll tell the boss about this, but Sally will be by" 'br)
   (str "later for more details.")
     (proc 3)
     ((cmd 197) 0 0)
     (proc 4) (str "Cole: ") (proc 0)
      (str "Okay")
     (str "."))))
  (proc 3)
  ((cmd 197) 0 15)
  (proc 4) (str "Nose: ") (proc 1)
   (str "By the way, you're a lucky guy with that girlfriend" 'br)
   (str "of yours!")
  (proc 3)
  ((cmd 197) 0 0)
  (proc 4) (str "Cole: ") (proc 0)
   (str "Oh? Shelia?")
  (proc 3)
  ((cmd 197) 0 15)
  (proc 4) (str "Nose: ") (proc 1)
   (str "She's so cute!")
  (proc 3)
  ((cmd 197) 0 0)
  (proc 4) (str "Cole: ") (proc 0)
   (str "If you make a move, I will shoot you.")
  (proc 3)
  ((cmd 197) 0 15)
  (proc 4) (str "Nose: ") (proc 1)
   (str "Ha! When you came in, I knew you were a scary guy!")
  (proc 3)
  ((cmd 197) 0 0)
  (proc 4) (str "Cole: ") (proc 0)
   (str "Hahaha, okay, but the second floor is to repay our" 'br)
   (str "debt.")
  (proc 3)
  ((cmd 197) 0 15)
  (proc 4) (str "Nose: ") (proc 1)
   (str "Well, in return, I'll get you the Big Dog buffet from" 'br)
   (str "Golden Palace!")
  (proc 3)
  ((cmd 197) 0 0)
  (proc 4) (str "Cole: ") (proc 0)
   (str "Definitely. Looking forward to it.")
  (proc 3)
  (proc 4) (str "Cole: ") (proc 0)
   (str "Nose seemed imposing, but he's actually a nice guy.")
  (proc 3)
  (exec-mem 10496 2 32 5 127 66 32 36 127 36 0 50)
  (exec-mem 10496 0 32 5 127 66 0)
  ((cmd 204) 99)
  (sound '|| 0)
  ((cmd 197) 0 0)
  (mes-jump "A:¥MES¥000018.MES"))
 (seg*))