(mes
 (meta (engine 'ADV) (charset "pc98"))
 (seg*
  ((cmd 182) "A:¥CLM¥BL029A.CLM")
  (exec-mem 16384 0 0 1 6)
  (exec-mem 256 4)
  (loop ((cmd 182) P 3) (seg-call)))
 (seg (? (= Q 1)) (nop@))
 (seg (? (= Q 2)) (nop@))
 (seg (? (= Q 3)) (nop@))
 (seg (? (= Q 4)) (nop@))
 (seg (? (= Q 5)) (nop@))
 (seg (? (= Q 6)) (nop@))
 (seg (? (= Q 7)) (nop@))
 (seg (? (= Q 8)) (nop@))
 (seg (? (= Q 11))
   (proc 0)
   (str "That voice certainly came from over here.")
   (proc 3)
   (proc 0)
   (str "I have... enough bullets. Let's go!")
   (proc 3)
   ((cmd 198) 32 5 127 66 0)
   (mes-jump "A:¥MES¥000026.MES"))
 (seg*
  (proc 0)
  (str "That voice didn't come from here. It certainly came  from Room 103.")
  (proc 3))
 (seg*))