; Dead of the Brain English Translation - OPEN_1.MES
; Translated by Crookerwine
; Edited by JackDBS
; 2.0 fixes and comments by trentsignia
(mes
 (meta (engine 'ADV) (charset "pc98"))
 (seg*
  ((cmd 209) 0)
  (mouse 3 0 0)								; PC98 only
  (text-frame 0 0 79 399)
  (text-reset 14)
  (sound '|| "A:¥MUSIC¥B0N_05.USO") (sound '|| 1)			; PC98/X68K
; (sound '|| 0) (sound 'cd 5)						  FMT
  (image-file "A:¥GRAPH¥FRR.GPC") (image-mem 0)
  (image-file "A:¥GRAPH¥BLOP01.GPC") (image-mem 1)
  (exec-mem 10496 2 32 5 127 66 35 17 44 22 0 50)
  ((cmd 209) 1 10)
  (delay 50)
  (exec-mem 10496 1 35 17 44 22 32 5 127 66 8 50)
  (text-frame 17 284 76 340)
  (text-reset 14)
  (proc 4) (str "Cole: ") (proc 0)
   (str "Ah, finally. Home at last.")
  (proc 3)
  (proc 4) (str "Cole: ") (proc 0)
   (str "Man, I got worked to death painting those walls today.")
  (str "Why don't they make the temps do it?")
  (proc 3)
  (proc 4) (str "Cole: ") (proc 0)
   (str "Why do I have to do all the boring chores? Thanks to" 'br)
  (str "that, I had to work overtime again today!")
  (proc 3)
  (proc 4) (str "Cole: ") (proc 0)
   (str "Whatever, overtime pays well so I ain't complaining.")
  (proc 3)
  (proc 4) (str "Cole: ") (proc 0)
   (str "God, I'm all sweaty. I should go take a shower and" 'br)
  (str "relax for a bit.")
  (proc 3)
  ((cmd 198) 32 5 127 66 0)
  (sound '|se | 29)							; PC98/X68K
  (text-delay 0)
  (repeat 3 (<> (text "　　　　　　　　　　　　　　・") (proc 19) (delay 50 0)))
  (text-reset 14)
  ((cmd 198) 32 5 127 66 15)
  (proc 4) (str "Cole: ") (proc 0)
   (str "Ah, all relaxed now!")
  (proc 3)
  (proc 4) (str "Cole: ") (proc 0)
   (str "I love my after-shower beer as well. Try it once, you" 'br)
   (str "can never stop having them!")
  (proc 3)
  (proc 4) (str "Cole: ") (proc 0)
   (str "Well, another day of work done. I wonder when" 'br)
  (str "something interesting will happen for once!")
  (proc 3)
  (proc 4) (str "Cole: ") (proc 0)
   (str "Even if it's a massive incident that baffles the" 'br)
  (str "world!")
  (proc 3)
  (sound '|se | 24)
  (exec-mem 10496 2 32 5 127 66 110 30 126 42 0 50)
  (text-frame 16 22 40 265)
  (text-reset 14)
  (delay 200 0)
  (sound '|se | 29)
  (text-frame 17 284 76 340)
  (text-reset 14)
  (proc 4) (str "Cole: ") (proc 0)
   (str "Hm? Who could be calling this late?")
  (proc 3)
; (sound '|| 0)								  FMT
  (proc 4) (str "Cole: ") (proc 0)
   (str "Hi, this is Cole speaking.")
  (proc 3)
  (image-file "A:¥GRAPH¥BLOP02.GPC") (image-mem 1 1)
  ((cmd 193) 0 "A:¥ANIME¥BLOP02.GPA")					; PC98 HDD mod
  ((cmd 194) 0 "ｱｶ. .ｱ..ｴ..ｵ..ｶ.ｵ..ｱ.ｶ. .ｴ...ｵ.ｶ..ｲ.ｳ.ｵ...ｴ.ｲ.ｱ. .ｵ.ｶ.ｴ..ｶ.ｱ. .ｶ.ｱ")
  (exec-mem 10496 0 48 21 79 50 8)
  ((cmd 197) 0 15)
  (proc 4) (str "Cooger: ") (proc 1)
     (str "Cole, it's me, Cooger.")
  (proc 3)
  ((cmd 197) 0 0)
  (proc 4) (str "Cole: ") (proc 0)
   (str "Oh, it's you, Doc.")
  (proc 3)
  (proc 4) (str "Cole: ") (proc 0)
   (str "Why're you calling in the middle of the night?")
  (proc 3)
  ((cmd 197) 0 15)
  (proc 4) (str "Cooger: ") (proc 1)
     (str "It's amazing, Cole! You gotta see my latest" 'br)
  (str "invention! It'll knock your socks off!")
  (proc 3)
  ((cmd 197) 0 0)
  (proc 4) (str "Cole: ") (proc 0)
   (str "This again? Last time, you pumped so much blood into" 'br)
  (str "that artifical heart that it burst!")
  (proc 3)
  (proc 4) (str "Cole: ") (proc 0)
   (str "My jacket got soaked! It was such a pain to wash it," 'br)
  (str "I don't think I got rid of the smell.")
  (proc 3)
  ((cmd 197) 0 15)
  (proc 4) (str "Cooger: ") (proc 1)
     (str "I assure you, it's amazing! No blood this time! I" 'br)
  (str "mean, less blood. Can you just come over now?")
  (proc 3)
  ((cmd 197) 0 0)
  (proc 4) (str "Cole: ") (proc 0)
   (str "Now? I'm too tired. How about tomorrow?")
  (proc 3)
  ((cmd 197) 0 15)
  (proc 4) (str "Cooger: ") (proc 1)
     (str "Right now. I'll tell Terry about you and Sheila!")
  (proc 3)
  ((cmd 197) 0 0)
  (proc 4) (str "Cole: ") (proc 0)
   (str "Alright! I'll be there!")
  (proc 3)
  ((cmd 197) 0 15)
  (proc 4) (str "Cooger: ") (proc 1)
     (str "Ha! I'll be waiting!")
  (proc 3)
  ((cmd 197) 0 0)
  (exec-mem 10496 0 47 20 80 51 0)
  (text-frame 23 82 40 265)
  (text-reset 14)
  (image-file "A:¥GRAPH¥BLOP01.GPC") (image-mem 1 1)
  (exec-mem 10496 1 110 30 126 42 32 5 127 66 8 50)
  (text-frame 17 284 76 340)
  (text-reset 14)
  (proc 4) (str "Cole: ") (proc 0)
   (str "Doc's always threatening to expose Sheila and I when" 'br)
  (str "he wants something.")
  (proc 3)
  (proc 4) (str "Cole: ") (proc 0)
   (str "Terry doesn't know I'm seeing Sheila, and he's" 'br)
  (str "planning to make moves on her. He came to ask me for advice" 'br)
  (str "on it!")
  (proc 3)
  (proc 4) (str "Cole: ") (proc 0)
   (str "I'll figure it out when he finds out...")
  (proc 3)
  (proc 4) (str "Cole: ") (proc 0)
   (str "If I don't go now, Doc will never let me hear the end" 'br)
  (str "of it. I wonder what he did this time...")
  (proc 3)
  (exec-mem 10496 2 32 5 127 66 32 36 127 36 0 50)
  (exec-mem 10496 0 32 5 127 66 0)
  (sound '|| 0)
; (sound 'cd 4)								  FMT
  (image-file "A:¥GRAPH¥BLOP03.GPC") (image-mem 1 1)
  (image-file "A:¥GRAPH¥BLOP04.GPC") (image-mem 1 0)
  (sound '|| "A:¥MUSIC¥B0N_04.USO") (sound '|| 1)			; PC98/X68K
  ((cmd 193) 0 "A:¥ANIME¥BLOP04.GPA")
  ((cmd 194) 0 "ｱ. ..ｴ.ｲｳ..ｲｱｵ....ｴ..ｱ..ｵ..ｴ...ｵ..ｴ..ｵ....ｱ..ｵ..ｱ")
  (exec-mem 10496 1 32 36 127 36 32 5 127 66 8 50)			; PC98/FMT
; (exec-mem 10752 1 32 36 127 35 32 5 127 66 8 50)			  X68K
  (proc 4) (str "Cole: ") (proc 0)
   (str "Why are you waiting here, Doc?")
  (proc 3)
  ((cmd 197) 0 15)
  (proc 4) (str "Cooger: ") (proc 1)
     (str "The neighbours don't know I'm home, so I couldn't" 'br)
  (str "have you call to me out loud.")
  (proc 3)
  (proc 4) (str "Cooger: ") (proc 1)
     (str "I don't want anyone to know about this one.")
  (proc 3)
  ((cmd 197) 0 0)
  (proc 4) (str "Cole: ") (proc 0)
   (str "I see. So, what's this new invention?")
  (proc 3)
  ((cmd 197) 0 15)
  (proc 4) (str "Cooger: ") (proc 1)
     (str "It's in the lab, come see.")
  (proc 3)
  ((cmd 197) 0 0)
  ((cmd 198) 32 5 127 66 0)
  (image-file "A:¥GRAPH¥BLOP05.GPC") (image-mem 1 1)
  (image-file "A:¥GRAPH¥BLOP04.GPC") (image-mem 1 1)
  ((cmd 198) 32 5 127 66 15)
  (proc 4) (str "Cole: ") (proc 0)
   (str "I'm always impressed at how cool this lab is. Most" 'br)
  (str "people wouldn't believe this is a university professor's" 'br)
  (str "home.")
  (proc 3)
  ((cmd 197) 0 15)
  (proc 4) (str "Cooger: ") (proc 1)
     (str "Well, since my wife passed, all I have is my" 'br)
  (str "research.")
  (proc 3)
  ((cmd 197) 0 0)
  (proc 4) (str "Cole: ") (proc 0)
   (str "Oh, right... Sorry, I forgot, don't look sad.")
  (proc 3)
  (proc 4) (str "Cole: ") (proc 0)
   (str "I just spoke without thinking, I didn't mean to...")
  (proc 3)
  (proc 4) (str "Cole: ") (proc 0)
   (str "Hm?")
  (proc 3)
  (proc 4) (str "Cole: ") (proc 0)
   (str "Doc, did you hear that? Sounded like someone moaning.")
  (proc 3)
  (proc 4) (str "Cole: ") (proc 0)
   (str "Yeah... like a baby...")
  (proc 3)
  ((cmd 197) 0 15)
  (proc 4) (str "Cooger: ") (proc 1)
     (str "Cole, watch it!")
  (proc 3)
  ((cmd 197) 0 0)
  (image-file "A:¥GRAPH¥BLOP05.GPC")
  ((cmd 198) 32 5 127 66 0)
  (sound '|| 0)
; (sound 'cd 0)								  FMT
  (image-mem 1 1)
  (image-file "A:¥GRAPH¥BLOP06.GPC") (image-mem 1 1)
  ((cmd 198) 32 5 127 66 15)
  (sound '|se | 3)
  (proc 4) (str "Cole: ") (proc 0)
   (str "!!!")
  (proc 19)
  (proc 4) (str "Cooger: ") (proc 1)
     (str "Cole, duck!")
  (proc 3)
; (delay 40 0)								  FMT
  (sound '|se | 9) (delay 15)
  (sound '|se | 9) (delay 10)
  (sound '|se | 9)
  ((cmd 198) 32 5 127 66 0)
  (image-file "A:¥GRAPH¥BLOP05.GPC") (image-mem 1 1)
  (image-file "A:¥GRAPH¥BLOP04.GPC") (image-mem 1 1)
  ((cmd 198) 32 5 127 66 15)
  (sound '|| "A:¥MUSIC¥B0N_04.USO") (sound '|| 1)			; PC98/X68K
; (sound '|| 0) (sound 'cd 4)						  FMT
  (proc 4) (str "Cole: ") (proc 0)
   (str "Woah! What's with that cat?!")
  (proc 3)
  ((cmd 197) 0 15)
  (proc 4) (str "Cooger: ") (proc 1)
     (str "Cole! Did you get bit? Scratched?! Anything?!")
  (proc 3)
  ((cmd 197) 0 0)
  (proc 4) (str "Cole: ") (proc 0)
   (str "No. Nothing hurts, I'm alright. So...")
  (proc 3)
  (proc 4) (str "Cole: ") (proc 0)
   (str "This was your cat, wasn't it?")
  (proc 3)
  ((cmd 197) 0 15)
  (proc 4) (str "Cooger: ") (proc 1)
     (str "Yes, it's Kitty.")
  (proc 3)
  ((cmd 197) 0 0)
  (proc 4) (str "Cole: ") (proc 0)
   (str "Cole: Kitty, huh? Right, so why the hell did your pet cat" 'br)
  (str "attack me?! Does it have rabies?!")
  (proc 3)
  ((cmd 197) 0 15)
  (proc 4) (str "Cooger: ") (proc 1)
     (str "No... The cat died a week ago.")
  (proc 3)
  ((cmd 197) 0 0)
  (proc 4) (str "Cole: ") (proc 0)
   (str "Huh?! Don't be crazy, it jumped right at me! That's" 'br)
  (str "not the same quiet Kitty as before!")
  (proc 3)
  (proc 4) (str "Cole: ") (proc 0)
   (str "It must be rabid! Just tell it straight, I'm not a" 'br)
  (str "health inspector, ya know.")
  (proc 3)
  ((cmd 197) 0 15)
  (proc 4) (str "Cooger: ") (proc 1)
     (str "Cole, Kitty isn't rabid. You've got it all wrong.")
  (proc 3)
  ((cmd 197) 0 0)
  (proc 4) (str "Cole: ") (proc 0)
   (str "Got it all wrong? What do you mean?! And what's with" 'br)
  (str "that week-old dead cat shit? Shooting it was just cruel!")
  (proc 3)
  ((cmd 197) 0 15)
  (proc 4) (str "Cooger: ") (proc 1)
     (str "Listen to me, Cole!")
  (proc 3)
  (proc 4) (str "Cooger: ") (proc 1)
     (str "Kitty died a week ago. I'm certain it wasn't rabies.")
  (proc 3)
  (proc 4) (str "Cooger: ") (proc 1)
     (str "I found the body just after I made the first sample" 'br)
   (str "of my new resurrection drug.")
  (proc 3)
  ((cmd 197) 0 0)
  (proc 4) (str "Cole: ") (proc 0)
   (str "Resurrection drug? Like, the kind of thing that can" 'br)
  (str "revive the dead?")
  (proc 3)
  ((cmd 197) 0 15)
  (proc 4) (str "Cooger: ") (proc 1)
     (str "Yes. Kitty died of old age. I felt sorry for it, but")
  (str "I made it my test subject.")
  (proc 3)
  ((cmd 197) 0 0)
  (proc 4) (str "Cole: ") (proc 0)
   (str "Doc, I can't get what you're saying. There's no way" 'br)
  (str "you've made a drug like this. Sure, you're a genius" 'br)
  (str "scientist, but this is the stuff of movies!")
  (proc 3)
  ((cmd 197) 0 15)
  (proc 4) (str "Cooger: ") (proc 1)
     (str "I know people would think this kind of thing is" 'br)
  (str "impossible. Your reaction is quite understandable, Cole.")
  (proc 3)
  (proc 4) (str "Cooger: ") (proc 1)
     (str "Yet, I must make you realize that this isn't science")
  (str "fiction!")
  (proc 3)
  ((cmd 197) 0 0)
  (proc 4) (str "Cole: ") (proc 0)
   (str "What're you gonna do?")
  (proc 3)
  ((cmd 197) 0 15)
  (proc 4) (str "Cooger: ") (proc 1)
     (str "I will show you the drug in full force!")
  (proc 3)
  ((cmd 197) 0 0)
  (proc 4) (str "Cole: ") (proc 0)
   (str "...")
  (proc 3)
  (image-file "A:¥GRAPH¥BLOP05.GPC")
  ((cmd 198) 32 5 127 66 0)
  (image-mem 1 1)
  (image-file "A:¥GRAPH¥BLOP06A.GPC") (image-mem 1 1)
  ((cmd 198) 32 5 127 66 15)
  (proc 4) (str "Cooger: ") (proc 1)
     (str "The cat is certainly dead, right? It would be odd if")
  (str "it was still alive after all that.")
  (proc 3)
  (proc 4) (str "Cole: ") (proc 0)
   (str "Doc, can you stop? I believe you.")
  (proc 3)
  (proc 4) (str "Cooger: ") (proc 1)
     (str "No, you're doubting. You probably think I've gone" 'br)
  (str "mad... You must see this with your own eyes!")
  (proc 3)
  (proc 4) (str "Cooger: ") (proc 1)
     (str "The liquid in here is a sample of the drug. Look at" 'br)
  (str "your watch after I inject it. According to my data, it'll" 'br)
  (str "take 13 seconds until revival.")
  (proc 3)
  (proc 4) (str "Cooger: ") (proc 1)
     (str "Here we go...")
  (proc 3)
  (image-file "A:¥GRAPH¥BLOP06A.GPC") (image-mem 1 1)
  ((cmd 193) 0 "A:¥ANIME¥BLOP06.GPA")
  ((cmd 194) 0 "ｵ..ｶ..ｸ.ｹ.ｺ.ｷ.ｹ.ｸ..ｶ..ｵ. .")
  ((cmd 196) 0 0) (delay 50 0)
  ((cmd 196) 0 1) (delay 4 0)
  ((cmd 196) 0 2) (delay 4 0)
  ((cmd 196) 0 3) (delay 4 0)
  ((cmd 196) 0 4)
  (sound '|| 0)
; (sound 'cd 0)								  FMT
  (image-file "A:¥GRAPH¥BLOP06A.GPC") (image-mem 1 1)
  (sound '|se | 29)							; PC98/X68K
  (text-delay 0)
  (text-color 15)
  (repeat 3 (<> (text "　　　　　　　　　　　　　　・") (proc 19) (delay 50 0)))
  (text-reset 14)
  ((cmd 197) 0 15)
  (sound '|se | 22)
  (proc 4) (str "Cole: ") (proc 0)
   (str "No way!")
  (proc 3)
  (proc 4) (str "Cole: ") (proc 0)
   (str "It came back to life?! How?!")
  (proc 3)
  (proc 4) (str "Cooger: ") (proc 1)
     (str "Those certainly aren't post-death convulsions.")
  (proc 3)
  (proc 4) (str "Cooger: ") (proc 1)
     (str "How about it? Believe me now?!")
  (proc 3)
  (proc 4) (str "Cole: ") (proc 0)
   (str "No way... This must be a trick!")
  (proc 3)
  (sound '|| "A:¥MUSIC¥B0N_04.USO") (sound '|| 1)			; PC98/X68K
; (sound '|| 0) (sound 'cd 4)						  FMT
  (proc 4) (str "Cooger: ") (proc 1)
     (str "It's not some trick. It's moving before your eyes," 'br)
  (str "isn't it?")
  (proc 3)
  (proc 4) (str "Cole: ") (proc 0)
   (str "Doc! This is amazing! You'll win the Nobel Prize," 'br)
  (str "maybe something greater! When will you make it public?!")
  (proc 3)
  (proc 4) (str "Cooger: ") (proc 1)
     (str "We aren't there yet. Like I said, this is a" 'br)
  (str "prototype sample.")
  (proc 3)
  (proc 4) (str "Cole: ") (proc 0)
   (str "How so? Did it not just work perfectly?")
  (proc 3)
  (proc 4) (str "Cooger: ") (proc 1)
     (str "Well, there are some side effects. Animals revived" 'br)
     (str "with the drug go feral.")
  (proc 3)
  (proc 4) (str "Cole: ") (proc 0)
   (str "Feral? Like those zombies in the movies?")
  (proc 3)
  (proc 4) (str "Cooger: ") (proc 1)
     (str "Ha! Probably, but I haven't tested it on humans, so" 'br)
  (str "I'm not sure. It's against the law... I'm a scientist, not a")
  (str "doctor.")
  (proc 3)
  (proc 4) (str "Cooger: ") (proc 1)
     (str "Anyways, revived animals lose any docility they once")
  (str "had.")
  (proc 3)
  (proc 4) (str "Cooger: ") (proc 1)
     (str "I've never heard of cats who attack humans without" 'br)
  (str "being provoked, unless they have rabies.")
  (proc 3)
  (proc 4) (str "Cole: ") (proc 0)
   (str "I see. Oh Kitty, why do you attack humans? What is" 'br)
  (str "your goal?")
  (proc 3)
  (proc 4) (str "Cooger: ") (proc 1)
     (str "Don't touch it! I forgot to tell you that their" 'br)
  (str "physical strength nearly doubles!")
  (proc 3)
  (proc 4) (str "Cooger: ") (proc 1)
     (str "Do you know what the word restrain means?")
  (proc 3)
  (proc 4) (str "Cooger: ") (proc 1)
     (str "Our muscles have enough strength to break our own" 'br)
  (str "bones. Normally, you save that strength to protect your own" 'br)
  (str "body.")
  (proc 3)
  (proc 4) (str "Cooger: ") (proc 1)
     (str "Once the ferality takes over, that restrain is gone" 'br)
  (str "and it exhibits unreal strength. It could probably kill a" 'br)
  (str "human in one hit!")
  (proc 3)
  (proc 4) (str "Officer Jack: ") (proc 1)
           (str "Mr. Cooger! This is Officer Jack from the 16th")
  (str "Precinct!")
  (proc 3)
  (proc 4) (str "Officer Jack: ") (proc 1)
           (str "Open the door, Mr. Cooger!")
  (proc 3)
  (proc 4) (str "Cole: ") (proc 0)
   (str "The cops! What're we gonna do?!")
  (proc 3)
  (proc 4) (str "Officer Jack: ") (proc 1)
           (str "Open the door! This is the police!")
  (proc 3)
  (proc 4) (str "Cooger: ") (proc 1)
     (str "Cole, stay here and hide the cat in the fridge." 'br)
  (str "Don't let it bite you!")
  (proc 3)
  (proc 4) (str "Cole: ") (proc 0)
   (str "Alright!")
  (proc 3)
  (proc 4) (str "Officer Jack: ") (proc 1)
           (str "Mr. Cooger! Mr. Cooger!")
  (proc 3)
  ((cmd 197) 0 0)
  ((cmd 198) 32 5 127 66 0)
  (image-file "A:¥GRAPH¥BLOP05.GPC") (image-mem 1 1)
  ((cmd 198) 32 5 127 66 15)
  (proc 4) (str "Cooger: ") (proc 1)
     (str "Officer, what brings you here at this hour?")
  (proc 19)
  (proc 4) (str "Cole: ") (proc 0)
   (str "(This house is so old I can hear their voices through" 'br)
   (str "the walls.)")
  (proc 3)
  (proc 4) (str "Officer Jack: ") (proc 1)
           (str "Mr. Cooger, we've had reports of strange cat" 'br)
  (str "noises in the area.")
  (proc 3)
  (proc 4) (str "Cooger: ") (proc 1)
     (str "Right, there are many strays around and it's" 'br)
  (str "troubling even me. Isn't it odd to ask the police to deal" 'br)
  (str "with stray cats, though?")
  (proc 3)
  (proc 4) (str "Officer Jack: ") (proc 1)
           (str "Officer Jack: Well, they say it's not the regular noise," 'br)
  (str "that it sounds more like eerie shrieks. We've been getting" 'br)
  (str "reports since last week.")
  (proc 3)
  (proc 4) (str "Officer Jack: ") (proc 1)
           (str "I got curious, so I came to patrol.")
  (proc 3)
  (proc 4) (str "Cooger: ") (proc 1)
     (str "I see, but I haven't heard any shrieks myself.")
  (proc 3)
  (proc 4) (str "Officer Jack: ") (proc 1)
           (str "I see. May I look inside? It's routine, I" 'br)
  (str "won't be long.")
  (proc 3)
  (proc 4) (str "Cooger: ") (proc 1)
     (str "I don't mind. I have a guest now, so please be" 'br)
  (str "quick.")
  (proc 3)
  (proc 4) (str "Officer Jack: ") (proc 1)
           (str "I'm coming in, then.")
  (proc 3)
  (sound '|se | 29)							; PC98/X68K
  (text-delay 0)
  (text-color 15)
  (repeat 2 (<> (text "　　　　　　　　　　　　　　・") (proc 19) (delay 50 0)))
  (text-reset 14)
  (proc 4) (str "Officer Jack: ") (proc 1)
           (str "This your bedroom?")
  (proc 3)
  (proc 4) (str "Cooger: ") (proc 1)
     (str "Yes. Since my wife passed I've forgotten to clean" 'br)
  (str "it, so it's quite messy.")
  (proc 3)
  (proc 4) (str "Officer Jack: ") (proc 1)
           (str "Alright.")
  (proc 3)
  (text-color 15)
  (sound '|se | 29)							; PC98/X68K
  (text-delay 0)
  (text-color 15)
  (repeat 2 (<> (text "　　　　　　　　　　　　　　・") (proc 19) (delay 50 0)))
  (text-reset 14)
  (proc 4) (str "Cooger: ") (proc 1)
     (str "This is my study. All my research is collected in" 'br)
  (str "there, so please don't touch anything.")
  (proc 3)
  (proc 4) (str "Officer Jack: ") (proc 1)
           (str "Don't worry, I won't. What's in here?")
  (proc 3)
  (proc 4) (str "Cooger: ") (proc 1)
     (str "The lab. My guest is here.")
  (proc 3)
  (proc 4) (str "Officer Jack: ") (proc 1)
           (str "May I come in?")
  (proc 19)
  (proc 4) (str "Cole: ") (proc 0)
   (str "(He's coming in here? Doc, just get him to leave!)")
  (proc 3)
  (mes-jump "A:¥MES¥OPEN_2.MES")))