(mes
 (meta (engine 'ADV) (charset "pc98"))
 (seg*
  ((cmd 209) 0)
  (mouse 3 0 0)
  (text-frame 0 0 79 399)
  (text-reset 14)
  (sound '|| "A:¥MUSIC¥B0N_05.USO")
  (sound '|| 1)
  (image-file "A:¥GRAPH¥FRR.GPC")
  (image-mem 0)
  (image-file "A:¥GRAPH¥BLOP01.GPC")
  (image-mem 1)
  (exec-mem 10496 2 32 5 127 66 35 17 44 22 0 50)
  ((cmd 209) 1 10)
  (delay 50)
  (exec-mem 10496 1 35 17 44 22 32 5 127 66 8 50)
  (text-frame 17 284 76 340)
  (text-reset 14)
  (proc 0)
  (str "Ah, finally. Home at last.")
  (proc 3)
  (proc 0)
  (str
   "Man, I got worked to death painting those walls      today. Why don't they make the temps do it?")
  (proc 3)
  (proc 0)
  (str
   "Why do I have to do all the boring chores? Thanks to that, I had to work overtime again today!")
  (proc 3)
  (proc 0)
  (str "Whatever. Overtime pays well so I ain't complaining.")
  (proc 3)
  (proc 0)
  (str "God, I'm all sweaty. I should go take a shower and   relax for a bit.")
  (proc 3)
  ((cmd 198) 32 5 127 66 0)
  (sound '|se | 29)
  (text-delay 0)
  (repeat 3 (<> (text "　　　　　　　　　　　　　　・") (proc 19) (delay 50 0)))
  (text-reset 14)
  ((cmd 198) 32 5 127 66 15)
  (proc 0)
  (str "Ah, all relaxed now!")
  (proc 3)
  (proc 0)
  (str
   "I love my after-shower beer as well. Try it once, youcan never stop having them!")
  (proc 3)
  (proc 0)
  (str
   "Well. Another day of work done. I wonder when        something interesting will happen for once!")
  (proc 3)
  (proc 0)
  (str "Even if it's a massive incident that baffles the     world!")
  (proc 3)
  (sound '|se | 24)
  (exec-mem 10496 2 32 5 127 66 110 30 126 42 0 50)
  (text-frame 16 22 40 265)
  (text-reset 14)
  (delay 200 0)
  (sound '|se | 29)
  (text-frame 17 284 76 340)
  (text-reset 14)
  (proc 0)
  (str "Hm? Who could be calling this late?")
  (proc 3)
  (proc 0)
  (str "Hi, this is Cole speaking.")
  (proc 3)
  (image-file "A:¥GRAPH¥BLOP02.GPC")
  (image-mem 1 1)
  ((cmd 193) 0 "A:¥ANIME¥BLOP02.GPA")
  ((cmd 194)
   0
   "ｱｶ. .ｱ..ｴ..ｵ..ｶ.ｵ..ｱ.ｶ. .ｴ...ｵ.ｶ..ｲ.ｳ.ｵ...ｴ.ｲ.ｱ. .ｵ.ｶ.ｴ..ｶ.ｱ. .ｶ.ｱ")
  (exec-mem 10496 0 48 21 79 50 8)
  ((cmd 197) 0 15)
  (proc 1)
  (str "Cole, it's me, Cooger.")
  (proc 3)
  ((cmd 197) 0 0)
  (proc 0)
  (str "Oh, it's you, Doc.")
  (proc 3)
  (proc 0)
  (str "Why're you calling in the middle of the night?")
  (proc 3)
  ((cmd 197) 0 15)
  (proc 1)
  (str
   "It's amazing, Cole! You gotta see my latest        invention! It'll knock your socks off!")
  (proc 3)
  ((cmd 197) 0 0)
  (proc 0)
  (str
   "This again? Last time, you pumped so much blood into that artifical heart that it burst!")
  (proc 3)
  (proc 0)
  (str
   "My jacket got soaked! It was such a pain to wash it. I don't think I got rid of the smell.")
  (proc 3)
  ((cmd 197) 0 15)
  (proc 1)
  (str
   "I assure you, it's amazing! No blood this time! I  mean, less blood. Can you just come over now?")
  (proc 3)
  ((cmd 197) 0 0)
  (proc 0)
  (str "Now? I'm too tired. How about tomorrow?")
  (proc 3)
  ((cmd 197) 0 15)
  (proc 1)
  (str "Right now. I'll tell Terry about you and Sheila!")
  (proc 3)
  ((cmd 197) 0 0)
  (proc 0)
  (str "Alright! I'll be there!")
  (proc 3)
  ((cmd 197) 0 15)
  (proc 1)
  (str "Ha! I'll be waiting!")
  (proc 3)
  ((cmd 197) 0 0)
  (exec-mem 10496 0 47 20 80 51 0)
  (text-frame 23 82 40 265)
  (text-reset 14)
  (image-file "A:¥GRAPH¥BLOP01.GPC")
  (image-mem 1 1)
  (exec-mem 10496 1 110 30 126 42 32 5 127 66 8 50)
  (text-frame 17 284 76 340)
  (text-reset 14)
  (proc 0)
  (str
   "Doc's always threatening to expose Sheila and I when he wants something.")
  (proc 3)
  (proc 0)
  (str
   "Terry doesn't know I'm seeing Sheila, and he's       planning to make moves on her. He came to ask me for advice on it!")
  (proc 3)
  (proc 0)
  (str "I'll figure it out when he finds out...")
  (proc 3)
  (proc 0)
  (str
   "If I don't go now, Doc will never let me hear the endof it. I wonder what he did this time...")
  (proc 3)
  (exec-mem 10496 2 32 5 127 66 32 36 127 36 0 50)
  (exec-mem 10496 0 32 5 127 66 0)
  (sound '|| 0)
  (image-file "A:¥GRAPH¥BLOP03.GPC")
  (image-mem 1 1)
  (image-file "A:¥GRAPH¥BLOP04.GPC")
  (image-mem 1 0)
  (sound '|| "A:¥MUSIC¥B0N_04.USO")
  (sound '|| 1)
  ((cmd 193) 0 "A:¥ANIME¥BLOP04.GPA")
  ((cmd 194) 0 "ｱ. ..ｴ.ｲｳ..ｲｱｵ....ｴ..ｱ..ｵ..ｴ...ｵ..ｴ..ｵ....ｱ..ｵ..ｱ")
  (exec-mem 10496 1 32 36 127 36 32 5 127 66 8 50)
  (proc 0)
  (str "Why are you waiting here, Doc?")
  (proc 3)
  ((cmd 197) 0 15)
  (proc 1)
  (str
   "The neighbours don't know I'm home, so I couldn't  have you call to me out loud.")
  (proc 3)
  (proc 1)
  (str "I don't want anyone to know about this one.")
  (proc 3)
  ((cmd 197) 0 0)
  (proc 0)
  (str "I see. So, what's this new invention?")
  (proc 3)
  ((cmd 197) 0 15)
  (proc 1)
  (str "It's in the lab, come see.")
  (proc 3)
  ((cmd 197) 0 0)
  ((cmd 198) 32 5 127 66 0)
  (image-file "A:¥GRAPH¥BLOP05.GPC")
  (image-mem 1 1)
  (image-file "A:¥GRAPH¥BLOP04.GPC")
  (image-mem 1 1)
  ((cmd 198) 32 5 127 66 15)
  (proc 0)
  (str
   "I'm always impressed at how cool this lab is. Most   people wouldn't believe this is a university professor's    home.")
  (proc 3)
  ((cmd 197) 0 15)
  (proc 1)
  (str "Well, since my wife passed, all I have is my       research.")
  (proc 3)
  ((cmd 197) 0 0)
  (proc 0)
  (str "Oh, right... Sorry. I forgot. Don't look sad.")
  (proc 3)
  (proc 0)
  (str "I just spoke without thinking. I didn't mean to...")
  (proc 3)
  (proc 0)
  (str "Hm?")
  (proc 3)
  (proc 0)
  (str "Doc? Did you hear that? Sounded like someone moaning.")
  (proc 3)
  (proc 0)
  (str "Yeah... like a baby...")
  (proc 3)
  ((cmd 197) 0 15)
  (proc 1)
  (str "Cole, watch it!")
  (proc 3)
  ((cmd 197) 0 0)
  (image-file "A:¥GRAPH¥BLOP05.GPC")
  ((cmd 198) 32 5 127 66 0)
  (sound '|| 0)
  (image-mem 1 1)
  (image-file "A:¥GRAPH¥BLOP06.GPC")
  (image-mem 1 1)
  ((cmd 198) 32 5 127 66 15)
  (sound '|se | 3)
  (proc 0)
  (str "!!!")
  (proc 19)
  (proc 1)
  (str "Cole, duck!")
  (proc 3)
  (sound '|se | 9)
  (delay 15)
  (sound '|se | 9)
  (delay 10)
  (sound '|se | 9)
  ((cmd 198) 32 5 127 66 0)
  (image-file "A:¥GRAPH¥BLOP05.GPC")
  (image-mem 1 1)
  (image-file "A:¥GRAPH¥BLOP04.GPC")
  (image-mem 1 1)
  ((cmd 198) 32 5 127 66 15)
  (sound '|| "A:¥MUSIC¥B0N_04.USO")
  (sound '|| 1)
  (proc 0)
  (str "Woah! What's with that cat?!")
  (proc 3)
  ((cmd 197) 0 15)
  (proc 1)
  (str "Cole! Did you get bit? Scratched?! Anything?!")
  (proc 3)
  ((cmd 197) 0 0)
  (proc 0)
  (str "No. Nothing hurts. I'm alright. But anyways...")
  (proc 3)
  (proc 0)
  (str "This was your cat, wasn't it?")
  (proc 3)
  ((cmd 197) 0 15)
  (proc 1)
  (str "Yes. It's Kitty.")
  (proc 3)
  ((cmd 197) 0 0)
  (proc 0)
  (str
   "Kitty, huh? Right. Why the hell did your pet cat     attack me?! Does it have rabies?!")
  (proc 3)
  ((cmd 197) 0 15)
  (proc 1)
  (str "No. The cat died a week ago.")
  (proc 3)
  ((cmd 197) 0 0)
  (proc 0)
  (str
   "Huh?! Don't be crazy! It jumped right at me! That's  not the same quiet Kitty as before!")
  (proc 3)
  (proc 0)
  (str
   "It must be rabid! Just tell it straight. I'm not a   health inspector, ya know.")
  (proc 3)
  ((cmd 197) 0 15)
  (proc 1)
  (str "Cole. Kitty isn't rabid. You got it all wrong.")
  (proc 3)
  ((cmd 197) 0 0)
  (proc 0)
  (str
   "Got it all wrong?! What do you mean?! What's with    that week-old dead cat shit?! Shooting it was just cruel!")
  (proc 3)
  ((cmd 197) 0 15)
  (proc 1)
  (str "Listen to me, Cole!")
  (proc 3)
  (proc 1)
  (str "Kitty died a week ago. I'm certain it wasn't       rabies.")
  (proc 3)
  (proc 1)
  (str
   "I found the body just after I made the first sampleof my new resurrection drug.")
  (proc 3)
  ((cmd 197) 0 0)
  (proc 0)
  (str "Resurrection drug? Like, the kind of thing that can  revive the dead?")
  (proc 3)
  ((cmd 197) 0 15)
  (proc 1)
  (str
   "Yes. Kitty died of old age. I felt sorry for it,   but I made it my test subject.")
  (proc 3)
  ((cmd 197) 0 0)
  (proc 0)
  (str
   "Doc, I can't get what you're saying. No way you made a drug like this. Sure, you're a genius scientist, but this is the stuff of movies!")
  (proc 3)
  ((cmd 197) 0 15)
  (proc 1)
  (str
   "I know anyone would think this kind of thing is    impossible. Your reaction is quite understandable, Cole.")
  (proc 3)
  (proc 1)
  (str "Yet, I must make you realize that this isn't       sci-fi!")
  (proc 3)
  ((cmd 197) 0 0)
  (proc 0)
  (str "What're you gonna do?")
  (proc 3)
  ((cmd 197) 0 15)
  (proc 1)
  (str "Show you the drug in full force!")
  (proc 3)
  ((cmd 197) 0 0)
  (proc 0)
  (str "...")
  (proc 3)
  (image-file "A:¥GRAPH¥BLOP05.GPC")
  ((cmd 198) 32 5 127 66 0)
  (image-mem 1 1)
  (image-file "A:¥GRAPH¥BLOP06A.GPC")
  (image-mem 1 1)
  ((cmd 198) 32 5 127 66 15)
  (proc 1)
  (str
   "The cat is certainly dead, right? It would be odd  if it was still alive after all that.")
  (proc 3)
  (proc 0)
  (str "Doc. Can you stop? I believe you.")
  (proc 3)
  (proc 1)
  (str
   "No, you're doubting. You probably think I went mad!You must see this with your own eyes!")
  (proc 3)
  (proc 1)
  (str
   "The liquid in here is a sample of the drug. Look atyour watch after I inject it. According to my data, it'll   take 13 seconds until revival.")
  (proc 3)
  (proc 1)
  (str "Here we go...")
  (proc 3)
  (image-file "A:¥GRAPH¥BLOP06A.GPC")
  (image-mem 1 1)
  ((cmd 193) 0 "A:¥ANIME¥BLOP06.GPA")
  ((cmd 194) 0 "ｵ..ｶ..ｸ.ｹ.ｺ.ｷ.ｹ.ｸ..ｶ..ｵ. .")
  ((cmd 196) 0 0)
  (delay 50 0)
  ((cmd 196) 0 1)
  (delay 4 0)
  ((cmd 196) 0 2)
  (delay 4 0)
  ((cmd 196) 0 3)
  (delay 4 0)
  ((cmd 196) 0 4)
  (sound '|| 0)
  (image-file "A:¥GRAPH¥BLOP06A.GPC")
  (image-mem 1 1)
  (sound '|se | 29)
  (text-delay 0)
  (text-color 15)
  (repeat 3 (<> (text "　　　　　　　　　　　　　　・") (proc 19) (delay 50 0)))
  (text-reset 14)
  ((cmd 197) 0 15)
  (sound '|se | 22)
  (proc 0)
  (str "No way!")
  (proc 3)
  (proc 0)
  (str "It came back to life?! How?!")
  (proc 3)
  (proc 1)
  (str "Those certainly aren't post-death convulsions.")
  (proc 3)
  (proc 1)
  (str "How bout it? Believe me now?!")
  (proc 3)
  (proc 0)
  (str "No way... This must be a trick!")
  (proc 3)
  (sound '|| "A:¥MUSIC¥B0N_04.USO")
  (sound '|| 1)
  (proc 1)
  (str "It's not some trick. It's moving before your eyes, isn't it?")
  (proc 3)
  (proc 0)
  (str
   "Doc! This is amazing! You'll win the Nobel Prize!    Maybe something greater! When will you make it public?!")
  (proc 3)
  (proc 1)
  (str "We aren't there yet. Like I said, this is a        prototype sample.")
  (proc 3)
  (proc 0)
  (str "How so? Did it not just work perfectly?")
  (proc 3)
  (proc 1)
  (str
   "Well, there are some side effects. Animals revived with the drug go feral.")
  (proc 3)
  (proc 0)
  (str "Feral? Like those zombies in the movies?")
  (proc 3)
  (proc 1)
  (str
   "Ha! Probably, but I haven't tested it on humans, soI'm not sure. It's against the law. I'm a scientist, not a  doctor.")
  (proc 3)
  (proc 1)
  (str "Anyways, revived animals lose any docility they    once had.")
  (proc 3)
  (proc 1)
  (str
   "I've never heard of cats who attack humans without being provoked, unless they have rabies.")
  (proc 3)
  (proc 0)
  (str "I see. Kitty, why do you attack humans? What's your  goal?")
  (proc 3)
  (proc 1)
  (str
   "Don't touch it! I forgot to tell you that their    physical strength nearly doubles!")
  (proc 3)
  (proc 1)
  (str "You know what the word restrain means?")
  (proc 3)
  (proc 1)
  (str
   "Our muscles have enough strength to break our own  bones. Normally, you save that strength to protect your own body.")
  (proc 3)
  (proc 1)
  (str
   "Once the ferality takes over, that restrain is goneand it exhibits unreal strength. It could probably kill a   human in one hit!")
  (proc 3)
  (proc 17)
  (str "Mr. Cooger! This is Officer Jack from the    16th Precinct!")
  (proc 3)
  (proc 17)
  (str "Open the door, Mr. Cooger!")
  (proc 3)
  (proc 0)
  (str "The cops! What're we gonna do?!")
  (proc 3)
  (proc 17)
  (str "Open the door! This is the police!")
  (proc 3)
  (proc 1)
  (str
   "Cole, stay here and hide the cat in the fridge.    Don't let it bite you!")
  (proc 3)
  (proc 0)
  (str "Alright!")
  (proc 3)
  (proc 17)
  (str "Mr. Cooger! Mr. Cooger!")
  (proc 3)
  ((cmd 197) 0 0)
  ((cmd 198) 32 5 127 66 0)
  (image-file "A:¥GRAPH¥BLOP05.GPC")
  (image-mem 1 1)
  ((cmd 198) 32 5 127 66 15)
  (proc 1)
  (str "Officer, what brings you here at this hour?")
  (proc 19)
  (proc 0)
  (str "This house is so old I can hear their voices through the walls.")
  (proc 3)
  (proc 17)
  (str "Mr. Cooger, we had reports of strange cat    noises in the area.")
  (proc 3)
  (proc 1)
  (str
   "Right. There are many strays around and it's       troubling even me. Isn't it odd though to ask the police to deal with stray cats?")
  (proc 3)
  (proc 17)
  (str
   "Well, they say it's not a regular noise,     more like eerie shrieks. We've been getting reports since   last week.")
  (proc 3)
  (proc 17)
  (str "I got curious, so I came to patrol.")
  (proc 3)
  (proc 1)
  (str "I see, but I haven't heard any shrieks myself.")
  (proc 3)
  (proc 17)
  (str "Ah. May I look inside? It's routine. I won't be long.")
  (proc 3)
  (proc 1)
  (str "I don't mind. I have a guest now, so please be     quick.")
  (proc 3)
  (proc 17)
  (str "I'm coming in then.")
  (proc 3)
  (sound '|se | 29)
  (text-delay 0)
  (text-color 15)
  (repeat 2 (<> (text "　　　　　　　　　　　　　　・") (proc 19) (delay 50 0)))
  (text-reset 14)
  (proc 17)
  (str "This your bedroom?")
  (proc 3)
  (proc 1)
  (str
   "Yes. Since my wife passed I've forgotten to clean  it, so it's quite messy.")
  (proc 3)
  (proc 17)
  (str "Alright.")
  (proc 3)
  (text-color 15)
  (sound '|se | 29)
  (text-delay 0)
  (text-color 15)
  (repeat 2 (<> (text "　　　　　　　　　　　　　　・") (proc 19) (delay 50 0)))
  (text-reset 14)
  (proc 1)
  (str
   "This is my study. All my research is collected in  there, so please don't touch anything.")
  (proc 3)
  (proc 17)
  (str "Don't worry, I won't. What's in here?")
  (proc 3)
  (proc 1)
  (str "The lab. My guest is here.")
  (proc 3)
  (proc 17)
  (str "May I come in?")
  (proc 19)
  (proc 0)
  (str "He's coming in here? Doc, just get him to leave!")
  (proc 3)
  (mes-jump "A:¥MES¥OPEN_2.MES")))